### ISSUE TITLE
`className` attribute of the `<Link>` component

### ISSUE THREAD

**Issue by HelpMe-Pls** [vercel/next-learn#101]
From [this article](https://nextjs.org/learn/basics/navigate-between-pages/client-side), under the "Summary" section, there's a note:
![image](https://user-images.githubusercontent.com/43715386/200723259-4fec2a6d-b334-455f-8cbc-69d5738fd518.png)

Obviously it stated that you should add it (the `className` attribute) to the `a` tag, **_NOT_** to the `<Link>` tag. But the [cited example](https://github.com/vercel/next-learn/blob/master/basics/snippets/link-classname-example.js) clearly shows otherwise:
![image](https://user-images.githubusercontent.com/43715386/200723719-de1235ca-abb1-4f0a-92c6-09f899e6a8e0.png)

Shouldn't it be rephrased as: "add it to the `Link` tag, not to the `a` tag." ?

**Comment by leerob** [comment]
Thanks, fixing this now!
