### ISSUE TITLE
Getting uncaughtException: TypeError: t.unmask is not a function When Running a Dev Instance

### ISSUE THREAD

**Issue by frosteeze** [vercel/next-learn#102]
I am getting this error when running the project using "npm dev run"

> ready - started server on 0.0.0.0:3000, url: http://localhost:3000
> event - compiled client and server successfully in 1463 ms (154 modules)
> wait  - compiling / (client and server)...
> event - compiled client and server successfully in 486 ms (235 modules)
> error - uncaughtException: TypeError: t.unmask is not a function
>     at unmask (C:\Users\Username\nextjs-blog2\node_modules\next\dist\compiled\ws\index.js:1:1215)
>     at Receiver.getData (C:\Users\Username\nextjs-blog2\node_modules\next\dist\compiled\ws\index.js:1:17450)
>     at Receiver.startLoop (C:\Users\Username\nextjs-blog2\node_modules\next\dist\compiled\ws\index.js:1:14334)
>     at Receiver._write (C:\Users\Username\nextjs-blog2\node_modules\next\dist\compiled\ws\index.js:1:13674)
>     at writeOrBuffer (node:internal/streams/writable:392:12)
>     at _write (node:internal/streams/writable:333:10)
>     at Writable.write (node:internal/streams/writable:337:10)
>     at Socket.socketOnData (C:\Users\Username\nextjs-blog2\node_modules\next\dist\compiled\ws\index.js:1:44508)
>     at Socket.emit (node:events:513:28)
>     at addChunk (node:internal/streams/readable:324:12)

Not really sure if I did anything wrong. It doesn't seem to affect much, but seeing that error in the console is annoying.

**Comment by leerob** [comment]
Could you open an issue on the Next.js GitHub if you can still reproduce this? 🙏 That will help add more context like a reproduction, your computer details, and the Next.js version used.
