### ISSUE TITLE
Inconsistent css in tutorial

### ISSUE THREAD

**Issue by patoi** [vercel/next-learn#106]
Congratulations on the tutorial, very good!

I noticed that I was seeing something different on the screen than I should, e.g.: https://nextjs.org/static/images/learn/dynamic-routes/links.png 

**I found that globals.css are different:** https://github.com/vercel/next-learn/blob/master/basics/api-routes-starter/styles/global.css (looks good to me, same results), and https://github.com/vercel/next-learn/blob/master/basics/learn-starter/styles/globals.css (initialized on https://nextjs.org/learn/basics/create-nextjs-app/setup by "Create a Next.js app")

**Comment by manovotny** [comment]
Thanks for pointing this out, @patoi! We've got a PR open to resolve. 🙏
