### ISSUE TITLE
Spelling Mistake in code: Assets, Metadata, and CSS. `clsx` is misspelled as `cn`

### ISSUE THREAD

**Issue by ThePiyushAggarwal** [vercel/next-learn#108]
There is a spelling mistake inside the code for Alert.js component.
Please refer to the URL and image below.

Page URL: https://nextjs.org/learn/basics/assets-metadata-css/styling-tips

Image for reference: 
![image](https://user-images.githubusercontent.com/27003616/209476979-8dec1b58-2e74-4fe9-90ec-0e06c95e3fbf.png)

I will raise a PR for this if you direct me as to where is the actual code for the website.

**Comment by leerob** [comment]
Thank you! Fixing this now (the code is not open-source). Appreciate you reporting this.
