### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by vangotek** [vercel/next-learn#113]
Hi I'm just wondering if this ' ' is not the same as this ` `  . Because everytime I used this ' ' I get an error like from a link when i click the link I get 404 error. But when I change ' ' to ` ` it works fine. Are the different or is it a bug? Thanks

**Comment by vangotek** [comment]
![Screenshot 2023-03-24 150909](https://user-images.githubusercontent.com/128784344/227450300-ab35164a-59a2-46ab-aa1f-0c6984605aff.png)

**Comment by vangotek** [comment]
![Screenshot 2023-03-24 151145](https://user-images.githubusercontent.com/128784344/227450595-1128062c-e7cb-4d7c-8543-6efc8d850792.png)

**Comment by CarboxyDev** [comment]
The first screenshot uses a normal string ('/") while the second screenshot uses a template string (`).
The **${id}** can only be used in template strings and it performs string interpolation where it replaces itself with the **id** variable. The same cannot be done in normal strings without using concatenation. So in the first screenshot, the link routes to the "/posts/${id}" page which probably doesn't exist in your app.
Therefore, this is an issue with your app's code and not NextJS.

More on template strings: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by manovotny** [comment]
@CarboxyDev explained it perfectly. 😊
