### ISSUE TITLE
typeError-...is not a function in doc

### ISSUE THREAD

**Issue by RaisulislamRimon** [vercel/next-learn#114]
Error: [https://prnt.sc/K2MT1kktDS4b](https://prnt.sc/K2MT1kktDS4b)
<br>
I found this error while I was working on my machine. Then I solved it. This also needs to be changed in the Next.js documentation and GitHub also so that no one else has the same problem/error.
<br>
Next.js doc: `https://nextjs.org/learn/basics/dynamic-routes/implement-getstaticprops` <br>
Folder directory: `next-learn/basics/dynamic-routes-step-1/pages/posts/[id].js`
<br>
`https://github.com/vercel/next-learn/blob/master/basics/dynamic-routes-step-1/pages/posts/%5Bid%5D.js`
<br>
Line no 2:
`import { getAllPostIds, getPostData } from '../../lib/posts'`
<br>
Replace it with this line:
`import getAllPostIds, { getPostData } from "../../lib/posts";`
<br>
Thank you.

**Comment by RaisulislamRimon** [comment]
I hope this will solve the error/problem.

**Comment by manovotny** [comment]
@RaisulislamRimon this change should not be necessary. `getAllPostIds` is not a default export, and thus, needs to be imported with the curly brackets.
