### ISSUE TITLE
Create a Next.js App Setup lesson lists incorrect minimum supported Node.js version

### ISSUE THREAD

**Issue by icyJoseph** [vercel/next-learn#117]
The https://nextjs.org/learn/basics/create-nextjs-app/setup page says:

> If you don’t have Node.js installed, [install it from here](https://nodejs.org/en/). You’ll need Node.js version 10.13 or later.

But the docs https://nextjs.org/docs/upgrading#v13-summary say:

> The minimum Node.js version has been bumped from 12.22.0 to 14.6.0, since 12.x has reached end-of-life.

**Comment by manovotny** [comment]
Updated in #133 and within the course.
