### ISSUE TITLE
than a wrong of [id].js file!

### ISSUE THREAD

**Issue by mxdljwxx** [vercel/next-learn#118]
**run this demo(blog) , happen a  error of date.js:Server error,rangerERROR:Invalid time value**
tip format() fucntion  (No.6 line)
it  not date error , that function post(postData) of [id].js file  sent a undifine(null) data var!
wrong is [id].js  getStaticProps() function:
  return{
        props:{                                 //{} is Multiple packing
            postData
             }
         }
**solution is:**
1.delete {} of "postData",right is :  
    return{
         props:postData
}
2. modify   var of  "postData" object  in  Post function:
    postData.title   ==>   postData.postData.title
    postData.date  ==>   postData.postData.date    //not   "Invalid  time  value " error
    postData.contentHtml  ==>  postData.postData.contentHtml

demo is nice !!

**Comment by manovotny** [comment]
I tried to reproduce the issue you described above, but the current code in the `demo` folder runs and builds locally just fine. If you're still having issue, can you please try and create a pull request with the changes you think are needed?
