### ISSUE TITLE
Issue with creating next app

### ISSUE THREAD

**Issue by BockajAndrej** [vercel/next-learn#137]
npx create-next-app nextjs-blog
>> 
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path C:\Users\andrej.bockaj\AppData\Roaming\npm
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, lstat 'C:\Users\andrej.bockaj\AppData\Roaming\npm'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: C:\Users\andrej.bockaj\AppData\Local\npm-cache\_logs\2023-09-03T15_08_18_322Z-debug-0.log

node.js - 18.17.1

windows 11 pro

**Comment by cynfinity** [comment]
Your node.js is the current version. check the npm to see if you have the latest version. You may do this by entering the following in your terminal: 
npm -v
if you need to update the no you may enter the following in your terminal:
npm install -g npm@latest

Also check to see the path is correct and the spelling

ENOENT errors 'File or Directory Does Not Exist': The path specified in the command or script you're running does not point to an existing file or directory.

**Comment by jintu-das** [comment]
was facing the same issue, worked after @cynfinity solution. thanks

**Comment by manovotny** [comment]
I am going to close the issue based on @cynfinity's reply. I am going to close the issue, but please let us know if you're still experiencing issues, @BockajAndrej.
