### ISSUE TITLE
Add package to render Markdown in HTML

### ISSUE THREAD

**Issue by Edmond0116** [vercel/next-learn#176]
I found that in #170 didn't provide the corresponding package we should import.

The following are packages we should import:

```
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import remarkParse from "remark-parse";
import remarkHtml from "remark-html";
import { unified } from "unified";
```
It would fix the markdown not rendering in HTML.

**Comment by manovotny** [comment]
I don't believe this is necessary. Please [read my comment here](https://github.com/vercel/next-learn/issues/170).
