### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'useReducer')     at Object.useReducer (react.development.js:1626:1)

### ISSUE THREAD

**Issue by rafaeldevvv** [vercel/next-learn#203]
I just followed [next js setup tutorial](https://nextjs.org/learn/basics/create-nextjs-app/setup) and got a lot of errors:

client.js:1 Warning: An error occurred during hydration. The server HTML was replaced with client content in <div>. 

client.js:1 Warning: Container: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.

Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

Uncaught (in promise) Error: Cancel rendering route

Uncaught TypeError: Cannot read properties of null (reading 'useReducer')

client.js:1 The above error occurred in the <ReactDevOverlay> component

**Comment by rafaeldevvv** [comment]
Hey @delbaoliveira, the problem was that I was using the last versions of the react, react-dom and next packages. After installing the dependencies below, everything worked fine although new features of next.js and react were not available because those packages are outdated:

```json
{
  "dependencies": {
      "next": "^12.1.0",
      "react": "^17.0.2",
      "react-dom": "^17.0.2"
  }
}
```

**Comment by ChibuzoEkwue** [comment]
Having the same issues.

**Comment by leerob** [comment]
I am not able to reproduce this. Please open a new issue if you are still having trouble here. Thank you!
