### ISSUE TITLE
Quiz says none of the options are correct

### ISSUE THREAD

**Issue by newtoallofthis123** [vercel/next-learn#226]
The quiz given after the first section in the Chapter 13 "Handling Errors" says none of the options is right

The browser I am using is Firefox on Ubuntu, but I was able to reproduce this on a mobile phone as well

[Screencast from 2023-10-26 22-27-29.webm](https://github.com/vercel/next-learn/assets/78465651/ba84aba5-8949-4cd7-bad7-c282e820128e)

I think the right answer should be `not-found.tsx`. 

Edit: Couldn't really find the tutorial repo, so sorry if this bug was something you guys were already tracking internally...just came across it so reported it😅

**Comment by timeyoutakeit** [comment]
Thank you for filing! 🙏 We have a fix on the way

**Comment by newtoallofthis123** [comment]
Good to know :)
