### ISSUE TITLE
Spelling mistake in Chapter 3 - Optimizing Fonts and Images

### ISSUE THREAD

**Issue by ajtruex** [vercel/next-learn#238]
[Chapter 3 - Optimizing Fonts and Images | Adding the desktop hero image](https://nextjs.org/learn/dashboard-app/optimizing-fonts-images#adding-the-desktop-hero-image)

Under the "Adding the desktop hero image" section.

![CleanShot 2023-10-27 at 04 42AM Learn Next js Optimizing Fonts and Images  Next js](https://github.com/vercel/next-learn/assets/16868226/57222b7c-9507-4128-9fc6-3037c11d154f)

**Comment by ajtruex** [comment]
Repeat of #239

**Comment by delbaoliveira** [comment]
Thank you @ajtruex, looks like this typo has been fixed.
