### ISSUE TITLE
Mistake in Tailwind class in Chapter 2

### ISSUE THREAD

**Issue by yutakobayashidev** [vercel/next-learn#240]
It's a minor detail, but the last ] at the end of `border-r-[20px]` is missing.

https://nextjs.org/learn/dashboard-app/css-styling

![screenshots 2023-10-27 18 39 33](https://github.com/vercel/next-learn/assets/91340399/bac18dc4-0257-43b2-bf48-1ebad65c07eb)

**Comment by delbaoliveira** [comment]
Thank you @yutakobayashidev, looks like this has been fixed 🙏🏼
