### ISSUE TITLE
wrong answer of Quiz chapter 2

### ISSUE THREAD

**Issue by elqessouartariq** [vercel/next-learn#241]
Search for "clsx" in your code editor, what components use it to conditionally apply class names?

The Correct answer was:
`status.tsx` and `nav-links.tsx`
However, it turns out that the "nav-links.tsx" component doesn't utilize "clsx" for this purpose

![image](https://github.com/vercel/next-learn/assets/73233952/5f8743cc-02a1-476b-98f1-8dc3f57b3fe8)

**Comment by sugitlab** [comment]
duplicate #232

**Comment by delbaoliveira** [comment]
Thank you @elqessouartariq 🙏🏼 . Updated the quiz, should be landing soon :)
