### ISSUE TITLE
Next Learn: confusing sentence

### ISSUE THREAD

**Issue by MarcoPeretti** [vercel/next-learn#242]
The Showing Active Links section contains this sentence "The active link should be displayed with blue text and a light gray background." before showing how to use clsx to actually change the link color.

I think it is a little confusing a just assigning usePathname() to a variable is not sufficient. Furthermore, after the clsx example you have a similar statement "Save and check your localhost. You should now see the active link highlighted in blue.", which is correct.

**Comment by delbaoliveira** [comment]
Hey @MarcoPeretti, I can see why this might be confusing. How's this? 

> You can use the `clsx` library introduced in the chapter on [CSS styling](/learn/dashboard-app/css-styling) to conditionally apply class names when the link is active. When `link.href` matches the `pathname`, the active link should displayed with blue text and a light blue background.
