### ISSUE TITLE
Type error: Cannot find module '@/app/ui/fonts' or its corresponding type declarations.

### ISSUE THREAD

**Issue by olllayor** [vercel/next-learn#243]
Type error: Cannot find module '@/app/ui/fonts' or its corresponding type declarations.

  1 | import { GlobeAltIcon } from '@heroicons/react/24/outline';
> 2 | import { lusitana } from '@/app/ui/fonts';
    |                          ^
  3 |
  4 | export default function AcmeLogo() {
  5 |   return (

**Comment by yikayiyo** [comment]
There is no such a file, create one 😸.

**Comment by mrinmoyf2** [comment]
@yikayiyo
Create a file under the app/ui directory 'fonts.ts'.

`import { Inter , Lusitana} from 'next/font/google';

export const inter = Inter({ 
    subsets: ['latin'] 
});

export const lusitana = Lusitana({
    weight: ['400', '700'],
    subsets: ['latin'],
  });`
  
Then Deploy your project.
