### ISSUE TITLE
Next Learn: page.tsx wrong path - missing (overview) - chapter 9

### ISSUE THREAD

**Issue by MarcoPeretti** [vercel/next-learn#247]
the section streaming a component refers to page.tsx old path, that is, before having been moved to dashboard/(overview)

"Delete all instances of fetchRevenue() and its data from /dashboard/page.tsx:"

should be:

"Delete all instances of fetchRevenue() and its data from /dashboard/(overview)/page.tsx:"

The same path should be updated in the code that follow that sentence (see screenshot)

![Screenshot 2023-10-27 at 17 37 37](https://github.com/vercel/next-learn/assets/128880/bc44662d-1d5c-466b-a058-7be3f63b3c06)

**Comment by delbaoliveira** [comment]
Thank you @MarcoPeretti 🙏🏼 . Updated, should be landing soon!
