### ISSUE TITLE
Next Learn: wrong path for InvoicesTableSkeleton in Chapter 11

### ISSUE THREAD

**Issue by MarcoPeretti** [vercel/next-learn#249]
Hello,

/dashboard/invoices/page.tsx imports the following:

import { InvoicesTableSkeleton } from '@/app/ui/dashboard/skeletons';

but it should rather be:

import { InvoicesTableSkeleton } from '@/app/ui/skeletons';

**Comment by delbaoliveira** [comment]
Thank you @MarcoPeretti, fixed the imports. Should be landing soon 🙏🏼
