### ISSUE TITLE
Ch. 4: signOut module missing, build error

### ISSUE THREAD

**Issue by julianriise** [vercel/next-learn#250]
Help!

Unable to compile localhost:3000/dashboard:
<img width="690" alt="Screenshot 2023-10-27 at 23 14 04" src="https://github.com/vercel/next-learn/assets/77626314/fcc0a866-04bd-49f6-91ec-8ac0387b54a2">

Because of this missing module error:
<img width="690" alt="Screenshot 2023-10-27 at 23 12 50" src="https://github.com/vercel/next-learn/assets/77626314/42f906a1-946c-4645-bb31-ab2c30dd9787">

**Comment by neslob** [comment]
Remove the import. You will add it in chapter 14 https://nextjs.org/learn/dashboard-app/adding-authentication#adding-the-logout-functionality

**Comment by julianriise** [comment]
That partly works, however there are a bunch of imports and variables that are raising issues as I progress through the chapters. Did the creators try to follow the tutorial themselves from a beginner perspective?

As a beginner learner, I'm not smart enough to pin-point the issue for each chapter, this is a general observation, causing frustration. I want to learn more, but the issues are preventing me as a beginner.

**Comment by StephDietz** [comment]
Hey @julianriise, thanks for your feedback! This import has been removed as it should not be there at this point in the course. This is a new course, so we're continuing to improve it and iron out any kinks! If you run into  any other issues, feel free to continue to post them here. We read all issues and make the necessary updates 👍
