### ISSUE TITLE
Docs: Broken Link in Chapter 1 of new Learn Next.js

### ISSUE THREAD

**Issue by randseay** [vercel/next-learn#266]
### Summary
In [Chapter 1](https://nextjs.org/learn/dashboard-app/getting-started) of the new Learn Next.js docs, under the section "Creating a new project", there is a broken link:

<img width="1073" alt="image" src="https://github.com/vercel/next-learn/assets/4110122/9c9e5c6d-9457-4a0a-a487-db65b8cb507b">

The external link "starter example" navigates to https://github.com/vercel/next-learn/tree/main/dashboard/01-getting-started, which 404s

<img width="1421" alt="image" src="https://github.com/vercel/next-learn/assets/4110122/245c9cf4-fdee-47a2-a7bc-ab76895a77fd">

I expect it may need to link to https://github.com/vercel/next-learn/tree/main/dashboard/starter-example because the code snippet references it.

**Comment by delbaoliveira** [comment]
Thank you for raising this @randseay, updated, should be landing soon 🙏🏼
