### ISSUE TITLE
Wrong solution image in Creating Layouts & Pages

### ISSUE THREAD

**Issue by utsavsingh899** [vercel/next-learn#272]
Link: https://nextjs.org/learn/dashboard-app/creating-layouts-and-pages#practice-creating-the-dashboard-pages

The solution image should point to the correct route but it's wrong.

Intended solution should be like:
1. app/page.tsx -> /
2. app/dashboard/page.tsx -> /dashboard
3. app/dashboard/customers/page.tsx ->  /dashboard/customers
4. app/dashboard/invoices/page.tsx -> /dashboard/invoices

**Comment by delbaoliveira** [comment]
Thank you for raising this @utsavsingh899 🙏🏼 . Pushed a fix, should be landing soon.
