### ISSUE TITLE
Chapter 9 - Import Card doesn't exist

### ISSUE THREAD

**Issue by jhern61** [vercel/next-learn#273]
In Chapter 9 - Streaming, we're tasked to update /dashboard/page.tsx 

In the code snippet area we have `import Card from '@/app/ui/dashboard/card';
`However, this file is never given. 
![image](https://github.com/vercel/next-learn/assets/10925022/5ebebb93-8fd1-4423-8c58-b3883afcf67f)

Files in the UI Dashboard from Chapters 1-9:
![image](https://github.com/vercel/next-learn/assets/10925022/c716f67d-164c-4564-8408-9b78bf358eb3)

**Comment by Woozl** [comment]
It's a named export in that file, the course is incorrect. Use:

```ts
import { Card } from '@/app/ui/dashboard/cards';
```

It is a bit confusing because the next part of the course involves using the `Cards` component, which groups all 4 together, and *is* the default export.

**Comment by delbaoliveira** [comment]
Yes, the import is wrong. It should be **/cards** not **/card**, will push a fix. 

@Woozl  To make it less confusing, I'll rename <Cards> to <CardWrapper /> to indicate that it wraps cards.
