### ISSUE TITLE
Revalidate path needs to be updated in the edit section

### ISSUE THREAD

**Issue by mattjared** [vercel/next-learn#277]
On the `https://nextjs.org/learn/dashboard-app/mutating-data` page in the "edit invoice" section the revalidate path suggestion is `revalidatePath('/dashboard/invoices');` and I think it needs to be something else. When I update a form the data changes in the Table but when I updated it again the field data is the first value (not the new value). After doing a hard refresh it updates the values. I think something like `revalidatePath('/dashboard/invoices/[id]/edit');` is the answer here?

**Comment by delbaoliveira** [comment]
Thank you for raising this @mattjared 🙏🏼 . It looks like the `fetchInvoiceById` function was cached, added `noStore()` so that it fetches fresh data when you visit the edit invoice page again. Here's the PR:
