### ISSUE TITLE
Login not working, Functions cannot be passed directly to Client Components

### ISSUE THREAD

**Issue by ricardovelero** [vercel/next-learn#279]
After logging in correctly, I get this error:

Unhandled Runtime Error

Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".
  <form action={function} children=...>

I have the code exactly as the example. The only difference I can think of is that I'm running node ver 21.1. Maybe downgrading to minimal node version will work? Am I missing something? Thanks in advance.

**Comment by AlistairFR** [comment]
Make sure you have `'use server';` at the top of your `actions.ts` file. If it's regarding the Sidenav signOut button, here is the correct syntax to use inside `sidenav.ts` :
`<form action={async () => {'use server'; await signOut(); }}>`
I hope this helps.

**Comment by ricardovelero** [comment]
At the end, I just erased everything I typed, and just forked the final version. There must have been something, but definitely I had “user server” in actions.ts. It was the first thing I checked. Anyway, thanks a lot for the help!

**Comment by ricardovelero** [comment]
Something I must have typed wrong.
