### ISSUE TITLE
Chapter 12 - Mutating Data code error

### ISSUE THREAD

**Issue by ElSalvo96** [vercel/next-learn#282]
Hello,
I notice some code base errors in Chapter 12.

[3. Fetch the specific invoice section](https://nextjs.org/learn/dashboard-app/mutating-data#3-fetch-the-specific-invoice)
Typescript checking error: Form takes as a prop `InvoiceForm ` that it shouldn't be `undefined`, but the invoice variable taken from `fetchInvoiceById ` could be

[Deleting an invoice section](https://nextjs.org/learn/dashboard-app/mutating-data#deleting-an-invoice)
I have found theese two error in the code example.

- /app/ui/invoices/buttons.tsx, have different code base. The right code should be this:
```
export function DeleteInvoice({ id }: { id: string }) {
	return (
		<form action={deleteInvoice}>
			<input type='hidden' name='id' value={id} />
			<button className='rounded-md border p-2 hover:bg-gray-100'>
				<span className='sr-only'>Delete</span>
				<TrashIcon className='w-5' />
			</button>
		</form>
	);
}
```

- /app/lib/actions.ts, missing the Zod check. The right code should be this:
```
const DeleteInvoice = InvoiceSchema.pick({ id: true });

export async function deleteInvoice(formData: FormData) {
	const { id } = DeleteInvoice.parse({
		id: formData.get('id'),
	});
	await sql`DELETE FROM invoices WHERE id = ${id}`;
	revalidatePath('/dashboard/invoices');
}
```

**Comment by NoEl123n** [comment]
1. I use this code and it's work, maybe the difference is your code using the input to find the id? but I'll add it anyway
`export function DeleteInvoice({ id }: { id: string }) {
  const deleteInvoiceWithId = deleteInvoice.bind(null, id);

  return (
    <form action={deleteInvoiceWithId}>
      <button className="rounded-md border p-2 hover:bg-gray-100">
        <span className="sr-only">Delete</span>
        <TrashIcon className="w-5" />
      </button>
    </form>
  );
}`

3. This code works too
`export async function deleteInvoice(id: string) {

  try{
    await sql`DELETE FROM invoices WHERE id = ${id}`;
    
  }
  catch(error){
    return {
      message: 'Database Error: Failed to Delete Invoice.',
    };
  }

  revalidatePath('/dashboard/invoices');
}`

**Comment by NoEl123n** [comment]
alright, just got to the zod validation part, i see

**Comment by delbaoliveira** [comment]
Hey @ElSalvo96, we recently updated it to use bind instead of a hidden input. You can see the solution code here: https://github.com/vercel/next-learn/pull/311/files
