### ISSUE TITLE
chapter 12 deleteinvoice Style Mismatch Between Course Curriculum and Final Code Example

### ISSUE THREAD

**Issue by choopk** [vercel/next-learn#283]
![image](https://github.com/vercel/next-learn/assets/26024002/d2b0ecc9-4aa3-476b-9a7b-a8f2c9b2d027)
![image](https://github.com/vercel/next-learn/assets/26024002/0b98fbf9-8211-4add-8d34-470e2c5d649b)

There are mismatched styles between the course curriculum and the final code example

**Comment by delbaoliveira** [comment]
Thank you @choopk, updated the code snippet to match the final example. Should be landing soon.
