### ISSUE TITLE
NextLearn: tailwind classname misspelled in chapter 3

### ISSUE THREAD

**Issue by kamal0620040** [vercel/next-learn#284]
What is the improvement or update you wish to see?
Fix the misspelled classname

Is there any context that might help us understand?
The tailwind classname antialised is misspelled as antialased in [next learn](https://nextjs.org/learn/dashboard-app/optimizing-fonts-images#:~:text=adding%20the%20Tailwind-,antialased,-class%20which%20smooths).

Does the docs page already exist? Please link to it.
https://nextjs.org/learn/dashboard-app/optimizing-fonts-images

**Comment by delbaoliveira** [comment]
Thank you @kamal0620040, fixed the spelling. Should be landing soon 🙏🏼
