### ISSUE TITLE
Chapter 14 - Accessibility useFormState client side usage

### ISSUE THREAD

**Issue by Geminii** [vercel/next-learn#285]
Hi 👋 
Thanks for this new and great **learn** path about NextJs 14 😍

Reading Chapter 14 and there is a mistake in the introduction part, because it speaks about `useFormState()` usage that is a client side hook right 😇

**Problem:**
You can prevent errors earlier by doing form validation. Let's see how to implement **_server_**-side form validation with React's useFormState hook - while keeping accessibility in mind!

**Expected:**
You can prevent errors earlier by doing form validation. Let's see how to implement **_client_**-side form validation with React's useFormState hook - while keeping accessibility in mind!

Or maybe you want to speak about the combination of both client side and server side ? 🤔 
This isn't clear 🙈

Hope `learn path` will be available to contribute more easier than create an issue 😅

**Comment by delbaoliveira** [comment]
Thank you for the feedback @Geminii, I can see why this might be confusing. 
Maybe it's worth clarifying that you're implementing form validation in Server Actions, and displaying any errors with the `useFormState` hook. 

Does this make sense: 

> Let's see how to implement server-side validation with Server Actions, and how you can show form errors using `useFormState` hook.

**Comment by Geminii** [comment]
> Thank you for the feedback @Geminii, I can see why this might be confusing. Maybe it's worth clarifying that you're implementing form validation in Server Actions, and displaying any errors with the `useFormState` hook.
> 
> Does this make sense:
> 
> > Let's see how to implement server-side validation with Server Actions, and how you can show form errors using `useFormState` hook.

Completely 🚀
Much clear and simpler 😁
