### ISSUE TITLE
Chapter 14 - Missing eslintrc config file

### ISSUE THREAD

**Issue by Geminii** [vercel/next-learn#286]
Hi 👋 

In the [using eslint accessibility plugin section](https://nextjs.org/learn/dashboard-app/improving-accessibility#using-the-eslint-accessibility-plugin-in-nextjs), its misses a step about to add the `.eslintrc.json` or `.eslintrc.js` file to run the command `npm run lint`

```json
{
  "extends": "next/core-web-vitals"
}
```

Otherwise, you can execute the command again and again with the mode selection (recommanded / base etc) only.

**Comment by ibanlopez** [comment]
They've just fixed it here: Fixes: [#304](https://github.com/vercel/next-learn/issues/304)

**Comment by Geminii** [comment]
> They've just fixed it here: Fixes: [#305](https://github.com/vercel/next-learn/pull/305)

So cool 🔥 
Thanks 🙏
