### ISSUE TITLE
Chapter 15 - Introduction part

### ISSUE THREAD

**Issue by Geminii** [vercel/next-learn#289]
Hi 👋 

A little typo mistake in introduction part : 

**Problem:**
[...] you finished the invoices _**funcionality**_ by adding form validation [...]

**Expected:**
[...] you finished the invoices **_functionalities_** by adding form validation [...]

**Comment by delbaoliveira** [comment]
Thank you @Geminii 🙏🏼  Updated the sentence to say the "invoices routes". I think it's simpler. Should be landing soon.

**Comment by Geminii** [comment]
@delbaoliveira Thank you 🙏
