### ISSUE TITLE
Next Learn: missing call to await fetchCustomers() in Ch 12

### ISSUE THREAD

**Issue by MarcoPeretti** [vercel/next-learn#292]
Step 3. Fetch the specific invoice, tell us to fetch the invoice by Id but the form expects also the list of customers.

the example should show how to also retrieve customers.

either 

customers = await fetchCustomers(); 

or, as in your code

 const [invoice, customers] = await Promise.all([
    fetchInvoiceById(id),
    fetchCustomers(),
  ]);

**Comment by delbaoliveira** [comment]
Thank you @MarcoPeretti, fixed. Should be landing soon :)
