### ISSUE TITLE
Typo in Chapter 1 - TypeScript

### ISSUE THREAD

**Issue by mandeep-s1ngh** [vercel/next-learn#293]
Definitions file should be `.ts` instead of .tsx as the project template does not provide a TSX file. It provides TS.

![image](https://github.com/vercel/next-learn/assets/92678152/f78ebf68-54ec-43cb-976d-11f33da8acf3)

**Comment by delbaoliveira** [comment]
Thank you @mandeep-s1ngh, fixed. Should be landing soon 😄
