### ISSUE TITLE
Typo in chapter 5 docs

### ISSUE THREAD

**Issue by willholmeswastaken** [vercel/next-learn#296]
When I got to the automatic code splitting segment in chapter 5 I noticed a typo / grammar error.

It feels like it should read something like: `Furthermore, in production` or `Furthermore, in a production environment`

<img width="1146" alt="Screenshot 2023-10-29 at 17 10 16" src="https://github.com/vercel/next-learn/assets/13040458/bb5ea477-3094-4bf9-a1c7-2c2674ace8a4">

**Comment by chrisb2244** [comment]
In the same screenshot, there's probably a missing "the" in the first paragraph, between "where" and "browser".
(i.e. it would be better as "where [the] browser loads all"...)

**Comment by delbaoliveira** [comment]
Thank you, fixed! Should be landing soon 🙏🏼
