### ISSUE TITLE
Images don't work on production

### ISSUE THREAD

**Issue by mattjared** [vercel/next-learn#299]
Deploying the site to Vercel has broken images by default 

<img width="1726" alt="CleanShot 2023-10-29 at 15 21 28@2x" src="https://github.com/vercel/next-learn/assets/1571899/473d057c-3b85-4b2f-a5f3-dff4fbdf3a90">

**Comment by mattjared** [comment]
I think in the auth section we break images. This middleware...

```import NextAuth from 'next-auth';
import { authConfig } from './auth.config';
 
export default NextAuth(authConfig).auth;
 
export const config = {
  // https://nextjs.org/docs/app/building-your-application/routing/middleware#matcher
  matcher: ['/((?!api|_next/static|_next/image|favicon.ico).*)'],
};```

i think incorrectly breaks next images somehow

**Comment by mattjared** [comment]
i changed it to `  matcher: ['/((?!api|_next/static||favicon.ico).*)'],`

**Comment by delbaoliveira** [comment]
Thank you @mattjared, this has to do with the matcher regex for the code block not being in sync with the example. I'll push a PR to update the code.
