### ISSUE TITLE
Inconsistent `usePathname()` vs `usePathName()` in Ch5.

### ISSUE THREAD

**Issue by chrisb2244** [vercel/next-learn#301]
![image](https://github.com/vercel/next-learn/assets/7201433/b9b4bb94-41e7-4c81-82aa-609076941b16)

The text uses `usePathName()` (linking to the [use-pathname page](https://nextjs.org/docs/app/api-reference/functions/use-pathname), which gives the correct `usePathname()`.

**Comment by delbaoliveira** [comment]
Thank you! Fixed :)
