### ISSUE TITLE
Confusing (and wrong?) example in Ch11 with searchParams

### ISSUE THREAD

**Issue by chrisb2244** [vercel/next-learn#302]
The documentation shows

> The replace(${pathname}?${params.toString()}); command updates the URL with the user's search data. For example, /dashboard/invoices?query=lee if the user is on page 3.

but this looks like the result of mixing an example for pagination with an example for querying maybe a username/person (lee vs page 3).

**Comment by delbaoliveira** [comment]
Hey @chrisb2244 👋🏼 you are right, updated the wording. Should be landing soon.
