### ISSUE TITLE
undefined type for 'invoice' in Ch 12 

### ISSUE THREAD

**Issue by NoEl123n** [vercel/next-learn#303]
I got this '{
  id: string;
  customer_id: string;
  amount: number;
  status: 'pending' | 'paid';
} | undefined' type 
returned by fetchInvoiceById(id) while the 'invoice' variable in EditInvoiceForm() ask for InvoiceForm type, I already tried to change the 'invoice' variable in EditInvoiceForm() into 
'{
  id: string;
  customer_id: string;
  amount: number;
  status: 'pending' | 'paid';
}' type
but I still got this issue because of the " | undefined" part

and I have no clue how to debug it at all now

![image](https://github.com/vercel/next-learn/assets/51993160/282d3bef-6417-4c99-a410-844e347fbbba)
![image](https://github.com/vercel/next-learn/assets/51993160/2d1d762c-84c0-4253-bc96-b26a28a33cdf)

**Comment by spacecat** [comment]
I'm also experiencing the same error. 

Vercel deployment breaks also:



```
Failed to compile.
--
18:35:59.976 |  
18:35:59.976 | ./app/dashboard/invoices/[id]/edit/page.tsx:24:13
18:35:59.977 | Type error: Type '{ amount: number; id: string; customer_id: string; status: "pending" \| "paid"; } \| undefined' is not assignable to type 'InvoiceForm'.
18:35:59.977 | Type 'undefined' is not assignable to type 'InvoiceForm'.
18:35:59.977 |  
18:35:59.977 | 22 \|         ]}
18:35:59.977 | 23 \|       />
18:35:59.977 | > 24 \|       <Form invoice={invoice} customers={customers} />
18:35:59.977 | \|             ^
18:35:59.978 | 25 \|     </main>
18:35:59.978 | 26 \|   );
18:35:59.978 | 27 \| }
18:36:00.043 | Error: Command "npm run build" exited with 1


```

**Comment by NoEl123n** [comment]
I see @Woozl 
yeah I just found it too in the final-example, but thanks for the explanation, it's cleared the reason for the error for me :)
@spacecat try the fix by Woozl's comment
