### ISSUE TITLE
Ch 14 - A11y eslint config

### ISSUE THREAD

**Issue by ibanlopez** [vercel/next-learn#304]
First things first, I want to thank you all the team involved in this amazing learning resource.

## https://nextjs.org/learn/dashboard-app/improving-accessibility#using-the-eslint-accessibility-plugin-in-nextjs

in this part of the docs which explain how to config the eslint plugin, it doesn't actually create the .eslintrc.json files when running the script: "next lint".

## Problem description

It points explains the next steps literally:

1. npm run lint
2.  You should see the following warning:

`
./app/ui/invoices/table.tsx
45:25  Warning: Image elements must have an alt prop,
either with meaningful text, or an empty string for decorative images. jsx-a11y/alt-text
`

But this doesn't happen because running the script actually installs 'eslint' and 'eslint-config-next' devDdependencies, but this does not creaate the **.eslintrc.json** file.

## Questions 

It's not quite clear at this point whether we should follow the eslint config steps in the docs or it is intended that we should creaate manually this file and proceed with the docs for configuring.

Maybe this should be noted or point to this step between 1 and 2 steps on the chapter 14 documentaation.

Thank you so much for this resource anyways.

**Comment by delbaoliveira** [comment]
Thank you for raising this @ibanlopez  🙏🏼 . This issue has been addressed here: https://github.com/vercel/next-learn/pull/305
