### ISSUE TITLE
Chapter 12 - Replace hidden input field with the bind method for server actions

### ISSUE THREAD

**Issue by webdevelukas** [vercel/next-learn#308]
In this two sections of chapter 12 the id of the invoice is sent with a hidden input field in the form:
https://nextjs.org/learn/dashboard-app/mutating-data#4-pass-the-id-to-the-server-action
https://nextjs.org/learn/dashboard-app/mutating-data#deleting-an-invoice

Isn't this the perfect case to use the `bind` method for server actions instead: 
https://nextjs.org/docs/app/api-reference/functions/server-actions#binding-arguments

**Comment by delbaoliveira** [comment]
Hey @webdevelukas, you can use both. However, we'll be recommending `.bind()` for reasons stated here:  https://github.com/vercel/next.js/pull/56164

PR to update: https://github.com/vercel/next-learn/pull/311. Changes should be landing in the nextjs.org/learn soon.
