### ISSUE TITLE
Chapter 3 - Incorrect Global Styles Import

### ISSUE THREAD

**Issue by sdornan** [vercel/next-learn#310]
In chapter 2, you are told to add
```typescript
import '@/app/ui/global.css';
``` 
to `/app/layout.tsx` to import global styles.

However, in chapter 3, you are told to add a font to this file, and the full snippet looks like this:
```typescript
import './global.css';
import { inter } from '@/app/ui/fonts';
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
```

The global css import should be
```typescript
import '@/app/ui/global.css';
```
for consistency and because an error is generated if you copy the whole snippet as is.

**Comment by delbaoliveira** [comment]
Thank you @sdornan, updated, should be merged shortly.
