### ISSUE TITLE
Chapter15 Adding Authentication: Request to add environment variables

### ISSUE THREAD

**Issue by YukiOnishi1129** [vercel/next-learn#321]
If you do not specify `AUTH_SECRET` and `AUTH_URL` in the environment variables, the authentication process will not be executed by middleware.

It would be better to indicate that the following two are added to the .env settings display on the following page.

- Correction page
https://nextjs.org/learn/dashboard-app/adding-authentication

- Notation content of `.env`
````
AUTH_SECRET=your-secret-key
AUTH_URL=http://localhost:3000/api/auth
````

If you do not include the `AUTH_URL` in the `.env`, auth will be null in the following process in `auth.config.ts`.

````
callbacks: {
    authorized({ auth, request: { nextUrl } }) {
      const isLoggedIn = !!auth?.user;
      const isOnDashboard = nextUrl.pathname.startsWith('/dashboard');
      if (isOnDashboard) {
        if (isLoggedIn) return true;
        return false; // Redirect unathenticated users to login page
      } else if (isLoggedIn) {
        return Response.redirect(new URL('/dashboard', nextUrl));
      }
      return true;
    },
  },
````

Relevant part
https://github.com/vercel/next-learn/blob/main/dashboard/final-example/auth.config.ts#L13

Thank you very much for your cooperation.

**Comment by delbaoliveira** [comment]
Hey @YukiOnishi1129, thank you for raising this up and for opening the PR 🙏🏼 

I've updated the wording in the chapters to be clearer that users should: 

1. Rename the `.env.example` file to `.env`
2. Check that the `AUTH_URL` variable is present. 
3. Add their secret to `AUTH_SECRET`

Changes should be landing soon, thank you again!
