### ISSUE TITLE
Incorrect parsing in Ch 12

### ISSUE THREAD

**Issue by NoEl123n** [vercel/next-learn#322]
[4. Pass the id to the Server Action](https://nextjs.org/learn/dashboard-app/mutating-data#4-pass-the-id-to-the-server-action)
in the part you add the updateInvoice action, 
![image](https://github.com/vercel/next-learn/assets/51993160/e7430459-a62f-430f-961b-f1c1a0361f6a)

it will get this error
![image](https://github.com/vercel/next-learn/assets/51993160/2f3eefa6-0d98-4b4d-954d-1d75ba6eea6f)

and the fix is really simple, just add "id: formData.get('id'),"
![image](https://github.com/vercel/next-learn/assets/51993160/9655a0d3-785e-4b60-97d8-3bfaab4cdeaf)

**Comment by delbaoliveira** [comment]
Hey @NoEl123n, that fix is correct. However, we won't recommend passing `id` using `formData` reasons stated here: https://github.com/vercel/next.js/pull/56164

The alternative is to use `bind`, we're landing the PR here: https://github.com/vercel/next-learn/pull/311

For now, here's the solution code: 

```
import { updateInvoice } from '@/app/lib/actions';
 
export default function EditInvoiceForm({...}) {
  const updateInvoiceWithId = updateInvoice.bind(null, invoice.id);
 
  return (
    <form action={updateInvoiceWithId}>
      <input type="hidden" name="id" value={invoice.id} />
    </form>
  );
}
```

Then, in the Server Action: 

```
export async function updateInvoice(id: string, formData: FormData) {
  const { customerId, amount, status } = UpdateInvoice.parse({
    customerId: formData.get('customerId'),
    amount: formData.get('amount'),
    status: formData.get('status'),
  });
```

These snippets will be updated in the chapter shortly :)

**Comment by NoEl123n** [comment]
oh I see, thanks

**Comment by NoEl123n** [comment]
wait @delbaoliveira 
if we use .bind, then after ch 14 it should be like this right?

**Comment by NoEl123n** [comment]
but if I use id from formData like in the final-example before last update it didn't unresponsive like that, and it's just going no response at all, no error not returning to /dashboard/invoice, none; and the issue in the console is just this:
![image](https://github.com/vercel/next-learn/assets/51993160/379b1ec9-54d8-4f3b-abde-961047da6b61)
