### ISSUE TITLE
Could not locate the repository for "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"

### ISSUE THREAD

**Issue by hyy110** [vercel/next-learn#323]
when i in Official website learning nextjs,i use the command npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter" to create a nextjs app.
i meeted a problem, Could not locate the repository for "https://github.com/vercel/next-learn-starter/tree/master/learn-starter". Please check that the repository exists and try again.

**Comment by hyy110** [comment]
and i click this link, i showed that 404 status

**Comment by NoEl123n** [comment]
It's npx create-next-app@latest nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/main/basics/learn-starter" when I checked it in [Create a Next.js App](https://nextjs.org/learn-pages-router/basics/create-nextjs-app/setup), maybe check it again?
![image](https://github.com/vercel/next-learn/assets/51993160/affeefd0-559b-4424-987c-c2bbbaca89e8)

**Comment by hyy110** [comment]
yeah, you are right, i guess the nextjs official documentation has not been updated.

**Comment by hyy110** [comment]
https://www.nextjs.cn/learn/basics/create-nextjs-app/setup

**Comment by NoEl123n** [comment]
ohh I see, yeah maybe the local version haven't updated
