### ISSUE TITLE
Chapter 9: Streaming

### ISSUE THREAD

**Issue by jasonaw98** [vercel/next-learn#325]
In the Streaming a Component module, the import for
import { Suspense } from 'react';
import { RevenueChartSkeleton } from '@/app/ui/dashboard/skeletons';

supposed to be 
import { Suspense } from 'react';
import { RevenueChartSkeleton } from '@/app/ui/skeletons';

**Comment by delbaoliveira** [comment]
Thank you @jasonaw98, updated. Should be landing soon.
