### ISSUE TITLE
Wrong prop type  in Chapter 11-4

### ISSUE THREAD

**Issue by chengd42** [vercel/next-learn#326]
In Chapter 11 section 4:Updating the table, the type of the `searchParams.page` should be `number` not `string` in the first code snippet.

<img width="967" alt="Screenshot 2023-10-31 at 11 07 34" src="https://github.com/vercel/next-learn/assets/12732952/d693b775-973b-4310-bcbb-bf94b747748e">

[https://nextjs.org/learn/dashboard-app/adding-search-and-pagination](url)

**Comment by delbaoliveira** [comment]
Hey @chengd42, the type returned in searchParams is a string. You can confirm it by adding `console.log(typeof searchParams?.page)`. 

We are coercing it to a number to make it work with our `fetchInvoicesPages` and `fetchFilteredInvoices` function: 

`const currentPage = Number(searchParams?.page) || 1;`

**Comment by chengd42** [comment]
I got it, thank you for the explanation!
