### ISSUE TITLE
Chapter 7: file name typo

### ISSUE THREAD

**Issue by JayYi3** [vercel/next-learn#327]
For the [Practice: Fetch data for the <Card> components](https://nextjs.org/learn/dashboard-app/fetching-data#practice-fetch-data-for-the-card-components) part of Chapter 7, the solution file path should be _/app/dashboard/page.tsx_ instead of _/app/lib/data.ts_
<img width="1059" alt="image" src="https://github.com/vercel/next-learn/assets/73229476/3714a243-3ebc-4934-9a22-367851025a77">

**Comment by delbaoliveira** [comment]
Thank you @JayYi3, updated, should be landing soon!
