### ISSUE TITLE
The image in Chapter 4 Solution is showing wrong paths

### ISSUE THREAD

**Issue by FurkanCodes** [vercel/next-learn#328]
In the "Practice: Creating the dashboard pages" solution, the image shows wrong paths. It may confuse some people.

App folder's page.tsx is proposed as Dashboard folder. Dashboard's page.tsx is proposed as Customers and so on.

**Comment by delbaoliveira** [comment]
Thank you for raising this @FurkanCodes, fixed the diagram, should be landing soon 🙏🏼

**Comment by FurkanCodes** [comment]
@delbaoliveira Your welcome! I am glad I contributed.
