### ISSUE TITLE
Dark Mode is Not working for Nextjs Basic Learn

### ISSUE THREAD

**Issue by ansulagrawal** [vercel/next-learn#333]
Dark Mode is not working for [Basic Learn](https://nextjs.org/learn-pages-router/basics/create-nextjs-app).
Images are below:
![image](https://github.com/vercel/next-learn/assets/55939700/70b73f12-6120-48c2-97a4-b37678367f53)
![image](https://github.com/vercel/next-learn/assets/55939700/788e8886-a7d7-41c3-8996-b1674ab11751)

But working in [Dashboard Learn](https://nextjs.org/learn/dashboard-app/getting-started)

Image:
![image](https://github.com/vercel/next-learn/assets/55939700/9be0cb37-2656-48f2-9140-6f5ff0e94f78)

**Comment by leerob** [comment]
The pages router version (shown on top) does not have dark mode. The new version of Learn does (on bottom).
