### ISSUE TITLE
Search hydration mismatch

### ISSUE THREAD

**Issue by flextremedev** [vercel/next-learn#334]
When opening final-example http://localhost:3000/dashboard/invoices I get 

_Warning: Did not expect server HTML to contain a \<div> in \<div>._

Could someone confirm this?

**Comment by testanib** [comment]
@flextremedev  I'm unsure of the underlying cause but I ran into the same issue and removing the dynamic placeholder for the search component seemed to have fixed it.

**Comment by flextremedev** [comment]
Yeah I had also noticed that this only occurs for some strings in the placeholder.

**Comment by delbaoliveira** [comment]
@flextremedev could you give us more information? 🙏🏼 

@testanib is right that there are some extensions that update the DOM, causing a hydration mismatch in React.

**Comment by DemaPy** [comment]
@flextremedev just check console and i am sure you can find line where you have nested divs

**Comment by delbaoliveira** [comment]
Closing as this issue is not project or Next.js related.

**Comment by flextremedev** [comment]
This is not my code. It's the final example from the learn course repository. Like I said when opening the route /invoices the warning appears in the console.
I think this should be resolved in the example because this might lead to confusion.

**Comment by mikesmo** [comment]
I can confirm also that I am getting this same error for browsers where LastPass extension is installed.
