### ISSUE TITLE
Chapter 9 - Name conflict

### ISSUE THREAD

**Issue by JayYi3** [vercel/next-learn#335]
In the [Grouping components](https://nextjs.org/learn/dashboard-app/streaming#grouping-components) section of Chapter 9, I can not find the definition of **CardWrapper**. I think it should be **Cards**, or the **Cards** below should be replaced by **CardWrapper**.

**Comment by mrdarkside** [comment]
Yeap it's a typo. In the last code example on line 6 `Cards` should be `CardWrapper`

**Comment by StephDietz** [comment]
@JayYi3 Thank you for the feedback! This typo has been fixed :)
