### ISSUE TITLE
Typos and Errors in the Learning Course

### ISSUE THREAD

**Issue by mukham12** [vercel/next-learn#336]
I created this issue in the Next.js repository initially, but I later realized that I could have done it here. For convenience, I am copy-pasting the original text. The following is a list of errors that I have identified, some of which have already been fixed (thank you for that). I will update this with more errors I find in the comments below.

### What is the improvement or update you wish to see?
I would like to see the below-mentioned issues fixed.

### Is there any context that might help us understand?

1. ~~The word `antialised` is misspelled as `antialased` on [this page](https://nextjs.org/learn/dashboard-app/optimizing-fonts-images) of the course.~~ (Fixed as of 10/31/2023)

2. ~~The word `postgres` is misspelled as `postgress` on [this page](https://nextjs.org/learn/dashboard-app/fetching-data) of the course.~~ (Fixed as of 11/03/2023)

3. ~~Incorrect code block headers in [Fetching Data for `<RevenueChart />`](https://nextjs.org/learn/dashboard-app/fetching-data#fetching-data-for-revenuechart) and [Fetching Data for `<LatestInvoices />`](https://nextjs.org/learn/dashboard-app/fetching-data#fetching-data-for-latestinvoices) sections. Should be `/app/dashboard/page.tsx`, but actually is `/app/ui/dashboard/page.tsx`.~~ (Fixed as of 11/08/2023)

**4. Incorrect code block header in [What are request waterfalls](https://nextjs.org/learn/dashboard-app/fetching-data#what-are-request-waterfalls) section. The header is `/app/pages/dashboard/page.tsx`, whereas it should be `/app/dashboard/page.tsx`**

5. ~~I don’t think it’s a major issue, but to maintain consistency on the page about [streaming,](https://nextjs.org/learn/dashboard-app/streaming) we should use `loading.tsx` throughout the whole page. Currently, there are two instances of `loading.js` on that page as well.~~ (Fixed as of 11/03/2023)

6. ~~The invoice search component, as specified in `/app/ui/search.tsx`, is referred to as `TableSearch` in [Chapter 11](https://nextjs.org/learn/dashboard-app/adding-search-and-pagination#1-capture-the-users-input). However, in the starter code, it is simply named as `Search`.~~ (Fixed as of 10/31/2023)

7. ~~`InvoicesTableSkeleton` is imported from a wrong path multiple times on [this page](https://nextjs.org/learn/dashboard-app/adding-search-and-pagination). It should be imported from `@/app/ui/skeletons`, but is actually imported from `@/app/ui/dashboard/skeletons`.~~ (Fixed as of 10/31/2023)

**8. `formData` has to be capitalized in [this section](https://nextjs.org/learn/dashboard-app/mutating-data#using-forms-with-server-actions).** 

9. ~~`revalidateTag` is misspelled as `relivateTag` in [this section](https://nextjs.org/learn/dashboard-app/mutating-data#nextjs-with-server-actions)~~ (Fixed as of 10/31/2023)

**Comment by mukham12** [comment]
10. In Chapter 12, section about [Dynamic Routes](https://nextjs.org/learn/dashboard-app/mutating-data#1-create-a-dynamic-route-segment-with-the-invoice-id), the code on the page does not match the starter code. Namely, the the `InvoicesTable` component is expecting two props (query and currentPage), but the code on the page only has one prop (invoices).

https://github.com/vercel/next-learn/blob/94f19a17aa0b916b105ac4e1911e50ce85a0ec86/dashboard/starter-example/app/ui/invoices/table.tsx#L7-L13

![image](https://github.com/vercel/next-learn/assets/55890311/35c84408-1733-4085-9c4a-dce421894ea8)

**Comment by mukham12** [comment]
11. I believe that the first line of code in the section about [deleting an invoice](https://nextjs.org/learn/dashboard-app/mutating-data#deleting-an-invoice) is redundant and wrong. It appears that the code block uses `FormSchema` identifier instead of `InvoiceSchema`. Since that line of code has nothing to do with deleting an invoice, I propose to remove that line and only keep `// ... `.

![image](https://github.com/vercel/next-learn/assets/55890311/4358c28c-86b3-4bcf-8dc1-70adf2c449d6)

**Comment by mukham12** [comment]
12. I'm being quite picky here 😄 , but in [Chapter 14](https://nextjs.org/learn/dashboard-app/improving-accessibility) of the course, it appears that the code snippet isn't properly delimited. My suggestion is to place only the hook name (highlighted in red in the image below) within the code snippet block.

![tempsnip](https://github.com/vercel/next-learn/assets/55890311/9b675a9c-8a65-4362-9682-00930e4e3ed7)

**Comment by mukham12** [comment]
13. Similarly, to keep things consistent, we need to surround hook names (`useFormStatus` and `useFormState`) in [Chapter 15](https://nextjs.org/learn/dashboard-app/adding-authentication) within code tags.

![tempsnip](https://github.com/vercel/next-learn/assets/55890311/2dc137f1-fb70-405e-ac0f-16bcdd4539ca)

**Comment by AMarlonG** [comment]
What is the solution to chapter 12 and dynamic routes? I'm following all the steps, and this is what I get ...
It all collpases when clicking the "Edit Invoice" button. 
Redone this three times now.

This is the error I'm getitng:
![Skjermbilde 2023-11-05 kl  10 55 26](https://github.com/vercel/next-learn/assets/98260184/44a4eaa6-6c30-4936-8b95-63f13d203b61)

**Comment by mukham12** [comment]
@AMarlonG The solution for that can be found in Chapter 13. Also, check [this issue](https://github.com/vercel/next-learn/issues/370) out.

**Comment by delbaoliveira** [comment]
Thank you so much for the  👀 @mukham12. Helped us 💅🏼

**Comment by mukham12** [comment]
My pleasure!

I appreciate all the hard work you have put into this @delbaoliveira, @leerob and @StephDietz.
