### ISSUE TITLE
lost images after applying auth and deploying in Ch 15

### ISSUE THREAD

**Issue by NoEl123n** [vercel/next-learn#337]
before applying auth:
![image](https://github.com/vercel/next-learn/assets/51993160/d939752b-a0f2-46e1-9e98-6e61a8cc7f7c)

after:
![image](https://github.com/vercel/next-learn/assets/51993160/f866d5a3-55f1-428d-b24b-8995d1db1916)

**Comment by NoEl123n** [comment]
oh it only happen in the deployment, but on local after adding `NEXTAUTH_URL=http://localhost:3000` and able to login+sign out, the image appear, but there are these messages in terminal tho
![image](https://github.com/vercel/next-learn/assets/51993160/32c7ac08-f5d8-4eda-8308-72cfb5d58201)

**Comment by graemen16** [comment]
Hi - yes, I noted the same. I had opened an issue on next ([57801](https://github.com/vercel/next.js/issues/57801)) but should have opened an issue here. I believe the problem is linked to the images being in /public/customers but customers not excluded in the middleware matcher regex.

**Comment by jeromemeichelbeck** [comment]
Same issue here.

Also I don't think it was mentioned that the NEXT_AUTH_URL was needed for local development.

**Comment by ramonmetzker** [comment]
> but there are these messages in terminal tho ![image](https://user-images.githubusercontent.com/51993160/279587673-32c7ac08-f5d8-4eda-8308-72cfb5d58201.png)

I stopped getting these errors when I added the folder /customers to the middleware matcher

`matcher: ["/((?!api|_next/static|_next/image|customers|.png|favicon.ico).*)"],`

Not sure if it's the best way to solve it. I think it happens because server components fetch the source image before the next/image component optimizes it, so the _next/image in the matcher doesn't work.

**Comment by flextremedev** [comment]
It was mentioned that you need AUTH_URL and AUTH_SECRET but I'm wondering if there is a different between NEXT_AUTH_URL and AUTH_URL because the latter works for me locally. However deployed I'm facing the same problem.

**Comment by steven-tey** [comment]
Hey everyone! This was actually due to the middleware matcher being configured incorrectly – sorry about that! 😅 

I've gone ahead and fixed it in https://github.com/vercel/next-learn/pull/355 so it should be working now!

**Comment by flextremedev** [comment]
Thanks. What's the first backslash in the fix needed for?

**Comment by flextremedev** [comment]
Got it. We have to escape the string.
