### ISSUE TITLE
Chapter 12 error while parsing, can be fixed by changing the omit.

### ISSUE THREAD

**Issue by ramyadoui** [vercel/next-learn#339]
### Here in chapter 12, following this code:
![Screenshot 2023-11-01 133017](https://github.com/vercel/next-learn/assets/59150162/24cbaa77-464c-4f18-abf5-edd4eebff081)

### Would result in this error:
![Screenshot 2023-11-01 133603](https://github.com/vercel/next-learn/assets/59150162/86b5bff0-bc29-4208-9a8c-7bb968f3fecb)

### Omitting the "id" from zod's schema could be a solution, because the "id" is already passed as an argument to the server action:
![Screenshot 2023-11-01 133](https://github.com/vercel/next-learn/assets/59150162/e200e514-06ee-4baf-9664-0a5174d3ae96)

**Comment by adrian-villamil** [comment]
You are in correct, if you see in the next section called [Deleting an invoice](https://nextjs.org/learn/dashboard-app/mutating-data#deleting-an-invoice), you can see they fixed this error as you did, but like they forgot to added in the previous section.
![Captura de pantalla 2023-11-02 082843](https://github.com/vercel/next-learn/assets/90985609/829f4e4b-c74a-4817-9de1-e8ab7a274993)

**Comment by ramyadoui** [comment]
Yes I noticed it. But they didn't highlight this change in the code and this could leave some people with an error and confused as to why that error exists, because they thought they did everything correctly.

![Screenshot 2023-11-02 143434](https://github.com/vercel/next-learn/assets/59150162/5881e836-1947-4ea5-b7ea-2d923b9e944b)

**Comment by dogbitcoin** [comment]
<Form invoice={invoice} customers={customers} /> this code has infos
不能将类型“{ amount: number; id: string; customer_id: string; status: "pending" | "paid"; } | undefined”分配给类型“InvoiceForm”。
  不能将类型“undefined”分配给类型“InvoiceForm”。ts(2322)
who can help me ?

**Comment by cyfyifanchen** [comment]
Duplicated #367
