### ISSUE TITLE
Problems with typescript version of cms-wordpress

### ISSUE THREAD

**Issue by mwoodpatrick** [vercel/next-learn#34]
I created a typescript version of the cms-wordpress using command:

npx create-next-app --typescript --example cms-wordpress nextjs-wp-typescript

I was somewhat surprised that it did not appear to create typescript versions of the standard files is it expected to?

I followed the docs in:

   https://nextjs.org/docs/basic-features/typescript
   https://nextjs.org/learn/excel/typescript/nextjs-types

But when I created date.tsx using the description in:

https://github.com/vercel/next-learn-starter/blob/master/typescript-final/components/date.tsx

but on rebuild I got the error:

./components/date.tsx:1:1
Type error: 'date.tsx' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.

Also looking at:

https://github.com/vercel/next-learn-starter/blob/master/typescript-final/components/layout.tsx

it does not seem like the signature of this component matches the javascript version that was generated is it correct?

Any pointers on the best way to create a typescript version of the cms-wordpress example would be much appreciated

**Comment by leerob** [comment]
I believe this is resolved now 😄
