### ISSUE TITLE
Chapter 6, Error resolving commonjs request

### ISSUE THREAD

**Issue by themuku** [vercel/next-learn#340]
Error: error - node_modules/node-gyp-build/node-gyp-build.js:21:10  Error resolving commonjs request

  19 |
  20 | function load (dir) {
> 21 |   return runtimeRequire(load.resolve(dir))
     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 22 | }
     | ^
  23 | module.exports = load
  24 |
  25 | load.resolve = load.path = function (dir) {
unable to resolve dynamic
It was not possible to find the requested file.
    Parsed request as written in source code: dynamic
    Path where resolving has started: [project]/node_modules/node-gyp-build/node-gyp-build.js
    Type of request: commonjs request
    Import map: No import map entry

**Comment by delbaoliveira** [comment]
Sorry @themuku, could you provide more context?

**Comment by themuku** [comment]
> Sorry @themuku, could you provide more context?

I followed instruction on NextJS learn but especially on this chapter i have an error when i uncomment RevenueChart i get this error

**Comment by delbaoliveira** [comment]
This seems like a module resolution error in your Node.js environment. 

Some things you can do: 

- Delete your `node_modules` folder, and run `npm i` again 
- Make sure you're using Node version `18.17.0` or above. I recommend [fnm](https://github.com/Schniz/fnm) for managing node versions. 
- And update to the latest Next.js `npm i next@latest`
