### ISSUE TITLE
Typos in Chapters 9-12

### ISSUE THREAD

**Issue by EvanZodl** [vercel/next-learn#341]
Chapter 9:
- In the [intro paragraph](https://nextjs.org/learn/dashboard-app/streaming), "Let's look at how you can **improve account for**  slow data requests" should be replaced with "Let's look at how you can **account for** slow data requests".
- ~~There are two references to `loading.js` instead of `loading.tsx`.~~ (already noted in [this issue](https://github.com/vercel/next-learn/issues/336))

Chapter 10:
- In the "Reveal the Solution" block in [this section](https://nextjs.org/learn/dashboard-app/partial-prerendering#combining-static-and-dynamic-content), `<Sidenav>` should be replaced with `<SideNav>`.
- In the same sentence, "**personalised**" should be replaced with "**personalized**" for consistency with the sentence below.

Chapter 12:
- In [this section](https://nextjs.org/learn/dashboard-app/mutating-data#type-validation-and-coercion), "**returna** string" should be replaced with “**return a** string”.
- In [this section](https://nextjs.org/learn/dashboard-app/mutating-data#1-create-a-dynamic-route-segment-with-the-invoice-id), “update the `href` of the Link **accept** the `id` prop” should be replaced with “update the `href` of the Link **to accept** the `id` prop”.

**Comment by mukham12** [comment]
Well spotted, @EvanZodl.

Just wanted to mention that I've previously addressed your second point regarding `loading.js` in my own [issue](https://github.com/vercel/next-learn/issues/336). 

The choice is yours, but I would like to suggest considering incorporating your findings into my issue to maintain a more organized and comprehensive list of errors. Thanks.

**Comment by EvanZodl** [comment]
Good catch, @mukham12. I'll remove the `loading.js` bullet point from my list.

Otherwise our issues reference different errors and typos, so I'll keep my issue open to keep both of ours succinct.

**Comment by leerob** [comment]
Thank you! Pushing a fix for these.
