### ISSUE TITLE
Chapter 14, eslint warning shouldn't have been fixed from the start

### ISSUE THREAD

**Issue by ramonmetzker** [vercel/next-learn#342]
### Chapter 14 - [Using the ESLint accessibility plugin in Next.js](https://nextjs.org/learn/dashboard-app/improving-accessibility#using-the-eslint-accessibility-plugin-in-nextjs)

Running `npm run lint` should return an ESLint warning about the missing alt on the invoices table component:

![image](https://github.com/vercel/next-learn/assets/16233109/cad27b29-32c9-4f95-990e-1a1480b010bd)

However, for some reason the alt is already there from the beginning of the project. 

![image](https://github.com/vercel/next-learn/assets/16233109/f9b558d7-1f99-4aa0-ad8d-81c31b0a0977)

I believe it has to be either removed or commented out, for learning purposes only.

**Comment by delbaoliveira** [comment]
Correct @ramonmetzker 🙏🏼 Updated, should be landing soon.

**Comment by theVDude** [comment]
Now that the 'alt' is missing, we fail in chapter 6 (setting up your database). When going to deploy on vercel, you'll get a build error (because image requires the `alt` property)
