### ISSUE TITLE
Could not locate the repository for "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example". Please check that the repository exists and try again.

### ISSUE THREAD

**Issue by sunsunmonkey** [vercel/next-learn#346]
I want to use  npx create-next-app@latest nextjs-dashboard --use-npm --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example"  to study nextjs.But i meet the error "Could not locate the repository for "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example". Please check that the repository exists and try again."

**Comment by nworbi** [comment]
I have this issue too. Am using work's VPN. Running it without 

`--example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example"`

works fine

**Comment by sunsunmonkey** [comment]
> I have this issue too. Am using work's VPN. Running it without `--example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example"` works fine

but i want to use his example😭

**Comment by delbaoliveira** [comment]
Yes @nworbi is on the right track, if you're using a VPN or accessing it from a work/school network, there may be some config that prevents you from cloning from Github.

Is that your case? If so, you can download the folder from Github instead, or try from a different network. 

Here's a related issue: https://github.com/vercel/next-learn/issues/60
More info: https://github.com/vercel/next-learn/blob/main/basics/errors/install.md

**Comment by sunsunmonkey** [comment]
> Yes @nworbi is on the right track, if you're using a VPN or accessing it from a work/school network, there may be some config that prevents you from cloning from Github.
> 
> Is that your case? If so, you can download the folder from Github instead, or try from a different network.
> 
> Here's a related issue: #60 More info: https://github.com/vercel/next-learn/blob/main/basics/errors/install.md

Thank you,i solve it

**Comment by sitp-jose** [comment]
> I want to use npx create-next-app@latest nextjs-dashboard --use-npm --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example" to study nextjs.But i meet the error "Could not locate the repository for "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example". Please check that the repository exists and try again."

when I encountered this error, I used to clone the main repo of the project. Then after I clone the project I specifically get the starter folder and rename it to 'nextjs-dashboard'.

**Comment by greatbody** [comment]
Switching to Cloudflare WARP "Zero Trust" works.

**Comment by qingtian1771** [comment]
It is not work for me what ever my VPN setting. what's the problem it is?

**Comment by greatbody** [comment]
> Cloudflare WARP "Zero Trust"

试试 Cloudflare WARP "Zero Trust"

**Comment by adamthewebguy** [comment]
I had this issue too.
To start with, I cloned the full repo and worked that way.
Later, I noticed that my node version was too old for NextJS:

```
Unsupported engine {
   package: 'create-next-app@14.1.0',
   required: { node: '>=18.17.0' },
   current: { node: 'v16.16.0', npm: '8.11.0' }
 }
```
 
I use nvm so I did this:

```
nvm install --lts
```

This installed node v20.11.0.

```
% node -v          
v20.11.0
```

And now, everything works fine.

**Comment by sunsunmonkey** [comment]
> I had this issue too.
> To start with, I cloned the full repo and worked that way.
> Later, I noticed that my node version was too old for NextJS:
> 
> ```
> Unsupported engine {
>    package: 'create-next-app@14.1.0',
>    required: { node: '>=18.17.0' },
>    current: { node: 'v16.16.0', npm: '8.11.0' }
>  }
> ```
>  
> I use nvm so I did this:
> 
> ```
> nvm install --lts
> ```
> 
> This installed node v20.11.0.
> 
> ```
> % node -v          
> v20.11.0
> ```
> 
> And now, everything works fine.

Thank you

**Comment by cnoder-wgh** [comment]
i have same, i worked it success  in node v18.17.0

**Comment by cnoder-wgh** [comment]
![image](https://github.com/vercel/next-learn/assets/15918416/0a0de39b-6756-4268-8c6b-540b910c7909)


> i have same, i worked it success in node v18.17.0

![image](https://github.com/vercel/next-learn/assets/15918416/db1db88d-c931-4ca6-950f-0187a1726bde)

**Comment by Mr-Kiran-KK** [comment]
First make sure your Node.js version 18 or higher.If it is less than 18 it will definitly throw the error: "Could not locate the repository for "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example". Please check that the repository exists and try again.
"
