### ISSUE TITLE
Docs: Fix typos in the dashboard-app Learn course

### ISSUE THREAD

**Issue by jung0han** [vercel/next-learn#348]
### What is the improvement or update you wish to see?

I would like to request the correction of typo in the dashboard-app course document.

### Is there any context that might help us understand?

I created the CSS file inside the UI folder, but when I import it from the `page.tsx` file under the `app `folder.
It fails to load because I imported it with `import styles from './home.module.css';` the css file is not imported.

Contents of the document
```js
import styles from './home.module.css';
 
//...
<div className={styles.shape}></div>;
```

Route information that needs to be changed
```js
import styles from './ui/home.module.css';
```

Please make the necessary corrections to the typos to enhance the clarity of the document. We kindly request that you review and address these corrections. Thank you.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/css-styling#css-modules

**Comment by leerob** [comment]
This should be fixed!
