### ISSUE TITLE
Are these typos?

### ISSUE THREAD

**Issue by cyfyifanchen** [vercel/next-learn#349]
![typo](https://github.com/vercel/next-learn/assets/2340896/b8954713-bf15-4112-a723-ed011e3e53eb)

**Comment by cyfyifanchen** [comment]
<img width="969" alt="image" src="https://github.com/vercel/next-learn/assets/2340896/fbfe4a85-cca1-452a-8b9c-d037dd032f69">

**Comment by cyfyifanchen** [comment]
<img width="658" alt="image" src="https://github.com/vercel/next-learn/assets/2340896/18350df0-9966-418b-a04c-a5453ac936f6">

**Comment by leerob** [comment]
Thank you! Pushing a fix for these now.
