### ISSUE TITLE
Note: Chapter 6 improvement.

### ISSUE THREAD

**Issue by hipdev** [vercel/next-learn#353]
I get an error with the bcrypt package because of my environtment( Mac with Sonoma 14.0 using Node v20.8.0 ), the solution was to install bcryptjs and replace this line in the seed.js file:

```javascript
const bcrypt = require("bcrypt");
```

with:
```javascript
const bcrypt = require("bcryptjs");
```
This is just in case someone has the same odd error because of lack of bcrypt support in your environment.

**Comment by delbaoliveira** [comment]
Hey @hipdev, thank you for the tip! I'll add it to the troubleshooting section of the course for other developers in the future. 🙌🏼
