### ISSUE TITLE
Root layout, an internal link, but has an arrow.

### ISSUE THREAD

**Issue by cyfyifanchen** [vercel/next-learn#356]
## This internal link has an arrow:
<img width="1031" alt="image" src="https://github.com/vercel/next-learn/assets/2340896/dc64cb71-5413-45c9-b79f-ec1b6a59cba4">

## These internal links have no arrows:

* <img width="1003" alt="image" src="https://github.com/vercel/next-learn/assets/2340896/a59b33d5-0a61-4627-8c02-5d9603432ef7">
* <img width="1014" alt="image" src="https://github.com/vercel/next-learn/assets/2340896/87313c8b-156d-4bb9-baeb-56cd750f2a6a">
* <img width="1058" alt="image" src="https://github.com/vercel/next-learn/assets/2340896/1fa6a61f-c9fd-4063-83e2-0764718747ee">
* <img width="989" alt="image" src="https://github.com/vercel/next-learn/assets/2340896/8138ba4a-1b0e-437a-9eb5-de5772782090">

**Comment by leerob** [comment]
External links have the arrows, internal links do not 😄

**Comment by cyfyifanchen** [comment]
They all are external, they all link to nextjs.org, but one of them(root layout) has arrow.

**Comment by delbaoliveira** [comment]
Thank you @cyfyifanchen  🙏🏼  Fixed, should be landing soon.
