### ISSUE TITLE
Method name in Chapter 12 course text does not match code block

### ISSUE THREAD

**Issue by greg-realmmap** [vercel/next-learn#357]
Mistake in course material at https://nextjs.org/learn/dashboard-app/mutating-data.

Line: 
`You can then pass your rawFormData to NewInvoice to validate the types:` 

Should be :
`You can then pass your rawFormData to CreateInvoice to validate the types:`

**Comment by StephDietz** [comment]
@greg-realmmap thank you for finding this typo! We have a PR fixing it
