### ISSUE TITLE
Function Name TYPO 

### ISSUE THREAD

**Issue by mrmahatva** [vercel/next-learn#360]
![image](https://github.com/vercel/next-learn/assets/149217201/3467ca0d-f099-4bf9-b63e-62fd26bf8d17)

import { fetchRevenue, fetchLatestInvoices } from '@/app/lib/data';

const revenue = await fetchAllRevenue();  ==> const revenue = await fetchRevenue();

**Comment by manovotny** [comment]
@mrmahatva thanks for the report. We have a PR submitted for this.
