### ISSUE TITLE
Tailwind is not component scoped

### ISSUE THREAD

**Issue by alexandreferreirafr** [vercel/next-learn#361]
Chapter : https://nextjs.org/learn/dashboard-app/css-styling

On the paragraph:

> [Tailwind](https://tailwindcss.com/) is a CSS framework that speeds up the development process by allowing you to quickly write [utility classes](https://tailwindcss.com/docs/utility-first) directly in your JSX markup. The CSS is scoped to components so you don't have to worry about style collisions or maintaining separate stylesheets.

Is saying that Tailwind CSS is component scoped, which is not true. CSS Modules are component scoped, since it generates unique classnames during build phase.

So the sentence below should be removed:

> The CSS is scoped to components so you don't have to worry about style collisions or maintaining separate stylesheets.

**Comment by manovotny** [comment]
@alexandreferreirafr thanks for the report. We have a PR created to address this.
