### ISSUE TITLE
Chapter 6: Database Seed Error

### ISSUE THREAD

**Issue by vladan345** [vercel/next-learn#362]
### Database Seed Error

When I try to run `npm run seed` command it throws `Error seeding users: error: no such user`

Node version, tried with:
v18.17.0 & v20.9.0

**Comment by Quentin-Satelix** [comment]
Hi, got the same issue

**Comment by devdanuk** [comment]
Got it working. For me, it was because the .env file was missing the actual password and few other bits. I think you need to click **Show Secret** before you hit **Copy Snippet**.

**Comment by vladan345** [comment]
I totally missed that. Thank you so much!

**Comment by delbaoliveira** [comment]
Thank you @devdanuk, it seems a few people experience this issue with the Vercel UI. Will update the chapter with this information 🙏🏼

**Comment by fraineralex** [comment]
> Got it working. For me, it was because the .env file was missing the actual password and few other bits. I think you need to click **Show Secret** before you hit **Copy Snippet**.

Thank you @devdanuk, in my case missed the values of the POSTGRES_USER and POSGRES_PASSWORD variables after paste the code snippet in my .env file.
