### ISSUE TITLE
Missing arrow component in `app/page.tsx`

### ISSUE THREAD

**Issue by w14d3k** [vercel/next-learn#363]
Import and declaration of arrow component for the "Log in" button are missing inside `app/page.tsx` in starter package.
![image](https://github.com/vercel/next-learn/assets/18100538/eee69fa1-327b-4276-ae8e-909c12dacb80)
![image](https://github.com/vercel/next-learn/assets/18100538/969ca1b2-dd11-44ab-abb7-d9946e157687)
`import { ArrowRightIcon } from '@heroicons/react/24/outline';`
`<ArrowRightIcon className="w-5 md:w-6" />`

**Comment by delbaoliveira** [comment]
Good catch @w14d3k, added it here: https://github.com/vercel/next-learn/pull/397
