### ISSUE TITLE
Chapter 6 - doc addition after creating the database

### ISSUE THREAD

**Issue by mandeep-s1ngh** [vercel/next-learn#364]
Hi there, I had an issue with seeding the database after copying the contents from the .env.local tab

I got a couple of `Error: Database connection string format for neon()`  errors.

There was a fix mentioned in #362 for showing secret before copying the snippet so all the information could be copy and pasted correctly. 

This resolved my issue so I think it might be worth adding that extra bit of information to the steps.

**Comment by darlysson** [comment]
Thank you for posting that. It helped me as well. :)

**Comment by delbaoliveira** [comment]
Thank you @mandeep-s1ngh, this looks like a bug. Will let the storage team know and update the chapter to be more clear. Good suggestion 👍🏼
