### ISSUE TITLE
Chapter 7 file path mistake

### ISSUE THREAD

**Issue by SaeWooKKang** [vercel/next-learn#366]
There seems to be a mistake in the path. [link](https://nextjs.org/learn/dashboard-app/fetching-data#fetching-data-for-revenuechart)

Line: 
```
/app/ui/dashboard/page.tsx
```

Should be: 
```
/app/dashboard/page.tsx
```

**Comment by StephDietz** [comment]
@SaeWooKKang thank you for finding this typo! We have a PR fixing it
