### ISSUE TITLE
Chapter 12 zod schema mistake

### ISSUE THREAD

**Issue by HaoquanLuo** [vercel/next-learn#367]
There seems to be a mistake with the zod schema 'UpdateInvoice'. [link](https://nextjs.org/learn/dashboard-app/mutating-data#4-pass-the-id-to-the-server-action)

Schema:
`const UpdateInvoice = InvoiceSchema.omit({ date: true });`

Shoud be:
`const UpdateInvoice = InvoiceSchema.omit({ **id: true,** date: true });`

or you will get an error like this:
` ⨯ ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "id"
    ],
    "message": "Required"
  }
]
    at updateInvoice (./app/lib/actions.ts:56:58)`

**Comment by ffxixslh** [comment]
There seems to be one more literal mistake in [followring section](https://nextjs.org/learn/dashboard-app/mutating-data#deleting-an-invoice).

Schema:
const UpdateInvoice = InvoiceSchema.omit({ date: true, id: true });

Shoud be:
const **Delete**Invoice = InvoiceSchema.omit({ date: true, id: true });

**Comment by devdanuk** [comment]
Good shout! Thanks

**Comment by imhalid** [comment]
thanks this is help me.

**Comment by mgayaud** [comment]
thanks 🙏

**Comment by popring** [comment]
thanks👍

**Comment by StephDietz** [comment]
@HaoquanLuo thank you for this feedback! We have a PR with this fix

**Comment by LittleGiant237** [comment]
![Screenshot 2024-04-14 174522](https://github.com/vercel/next-learn/assets/111706271/135badee-0c03-41b2-829b-416b3aa14d21)

I don't know how to fix it.

⨯ ZodError: [   {     "code": "invalid_type",     "expected": "string",     "received": "undefined",     "path": [       "date"     ],     "message": "Required"   } ]

**Comment by LittleGiant237** [comment]
![Screenshot 2024-04-14 174804](https://github.com/vercel/next-learn/assets/111706271/32f8ad60-8861-4aa5-8bc2-b283ba9be690)

My error
