### ISSUE TITLE
Chapter 12 - Linting Error

### ISSUE THREAD

**Issue by mukham12** [vercel/next-learn#370]
In the section about [retrieving a specific invoice](https://nextjs.org/learn/dashboard-app/mutating-data#3-fetch-the-specific-invoice), we are presented with a code snippet designed to fetch an invoice by its ID. However, the build linter is currently flagging an issue regarding the `invoice` prop within the `EditInvoiceForm` component, which is specified to accept instances of the `InvoiceForm` type. However, `invoice` prop can potentially be of the `undefined` if a function encounters an error.
https://github.com/vercel/next-learn/blob/a9077215a0f83ff865f7e780c84463625c45e06a/dashboard/final-example/app/lib/data.ts#L152-L176

To address this situation, we have two potential solutions: either adjust the code to handle `undefined` values gracefully, or provide a placeholder type within the function's return. I am prepared to submit a PR if someone could clarify the desired behavior that should be exhibited in this scenario.

![image](https://github.com/vercel/next-learn/assets/55890311/b383952e-e8dc-4813-8429-4da7779a5880)

**Comment by mrmahatva** [comment]
This is Not Error
 
After you Add
if (!invoice) { notFound() }

Error Resolve
But This is Shown in Error Handling Part Chapter 13

**Comment by mukham12** [comment]
Ah, I see. Thank you @mrmahatva.

I must have somehow missed that part while jumping back and forth between chapters.

**Comment by delbaoliveira** [comment]
Thank you @mrmahatva, I'll add it to the chapter so it's clearer 🙏🏼

**Comment by Samad-Developer** [comment]
@delbaoliveira i have an issue when i add authentication to me website and deploy after auth_url updating it still redirect me to local host

**Comment by LainLic** [comment]
> Ah, I see. Thank you @mrmahatva.
> 
> I must have somehow missed that part while jumping back and forth between chapters.

The problem lies within the tutorial imo :
![Bildschirmfoto 2024-04-26 um 15 55 28](https://github.com/vercel/next-learn/assets/112620671/164c8700-8543-452a-a969-18348e854371)
The green box is giving the important information while the next sentence and the image are highly confusing, at least for newbies like me. If the solution is provided in the next chapter this call to action and the image should be in chapter 13 as well
