### ISSUE TITLE
Failed to fetch table from database

### ISSUE THREAD

**Issue by OsamaSokrab** [vercel/next-learn#371]
**Following the tutorial instructions, I created a tasks table with the following seed**
`async function seedTasks(client) {
  try {
    await client.sql`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`;
    // Create the "tasks" table if it doesn't exist
    const createTable = await client.sql`
      CREATE TABLE IF NOT EXISTS tasks (
        id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        status VARCHAR(255) NOT NULL,
        date DATE NOT NULL
      );
    `;
    console.log(`Created "tasks" table`);
    // Insert data into the "tasks" table
    const insertedTasks = await Promise.all(
      tasks.map(
        (task) => client.sql`
        INSERT INTO tasks (id, name, status, date)
        VALUES (${task.id}, ${task.name}, ${task.status}, ${task.date})
        ON CONFLICT (id) DO NOTHING;
      `,
      ),
    );
    console.log(`Seeded ${insertedTasks.length} tasks`);
    return {
      createTable,
      tasks: insertedTasks,
    };
  } catch (error) {
    console.error('Error seeding tasks:', error);
    throw error;
  }
}
`
**I put the following data in the data placeholder**
`const tasks = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    name: 'task1',
    status: 'done',
    date: '2023-11-04',
  },
];`

**The table was created successfully and I could examine it in the vercel postgres data
but when I try to fetch data with the following function**
`export async function fetchTasks() {
  try {
    const tasks = await sql`
    SELECT
		  tasks.id,
		  tasks.name,
		  tasks.status,
		  tasks.date,
		FROM tasks`;
    return tasks.rows;
  } catch (error) {
    console.error('Failed to fetch tasks:', error);
    throw new Error('Failed to fetch tasks.');
  }
}`

**It failed to fetch data and give me the following message:**
`ailed to fetch tasks: NeonDbError: db error: ERROR: syntax error at or near "FROM"

Caused by:
    ERROR: syntax error at or near "FROM"
    at execute (webpack-internal:///(rsc)/./node_modules/@neondatabase/serverless/index.js:4713:70)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchTasks (webpack-internal:///(rsc)/./app/lib/data.ts:231:23)
    at async Page (webpack-internal:///(rsc)/./app/dashboard/tasks/page.tsx:18:19) {
  code: '42601',
  sourceError: undefined
}
 ⨯ app/lib/data.ts (264:10) @ fetchTasks
 ⨯ Error: Failed to fetch tasks.
    at fetchTasks (./app/lib/data.ts:241:15)
    at async Page (./app/dashboard/tasks/page.tsx:18:19)
  262 |   } catch (error) {
  263 |     console.error('Failed to fetch tasks:', error);
> 264 |     throw new Error('Failed to fetch tasks.');
      |          ^
  265 |   }
  266 | }
  267 |`
In the

**Comment by ffxixslh** [comment]
Maybe the extra comma before FROM cause the error 🤔

**Comment by OsamaSokrab** [comment]
The problem is solved .... Thank you
