### ISSUE TITLE
Chapter 10 - missing/wrong highlight in code block

### ISSUE THREAD

**Issue by imhalid** [vercel/next-learn#379]
<img width="974" alt="Screen Shot 2023-11-05 at 08 18 36" src="https://github.com/vercel/next-learn/assets/40598819/edce3db6-418e-4d23-bcbe-98eadbf84ac4">

The handleSearch function changes slightly, but only line 7 is highlighted. Looks like this could be fixed a bit.

**Comment by mrmahatva** [comment]
![image](https://github.com/vercel/next-learn/assets/149217201/6aee9367-4513-4c1d-a4fd-ba53cb40a645)

Line 10, 11, 12  => Line 12, 13, 14

**Comment by StephDietz** [comment]
@imhalid @mrmahatva thank you for your feedback! We have a PR fixing these code block highlights
