### ISSUE TITLE
Production URL redirects to http://localhost:3000/dashboard when log in

### ISSUE THREAD

**Issue by fpuglap** [vercel/next-learn#381]
Hi, the production URL https://nextjs-dashboard-fpuglap.vercel.app/ redirects to http://localhost:3000/dashboard when try to log in.

I was seeing issues similar to this but I didn't find the solution. Maybe it's a cache problem? I've cleaned up some URLs but I'm not sure if that should fix the problem.

I am wondering if I should add the AUTH_URL environment variable (something like https://nextjs-dashboard-fpuglap.vercel.app/api/auth) inside my Vercel cloud project. I read that it is not necessary if the deployment is done with Vercel, but I don't know.

Any clue how I can solve this problem?

Here is my repo: https://github.com/fpuglap/nextjs-dashboard

**Comment by OsamaSokrab** [comment]
I also have the same problem

**Comment by Tyler98ky** [comment]
Your intuition was correct! You need to update the environment variable for wherever the project is deployed (in your case, Vercel) to match the domain it's being accessed from.

So in your case and all others deploying on Vercel:
1. Navigate to your project in Vercel
2. Select the `Settings` tab
3. Choose `Environment Variables` from the provided options
4.  Edit the `AUTH_URL` variable and replace `http://localhost:3000/api/auth` with `https://{YOUR_DOMAIN_HERE}/api/auth`

So again, using your example and the URL you've provided, your `AUTH_URL` variable should be set to `https://nextjs-dashboard-fpuglap.vercel.app/api/auth`

P.S. You will want to leave your local .env file alone and keep the `localhost:3000/api/auth` value so that auth will work locally. Changing the Vercel environment variable will only affect the vercel deployed service.

**Comment by StephDietz** [comment]
@fpuglap thank you for the feedback! `AUTH_URL` is no longer necessary either locally or on Vercel. You may need to bump to latest, but you can remove that environment variable!

**Comment by fpuglap** [comment]
@StephDietz Thank you for following up. I realized that I no longer need to add that variable in Vercel cloud server a couple of days ago. 

So I don't need anymore `AUTH_URL=http://localhost:3000/api/auth` in my .nev file? That's cool.

I'm using `"next": "^14.0.0"` version. I'm not sure if it would work on that one, but I'll give it a shoot :)

**Comment by maik-emanoel** [comment]
@StephDietz did you get solve this problem? I'm having this same issue. Actually, in production, instead of going to '/dashboard' is going to '/undefined'. I don't know how to make it work.

**Comment by ZGarry** [comment]
> @fpuglap thank you for the feedback! `AUTH_URL` is no longer necessary either locally or on Vercel. You may need to bump to latest, but you can remove that environment variable!

It works in the lastest tutorial

**Comment by markosmk** [comment]
> @StephDietz did you get solve this problem? I'm having this same issue. Actually, in production, instead of going to '/dashboard' is going to '/undefined'. I don't know how to make it work.

Hi Maik @maik-emanoel , I'm having this same issue, how could you solve it? every time I try the POST of the login, I get 405 error, i added the AUTH_SECRET, and the postgress variables were added automatically

**Comment by xli340** [comment]
> @StephDietz did you get solve this problem? I'm having this same issue. Actually, in production, instead of going to '/dashboard' is going to '/undefined'. I don't know how to make it work.

I also met this issue, did you solve it?

**Comment by maik-emanoel** [comment]
> > @StephDietz did you get solve this problem? I'm having this same issue. Actually, in production, instead of going to '/dashboard' is going to '/undefined'. I don't know how to make it work.
> 
> Hi Maik @maik-emanoel , I'm having this same issue, how could you solve it? every time I try the POST of the login, I get 405 error, i added the AUTH_SECRET, and the postgress variables were added automatically

I solved this error a lot of months ago, now I neither remember what problem were or how I solved it. I'm sorry guys

**Comment by hikevindiaz** [comment]
Hi there, my problem is the other way around. When I login on local it goes to my vercer app. Any suggestions?
I already tried changing the environment variables but it's not working.

**Comment by Ludovic-Blondon** [comment]
had the same issue, and I solved it by removing the `AUTH_URL` variable. You can find it in the **Environment Variables** section of your Vercel app, located under the **Config** tab.
