### ISSUE TITLE
Chapter 15: Protecting your routes with Next.js Middleware

### ISSUE THREAD

**Issue by alexandreferreirafr** [vercel/next-learn#386]
This part explain about the callbacks on `authConfig`, bug forgets to mention about the `providers`.

It should be nice to add a mention saying that the attribute `providers` with an empty Array should be added to `authConfig` in order to satisfies NextAuthConfig.

If this attribute is missing, the call to NextAuth on the middleware will not work.

**Comment by delbaoliveira** [comment]
Thank you @alexandreferreirafr, I'll update the chapter to explain why we need the empty array 🙏🏼
