### ISSUE TITLE
Chapter 14 and 15 - name convention returned values from useFormState

### ISSUE THREAD

**Issue by alexandreferreirafr** [vercel/next-learn#387]
`useFormState` return an Array with 2 values, it's true that we can give any name to them.

But in chapter 14 we are using `[state, dispatch]` and in the chapter 15 `[code, action]`. I think it can be confusing to see different name conventions on the same tutorial (project).

Can't we adopt the same convention everywhere on the project?

thanks

**Comment by delbaoliveira** [comment]
Thank you for raising this @alexandreferreirafr. I think we should stick to the naming in the [React docs](https://react.dev/reference/react-dom/hooks/useFormState#noun-labs-1201738-(2)) - state and dispatch. Updated, should be landing soon.
