### ISSUE TITLE
Chapter 15 - Adding the sign in functionality

### ISSUE THREAD

**Issue by alexandreferreirafr** [vercel/next-learn#390]
On the section "[Adding the sign in functionality](https://nextjs.org/learn/dashboard-app/adding-authentication#adding-the-sign-in-functionality)"

on the code block `auth.ts`, there's a sql query where the capitalization is not correct.

current:
```ts
const user = await sql<User>`SELECT * from USERS where email=${email}`;
```
expected:
```ts
const user = await sql<User>`SELECT * FROM users WHERE email=${email}`;
```

**Comment by delbaoliveira** [comment]
Thank you @alexandreferreirafr, and for the PR @tylerhoward15 🎉
