### ISSUE TITLE
Chapter 14 - npm run lint fails

### ISSUE THREAD

**Issue by hyojoongit** [vercel/next-learn#392]
command `npm run lint`
gives an error
```
> lint
> next lint

Failed to load config "next/core-web-vitals" to extend from.
Referenced from: /myroute/nextjs-dashboard/.eslintrc.json
```

**Comment by delbaoliveira** [comment]
Hey @hyojoongit 👋🏼 

What does your `.eslintrc.json` file look like? 

Can I double check you have this: 

```
{
  "extends": "next/core-web-vitals"
}
```

**Comment by hyojoongit** [comment]
The file was not in the root directory(was one step outside).. moved the file, and now it works.
But it is not showing any warnings as in the tutorial.

**Comment by delbaoliveira** [comment]
Glad to hear it! 😌
