### ISSUE TITLE
npm run seed issue. Error seeding users: error" no such user

### ISSUE THREAD

**Issue by ADITHYAADHI06** [vercel/next-learn#394]
length: 33,
  severity: 'ERROR',
  code: 'XX000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: undefined,
  line: undefined,
  routine: undefined

**Comment by SveinJH** [comment]
+1. Running Node.js v20.9.0

**Comment by tanujatiwari** [comment]
While copying envs from Vercel, make sure you first click on "Show secret" and then copy the values. For some reason, the values for POSTGRES_USER and POSTGRES_PASSWORD are not populated immediately; thus the error.

**Comment by eihabkhan** [comment]
I had the same issue, but I fixed it by copying the contents from the `.env.local` tab on the database page a second time. For some reason the first time I copied it both `POSTGRES_USER` and `POSTGRES_PASSWORD` were set to an empty string

**Comment by ADITHYAADHI06** [comment]
> While copying envs from Vercel, make sure you first click on "Show secret" and then copy the values. For some reason, the values for POSTGRES_USER and POSTGRES_PASSWORD are not populated immediately; thus the error.

solved, thanks for all your support.
