### ISSUE TITLE
Chapter 7 - Wrong line is highlighted

### ISSUE THREAD

**Issue by morinokami** [vercel/next-learn#395]
Line 11 of the code for https://nextjs.org/learn/dashboard-app/fetching-data#fetching-data-for-latestinvoices is highlighted, but line 9 should be highlighted here.

<img width="977" alt="Screenshot 2023-11-06 at 21 36 47" src="https://github.com/vercel/next-learn/assets/7889778/7786a0a7-b85b-47c1-a57b-c08a756a4211">

**Comment by morinokami** [comment]
I found a similar highlighting mistake in Chapter 11 at https://nextjs.org/learn/dashboard-app/adding-search-and-pagination#best-practice-debouncing. In the following code, line 7 should not be highlighted, instead lines 5 and 15 should be.

<img width="964" alt="Screenshot 2023-11-08 at 0 29 18" src="https://github.com/vercel/next-learn/assets/7889778/93229736-a174-42b9-bb2e-0eed9fc7c708">

**Comment by StephDietz** [comment]
@morinokami thank you for finding these! We have a PR fixing the highlight issues
