### ISSUE TITLE
Chapter 9 first quiz typo

### ISSUE THREAD

**Issue by jmadilia** [vercel/next-learn#399]
In Chapter 9, when answering the first quiz correctly, you are given the explanation on the answer. In the explanation, the word "significantly" has a typo:

![image](https://github.com/vercel/next-learn/assets/46933893/c26fab3d-505c-4edf-9d70-d988f6ab017e)

**Comment by StephDietz** [comment]
@jmadilia thank you for reporting this! We have a PR fixing the typo
