### ISSUE TITLE
Image Loading Issue in Production Following Authentication Implementation in Next.js Tutorial Chapter 15

### ISSUE THREAD

**Issue by emapeire** [vercel/next-learn#400]
After completing chapter 15 of the Next.js tutorial on authentication, images served from the public directory no longer load in the production environment, resulting in a HTTP 302 status and redirection to the login page. This issue does not occur in the local development environment (localhost), where images load as expected. There appears to be a conflict with the NextAuth middleware that interferes with the routing of static image paths. Any guidance to resolve this would be greatly appreciated.

- Some screenshots:

<img width="1089" alt="Captura de pantalla 2023-11-07 a la(s) 00 38 08" src="https://github.com/vercel/next-learn/assets/63935846/9eafac10-798b-4b6c-b358-febe452da2dc">

<img width="1045" alt="Captura de pantalla 2023-11-07 a la(s) 00 39 09" src="https://github.com/vercel/next-learn/assets/63935846/685aee01-4848-4fc2-ab56-ef0ad0259ab4">

<img width="1047" alt="Captura de pantalla 2023-11-07 a la(s) 00 39 39" src="https://github.com/vercel/next-learn/assets/63935846/5f4860fa-ed55-466b-b64b-579ed26b5f18">

**Comment by delbaoliveira** [comment]
Hey @emapeire, this has to do with the matcher in Middleware. 

It's been recently updated to: 

```
export const config = {
  matcher: ['/((?!api|_next/static|_next/image|.*\\.png$).*)'],
};
```

Please let us know if you run into any more issues! 🙏🏼

**Comment by emapeire** [comment]
> Hey @emapeire, this has to do with the matcher in Middleware.
> 
> It's been recently updated to:
> 
> ```
> export const config = {
>   matcher: ['/((?!api|_next/static|_next/image|.*\\.png$).*)'],
> };
> ```
> 
> Please let us know if you run into any more issues! 🙏🏼

Thanks a lot @delbaoliveira, it's works!
