### ISSUE TITLE
Get 3 errors when refresh or direct access on route http://localhost:3000/dashboard/invoices

### ISSUE THREAD

**Issue by yanguanyu** [vercel/next-learn#404]
<img width="960" alt="image" src="https://github.com/vercel/next-learn/assets/6942570/28f064b6-202d-4718-9d9c-6b6d96c028ba">

<img width="961" alt="image" src="https://github.com/vercel/next-learn/assets/6942570/c57f69a0-baad-496a-83e2-569903bc77fe">

<img width="956" alt="image" src="https://github.com/vercel/next-learn/assets/6942570/56a32388-b92c-4d9b-b58c-ffc98c18f4b4">

**Comment by hinn254** [comment]
- I ran into this and stopped the server then started it again using the `npm run dev` command

**Comment by rncrmn** [comment]
On search.tsx file replace the div with form, that will fix the issues.

![image](https://github.com/vercel/next-learn/assets/55722725/6cf6192f-80d4-4907-91a4-46c2ab36e601)

**Comment by rncrmn** [comment]
In search.tsx file, replace the div tag with form tag, that will fix the issues.
![image](https://github.com/vercel/next-learn/assets/55722725/6a92acc1-3bc0-4da0-a077-e7799743f90e)

**Comment by yanguanyu** [comment]
> In search.tsx file, replace the div tag with form tag, that will fix the issues. ![image](https://user-images.githubusercontent.com/55722725/281449765-6a92acc1-3bc0-4da0-a077-e7799743f90e.png)

It works for me, thank you.  But why the div tag can't be used here?

**Comment by yanguanyu** [comment]
> * I ran into this and stopped the server then started it again using the `npm run dev` command

I have tred it but not works.

**Comment by rncrmn** [comment]
> > In search.tsx file, replace the div tag with form tag, that will fix the issues. ![image](https://user-images.githubusercontent.com/55722725/281449765-6a92acc1-3bc0-4da0-a077-e7799743f90e.png)
> 
> It works for me, thank you. But why the div tag can't be used here?

Actually, there's nothing wrong with the div tag; the errors are caused by one of your browser extensions. In my case, it is the LastPass manager.

Try visiting "http://localhost:3000/dashboard/invoices" in incognito mode. You will see that you don't get that error anymore, even though you are using a div tag.

I just use the form tag to get around the error caused by LastPass.

**Comment by rncrmn** [comment]
> > > In search.tsx file, replace the div tag with form tag, that will fix the issues. ![image](https://user-images.githubusercontent.com/55722725/281449765-6a92acc1-3bc0-4da0-a077-e7799743f90e.png)
> > 
> > 
> > It works for me, thank you. But why the div tag can't be used here?
> 
> Actually, there's nothing wrong with the div tag; the errors are caused by one of your browser extensions. In my case, it is the LastPass manager.
> 
> Try visiting "http://localhost:3000/dashboard/invoices" in incognito mode. You will see that you don't get that error anymore, even though you are using a div tag.
> 
> I just use the form tag to get around the error caused by LastPass.

If it is caused by LastPass in your case and you don't want to change the tag or do it in incognito mode, what you can do is disable LastPass on localhost (see the screenshot below).

![Screenshot 2023-11-09 212430](https://github.com/vercel/next-learn/assets/55722725/b4016762-57be-49be-8d59-3dd263804f8e)

**Comment by rncrmn** [comment]
> That's really annoying! But, the LastPass thing was definitely my issue. Thank you

I'm glad to help.

**Comment by yanguanyu** [comment]
> > > In search.tsx file, replace the div tag with form tag, that will fix the issues. ![image](https://user-images.githubusercontent.com/55722725/281449765-6a92acc1-3bc0-4da0-a077-e7799743f90e.png)
> > 
> > 
> > It works for me, thank you. But why the div tag can't be used here?
> 
> Actually, there's nothing wrong with the div tag; the errors are caused by one of your browser extensions. In my case, it is the LastPass manager.
> 
> Try visiting "http://localhost:3000/dashboard/invoices" in incognito mode. You will see that you don't get that error anymore, even though you are using a div tag.
> 
> I just use the form tag to get around the error caused by LastPass.

Thank you for your explanation. I did use LastPass.
