### ISSUE TITLE
Chapter 12 - Edit Invoice, changing invoice status

### ISSUE THREAD

**Issue by impuls666** [vercel/next-learn#405]
When I change only the invoice status and nothing else in the "Edit Invoice" section it doesn't update on the main table. Possible solution adding noStore() to the async function updateInvoice() in actions.ts ?

**Comment by delbaoliveira** [comment]
Hey @impuls666, I'm sorry I haven't been able to reproduce this. Do you have a reproduction? 

One thing to make sure you are doing is invoking `revalidatePath` in your action.

**Comment by nitronaj** [comment]
I can reproduce it, mainly when the status is `pending` and wanna change it to `paid`
https://dashhboard-app.vercel.app/dashboard/invoices

added the `revalidatePath` in action and `noStore` in data file

I am working on chapter 15

**Comment by cjboco** [comment]
I experienced this as well, but it wasn't just status. It was caching everything. Adding noStore() fixed the issue.

**Comment by nitronaj** [comment]
Thank for checking it,
I fixed the issue, it was related to next-auth. I should add the secret environment variable.
`NEXTAUTH_SECRET`

https://next-auth.js.org/configuration/nextjs#secret

I added `noStore` to `fetchFilteredInvoices`, but still face the issue

**Comment by impuls666** [comment]
sorry for late reply, it's in the chapter 12 :
looks like the function:  "export async function updateInvoice..."  in  file "/app/lib/actions.ts" has no "noStore();" therefore it keeps cached data, but it is fixed in chapter 14 since the file is changed almost completly :)

**Comment by nitronaj** [comment]
`noStore` in the data file when fetching the data. not in action. 

https://nextjs.org/docs/app/api-reference/functions/unstable_noStore
so we have a post API for action call,  something like

`https://dashhboard-app.vercel.app/dashboard/invoices/5d12aebf-cc98-458b-9dbb-89d2301ff61b/edit`

 and in the request header `Cache-Control` is set to `no-cache`

**Comment by leerob** [comment]
Closing this one as stale, but please open a new issue if you are still having trouble here. Thank you!
