### ISSUE TITLE
Missing opengraph-image.jpg

### ISSUE THREAD

**Issue by joshuacox** [vercel/next-learn#411]
I cannot seem to locate this opengraph image, after cloning the [next-learn](https://github.com/vercel/next-learn.git
) repo, searching for this file returns nothing:

```
find . -iname 'opengraph-image.jpg'
```

**Comment by Tyler98ky** [comment]
For reference, this discrepancy is mentioned in the **_'Adding metadata'_** section of **Chapter 16**. Specifically under **_'Favicon and Open Graph image'_**. 

The statement: _"In your `/public` folder, you'll notice you have two images: `favicon.ico` and `opengraph-image.jpg`."_

In the public folder, there is a `large-image.jpg` which is likely what was intended to be referenced here. To utilize the next.js Metadata API, `large-image.jpg` should presumably be renamed to `opengraph-image.jpg` as well as the related references.

**Comment by Tyler98ky** [comment]
The documentation states that the file is `opengraph-image.jpg`, however the actual file in the repo is `opengraph-image.png`. So just replace jpg with png and it should work.

For reference, this is mentioned in **Chapter 16**,  specifically at the section **_'Favicon and Open Graph image'_**.
**Statement**: 'In your `/public` folder, you'll notice you have two images: `favicon.ico` and **`opengraph-image.jpg`**.'

**Comment by joshuacox** [comment]
I really don't see it there:
```
find . -iname 'opengraph-image*'
#^ returns nothing
tree public     
[4.0K]  public
├── [4.0K]  customers
│   ├── [7.8K]  amy-burns.png
│   ├── [7.8K]  balazs-orban.png
│   ├── [5.7K]  delba-de-oliveira.png
│   ├── [4.0K]  emil-kowalski.png
│   ├── [1019]  evil-rabbit.png
│   ├── [6.1K]  guillermo-rauch.png
│   ├── [5.5K]  hector-simpson.png
│   ├── [6.3K]  jared-palmer.png
│   ├── [5.5K]  lee-robinson.png
│   ├── [9.7K]  michael-novotny.png
│   ├── [7.0K]  steph-dietz.png
│   └── [7.2K]  steven-tey.png
├── [487K]  hero-desktop.png
└── [114K]  hero-mobile.png

2 directories, 14 files
```

It must've been added in after I cloned the repo, because I do see it now:

```
git clone --depth=1 https://github.com/vercel/next-learn.git
Cloning into 'next-learn'...
remote: Enumerating objects: 244, done.
remote: Counting objects: 100% (244/244), done.
remote: Compressing objects: 100% (183/183), done.
remote: Total 244 (delta 59), reused 165 (delta 34), pack-reused 0
Receiving objects: 100% (244/244), 1.14 MiB | 6.02 MiB/s, done.
Resolving deltas: 100% (59/59), done.
cd next-learn 
find . -iname 'opengraph-image*'
./dashboard/final-example/app/opengraph-image.png
./dashboard/starter-example/public/opengraph-image.png
```
