### ISSUE TITLE
Chapter 3 - Naming of image in course

### ISSUE THREAD

**Issue by maxdemaio** [vercel/next-learn#414]
Hey all,

At this location of the docs, https://nextjs.org/learn/dashboard-app/optimizing-fonts-images#practice-adding-the-mobile-hero-image, the image name should be `hero-mobile.png` instead of `mobile-hero.png` 👍🏻

> Now it's your turn! Under the image you've just added, add another `<Image>` component for `mobile-hero.png`.

This is because the asset is called `hero-mobile.png` in the template repository, as noted here - https://github.com/vercel/next-learn/blob/afe1f5d71af7b3b653641af9c335836aee0d16a3/dashboard/final-example/app/page.tsx#L41

Hope this helps and thanks for the course!

**Comment by delbaoliveira** [comment]
Good catch @maxdemaio, updated! Should be landing soon 🙏🏼
