### ISSUE TITLE
npm run seed fails

### ISSUE THREAD

**Issue by ValentinHoerzi** [vercel/next-learn#416]
When I run `npm run seed` from Chapter 6 i get this error:
<img width="326" alt="image" src="https://github.com/vercel/next-learn/assets/38781974/8340e10b-ee95-451c-83ea-b526a54a1933">

Can someone help me please?

**Comment by ronalrojasr** [comment]
I updated my .env, but it still show the same error, what do you mean with refresh on vercel site ??

**Comment by wei-learning** [comment]
I got the same error and I finally make it solved. Please make sure:
1.  click Show secret and then Copy Snippet (on vercel site)
2. .env file is under the root directory of your project

**Comment by StephDietz** [comment]
I updated the course to include verifying all environment variables are correct this in the troubleshooting section.

**Comment by ValentinHoerzi** [comment]
Thanks for the responses! I filled out the .env, so that was not the problem.
Turns out a software on my machine (ZScaler) caused it.
