### ISSUE TITLE
Customer images show in development but not in production on Vercel. 

### ISSUE THREAD

**Issue by LutherTS** [vercel/next-learn#424]
On the Dashboard page and other dashboard pages that rely on that data, images for customers like Delba, Steven and Lee show up but in development, but not only do they not show in production, but opening them in an other tab automatically redirects to the dashboard. What could be going on? 
Here's my demo: 
[https://nextjs-dashboard-luthertss-projects.vercel.app/dashboard](https://nextjs-dashboard-luthertss-projects.vercel.app/dashboard)

**Comment by Tyler98ky** [comment]
See "Image Loading Issue in Production Following Authentication Implementation in Next.js Tutorial Chapter 15" #400

**Comment by LutherTS** [comment]
Greatly appreciated.
