### ISSUE TITLE
NextJS 14.0.2 font bug

### ISSUE THREAD

**Issue by LutherTS** [vercel/next-learn#426]
Just a heads-up that updating to the latest 14.0.2 release messed up the import on the font Lusitana, at least on my end. I therefore had to revert to 14.0.1 to see the font again in my project. 

P.S.: Actually I still have the issue in 14.0.1 so I have no idea what's going on.

**Comment by LutherTS** [comment]
It finally worked by changing the localhost port. I think the issue was triggered by an other app that messed up with my localhost, so for now I'll just keep changing it with "dev": "next dev -p 3001" in scripts in package.json.

**Comment by StephDietz** [comment]
Glad you were able to fix it! Closing as this is not an issue related to the course

**Comment by LiamWinterton** [comment]
I also cannot get this font to load. Others work fine, but `import { Lusitana } from 'next/font/google';` specifically is an issue.
