### ISSUE TITLE
[Chapter 9] Dashboard <Suspense>s incorrect behavior with slow data

### ISSUE THREAD

**Issue by birkasecorba** [vercel/next-learn#429]
Just like in Chapter 9 I've wrapped my components that fetch data in <Suspense>. I've left the code that artificially slows the data fetch in `fetchRevenue` but removed it from `fetchLatestInvoices` and `fetchCardData`. When I run this version locally everything works as expected: 'Cards' and `Latest Invoices` load almost instantly and the skeleton for the `Recent Revenue` is visible for ~4s and then we get the UI with data.

But when this code is deployed, the behavior is different. When I login and navigate to dashboard, every time I refresh (cmd+r) one of the suspense in addition to the suspense around the component that calls `fetchRevenue` shows the skeleton ui until `fetchRevenue` returns the data. (ex video below)

The deployed code is here:
https://github.com/birkasecorba/nextjs-learn/tree/demo-bug-data-loading

Demo of the deployment here:
https://nextjs-learn-git-demo-bug-data-loading-birkasecorba.vercel.app/dashboard

Credentials:
- user@nextmail.com
- 123456

### Local
https://github.com/vercel/next-learn/assets/3323411/0ad0c624-e348-4644-99ba-e4160cdffd94

### Deployed

https://github.com/vercel/next-learn/assets/3323411/fee5a782-3a52-4652-bbc2-04120ad52b51

**Comment by birkasecorba** [comment]
Hey @delbaoliveira, 👋 

The deploy is updated, the issue seems to be resolved with the upgrade to the latest Next.js. I am not 100% what changed between the versions but thanks for looking into it!

**Comment by delbaoliveira** [comment]
Awesome, glad it's resolved 🙏🏼
