### ISSUE TITLE
Chapter 13 - Wrong Code Block Header

### ISSUE THREAD

**Issue by mukham12** [vercel/next-learn#430]
In [this portion](https://nextjs.org/learn/dashboard-app/error-handling#handling-404-errors-with-the-notfound-function), please ensure that the code block header and the reference mentioned in the paragraph, specifically `/app/lib/data.tsx`, are updated to include the correct file extension (.ts).

![image](https://github.com/vercel/next-learn/assets/55890311/b8b28faf-c0b5-487c-b4b7-d4009c244f53)

**Comment by StephDietz** [comment]
@mukham12  thank you for this feedback! We have a PR fixing the typo
