### ISSUE TITLE
[chapter 12] code snipet for deleting the invoice is inccorect

### ISSUE THREAD

**Issue by nitronaj** [vercel/next-learn#435]
in chapter 12 
https://nextjs.org/learn/dashboard-app/mutating-data#deleting-an-invoice
the action code need to be updated

instead of 
```typescript
const UpdateInvoice = FormSchema.omit({ date: true, id: true });
// ...
 
export async function deleteInvoice(id: string) {
  await sql`DELETE FROM invoices WHERE id = ${id}`;
  revalidatePath('/dashboard/invoices');
}
```

should be 
```typescript
const UpdateInvoice = InvoiceSchema.omit({ date: true, id: true });
// ...
 
export async function deleteInvoice(id: string) {
  await sql`DELETE FROM invoices WHERE id = ${id}`;
  revalidatePath('/dashboard/invoices');
}
```

**Comment by nitronaj** [comment]
export async function deleteInvoice(id: string) {
  await sql`DELETE FROM invoices WHERE id = ${id}`;
  revalidatePath('/dashboard/invoices');
}
```

**Comment by delbaoliveira** [comment]
Hey @nitronaj, you are correct, it should `FormSchema`. Thank you, updated 🙏🏼

**Comment by Connor-Skudlarek** [comment]
> Hey @nitronaj, you are correct, it should `FormSchema`. Thank you, updated 🙏🏼

Shouldn't it be InvoiceSchema? There is no FormSchema defined at this point (if there should be).

**Comment by gornyyvladimir** [comment]
Add `CreateInvoice` should be updated too.
Instead of `const CreateInvoice = FormSchema.omit({ id: true, date: true });` should be `const CreateInvoice = InvoiceSchema.omit({ id: true, date: true });`

**Comment by gornyyvladimir** [comment]
> ```ts
> InvoiceSchema
> ```

It should be `InvoiceSchema` because we do not have defined `FormSchema`
