### ISSUE TITLE
Docs: Fix some words misspelling.

### ISSUE THREAD

**Issue by DemaPy** [vercel/next-learn#437]
### What is the improvement or update you wish to see?

Reading NexJs amazing documentation I have found some mistake in word.

Import useRouter and usePathname from 'next/navigation', and use the replace method from **userRouter()** inside handleSearch:

[Chapter 11](https://nextjs.org/learn/dashboard-app/adding-search-and-pagination)

### Is there any context that might help us understand?

It would be nice to update it, since NextJs doesn't have this type of hook.

Developers will try to use it, and will have a problem.

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/adding-search-and-pagination

**Comment by mukham12** [comment]
Thanks, Lee!

This is now fixed @DemaPy.
