### ISSUE TITLE
Chapter 12, Typo Found in Learning Course

### ISSUE THREAD

**Issue by krsntn** [vercel/next-learn#439]
In the code block found in Chapter 12.4, there seems to be a typo error regarding the variable name. I believe the intended variable name should be `FormSchema` instead of `InvoiceSchema`.
 
![image](https://github.com/vercel/next-learn/assets/41847358/ac7e97e9-0235-4ba4-bbe7-50f68fb90760)

**Comment by delbaoliveira** [comment]
Thank you @krsntn 🙏🏼 updated, should be landing soon.
