### ISSUE TITLE
Missing instructions in the Assets, Metadata, and CSS > Layout Component tutorial

### ISSUE THREAD

**Issue by KlausEverWalkingDev** [vercel/next-learn#44]
In this part of the tutorial it is said that we should see those two changes: the First Post page with some margin on it and the automatically generated unique class name.

![image](https://user-images.githubusercontent.com/3390598/130710857-02db9585-7fca-42c3-931c-b78f53021599.png)

But if you're running the dev npm script those changes will not be visible. Just when you build and run the npm start script you'll see them. Tested on Arch Linux with both the Vivaldi Browser 4.1.2369.16 Stable Build and Firefox 91.0.2 Stable.

**Comment by shiraze** [comment]
I think this is linked to the missing resources that are mentioned on this page: https://nextjs.org/learn/basics/assets-metadata-css/css-styling
I've noticed that the repos doesn't contain a `styles` folder.  There are other repos under vercel/next-learn that have `globals.css` but, I've no idea where `Home.module.css` is meant to come from.

**Comment by z-argyropoulos** [comment]
I was confused as well going through the get started guide today. Most likely the mentioned styles (home and global) are included directly in the pages/index.js file and not in a separate directory as the docs mention. I would suggest the following paragraph should be removed or updated to match the example files as it is confusing and misleading

> As you can see, our index page (http://localhost:3000/) already has some styles. If you look at your file structure, you'll see a folder called styles with two CSS files: a global stylesheet (globals.css), and a CSS module (Home.module.css).

I can work on the PR if needed :)

**Comment by shiraze** [comment]
Yes - styled jsx is used in the index.js file, but the tutorial then goes on to make use of module css. It's a confusing start.
Maybe the tutorial should point this out, and state the intention that the rest of the tutorial will move to module css?

**Comment by primal100** [comment]
Just going through the tutorial now and seems like things are in the wrong order.

The styles directory and styles/globals.css are created manually two pages later than when the documentation expects them to exist:

Create a top-level styles directory and a global.css file.

https://nextjs.org/learn/basics/assets-metadata-css/global-styles

This is two pages later than when the tutorial expects them to exist:

As you can see, our index page (http://localhost:3000/) already has some styles. If you look at your file structure, you'll see a folder called styles with two CSS files: a global stylesheet (globals.css), and a CSS module (Home.module.css).

**Comment by triangletrianglesquareplusx** [comment]
Hey, thanks to all of your comments I found out I wasn't blind and these files really do not exist: ))

**Comment by leerob** [comment]
https://github.com/vercel/next-learn/pull/103
