### ISSUE TITLE
Chapter 7 - revenue prop error

### ISSUE THREAD

**Issue by mandarliev** [vercel/next-learn#442]
Hi,

I did this part https://nextjs.org/learn/dashboard-app/fetching-data#fetching-data-for-revenuechart
and the component is displayed as expected. However, I get the following error in the code:

<img width="863" alt="image" src="https://github.com/vercel/next-learn/assets/26351803/f8229590-4d62-456b-9792-7ec354cb1a2b">

Do you know what might be the reason for this?

**Comment by delbaoliveira** [comment]
Hey there @mandarliev, sorry, I haven't been able to reproduce this TS error. 

This error can usually occur if you have the incorrect prop types or missing props. Some things you can do: 

- Verify you're fetching data correctly:  `const revenue = await fetchRevenue()`
- Double check `RevenueChart` accepts `({ revenue }: {revenue: Revenue[]})` prop and type. 
- Uncomment the code inside `RevenueChart`

Happy to look at a reproduction if none of the above works.

**Comment by mandarliev** [comment]
Hi,

yes, the issue was the second point you mentioned. Thank you for the help! :)

**Comment by mandarliev** [comment]
Fixed with adding the prop and type to RevenueChart
