### ISSUE TITLE
Incorrect Code Block Header and a Typo

### ISSUE THREAD

**Issue by mukham12** [vercel/next-learn#443]
1. Incorrect code block header in [What are request waterfalls](https://nextjs.org/learn/dashboard-app/fetching-data#what-are-request-waterfalls) section. The header is /app/pages/dashboard/page.tsx, whereas it should be /app/dashboard/page.tsx

2. First occurrence of the word `formData` has to be capitalized in [this section](https://nextjs.org/learn/dashboard-app/mutating-data#using-forms-with-server-actions) since it refers to the FormData object.

**Comment by mukham12** [comment]
This was initially mentioned in #336. Despite resolving most reported problems, these two remain unresolved, prompting me to create a new issue. Apologies if the fix is pending deployment; I might have prematurely opened a new issue.

**Comment by delbaoliveira** [comment]
Hey @mukham12, no worries! Thank you for raising this, should be landing soon 🙏🏼
