### ISSUE TITLE
Chapter 4: Diagram showing how adding a folder... not loading.

### ISSUE THREAD

**Issue by cjboco** [vercel/next-learn#445]
Chapter 4, the image showing nested route diagram is not loading. 

macOS 14.1.1
Safari: 17.1

Looking at web console, I'm seeing:

```
Failed to load resource: the server responded with a status of 500 ()
https://nextjs.org/_next/image?url=%2Flearn%2Flight%2Fdashboard-route.png&w=3840&q=75&dpl=dpl_ceL1mqKvQeKhsugjeNqjHB5t3qoA
```

**Comment by DemaPy** [comment]
![image](https://github.com/vercel/next-learn/assets/80632445/23c4a899-ae24-47b4-94fb-9cec7483bcb4)
Here is a problem

**Comment by tylerhoward15** [comment]
The diagram is loading properly for me! Maybe a transient error? Is the problem still occurring for you?


![Screenshot 2023-11-15 135606](https://github.com/vercel/next-learn/assets/22920537/246e8703-4be6-4b4a-8556-e024418c8273)

**Comment by cjboco** [comment]
Still down for me?

<img width="975" alt="Screenshot 2023-11-15 at 2 02 02 PM" src="https://github.com/vercel/next-learn/assets/351122/53b36079-2496-4130-ba4a-0e47b9595dc2">

**Comment by cjboco** [comment]
> The diagram is loading properly for me. Maybe a transient error? Is the problem still occurring for you?
> 
> ![Screenshot 2023-11-15 135606](https://user-images.githubusercontent.com/22920537/283258141-246e8703-4be6-4b4a-8556-e024418c8273.png)

Actually... that image is loading. It's the image after that.

**Comment by cjboco** [comment]
<img width="1008" alt="Screenshot 2023-11-15 at 2 03 48 PM" src="https://github.com/vercel/next-learn/assets/351122/d711889d-fbb0-4c4b-ae7a-115645cd6fa7">

**Comment by StephDietz** [comment]
hey @cjboco, thanks for the feedback! I have been unable to reproduce this, is it still happening for you?

**Comment by delbaoliveira** [comment]
Hey @cjboco, thank you for reporting this 🙏🏼 . It looks like we're missing the light mode image. Will add, should be available soon!
