### ISSUE TITLE
Chapter 11: Small typo in search data URL code example

### ISSUE THREAD

**Issue by cjboco** [vercel/next-learn#447]
There's a small typo in your code example here:

[https://nextjs.org/learn/dashboard-app/adding-search-and-pagination](https://nextjs.org/learn/dashboard-app/adding-search-and-pagination)

Section 2, in the breakdown bullet list. Item 3 has an incorrect code example.

`replace(${pathname}?${params.toString()}) updates the URL with the user's search data. For example, /dashboard/invoices?query=lee if the user searches for "Lee".`

Nothing in your code is converting things to lowercase. You example should be:

`replace(${pathname}?${params.toString()}) updates the URL with the user's search data. For example, /dashboard/invoices?query=Lee if the user searches for "Lee".`

i.e. lowercase `lee`, in the example should be `Lee`. 

(I know this is nitpicking, but just trying to help make things rock solid!)

macOS 14.1.1
Safari 17.1

**Comment by StephDietz** [comment]
@cjboco thanks for the feedback! We have a PR  fixing this typo :)
