### ISSUE TITLE
What's the login password

### ISSUE THREAD

**Issue by chenJJ-88** [vercel/next-learn#448]
What's the login password

![Uploading image.png…]()

**Comment by delbaoliveira** [comment]
Hey @chenJJ-88, the login password is `123456`, very safe 😁

**Comment by chenJJ-88** [comment]
> Hey @chenJJ-88, the login password is `123456`, very safe 😁

Can't login, account is any e-mail? The error message： Invalid credentials

**Comment by jameskajon** [comment]
The email is `user@nextmail.com`

https://nextjs.org/learn/dashboard-app/adding-authentication#try-it-out
