### ISSUE TITLE
Chapter 3: Code highlighting off by one or two lines

### ISSUE THREAD

**Issue by DerTimonius** [vercel/next-learn#449]
Thanks for the awesome learning resource!

I noticed that in chapter 3 the code highlighting is a bit off sometimes.

- in this example it's two lines too high:
![example of code highlighting being placed too high](https://github.com/vercel/next-learn/assets/103483059/e69c2f80-02c7-4e28-bf12-8eeea20fe9ab)
- in this hidden example, it's one line too high:
![different example of code highlighting being placed too high](https://github.com/vercel/next-learn/assets/103483059/80484bc4-1630-4271-8303-0e564315fa98)

**Comment by delbaoliveira** [comment]
Thank you for raising this @DerTimonius, it looks like the code blocks were updated but not the lines. Fixed, should be landing soon 😄
