### ISSUE TITLE
Chapter 12: Incorrect break down on form

### ISSUE THREAD

**Issue by cjboco** [vercel/next-learn#453]
In Chapter 12, Section 1 (Create a new route and form)

[https://nextjs.org/learn/dashboard-app/mutating-data](https://nextjs.org/learn/dashboard-app/mutating-data)

The bullet points describing the `<Form>` component, you have:

- Has two `<select>` (dropdown) elements: **customers** and **status**.
- Has one `<input>` element for the **amount** with `type="number"`.
- Has one button with `type="submit"`.

It looks like you have updated the code, because status is now a radio input group. (Or maybe you are changing it, to a select, not sure). Either way, it should be:

- Has one `<select>` (dropdown) element: **customers**.
- Has one `<input>` element for the **amount** with `type="number"`.
- Has two `<input>` elements for the **status** with `type="radio"`
- Has one button with `type="submit"`.

<img width="807" alt="Screenshot 2023-11-16 at 10 01 57 AM" src="https://github.com/vercel/next-learn/assets/351122/c9d92128-2972-4db3-8243-1c1b7395ef70">

**Comment by delbaoliveira** [comment]
Thank you @cjboco 🙌🏼  

Updated, should be available soon.
