### ISSUE TITLE
Chapter 12: Adding cents to the amount and submitting results in error

### ISSUE THREAD

**Issue by cjboco** [vercel/next-learn#454]
On Chapter 12, Section 4

[https://nextjs.org/learn/dashboard-app/mutating-data](https://nextjs.org/learn/dashboard-app/mutating-data)

After adding the `updateInvoice()` functionality, attempting to add cents to any amount value results in error message `Enter valid amount` (Safari) `Please enter a valid value. The two nearest valid values are 5 and 6` (Chrome).

<img width="1111" alt="Screenshot 2023-11-16 at 11 31 34 AM" src="https://github.com/vercel/next-learn/assets/351122/f51d0bf4-856f-4221-b2d3-8149e197fa3e">
(Safari)

<img width="1111" alt="Screenshot 2023-11-16 at 11 27 48 AM" src="https://github.com/vercel/next-learn/assets/351122/f535c1b4-2351-48a3-bdb4-a662021b8f4c">
(Chrome)

Two fix this issue, I added the `step` attribute to the amount `<input>`, like so:

```
<input
   id='amount'
   name='amount'
   type='number'
   step='0.01'
   defaultValue={invoice.amount}
   placeholder='Enter USD amount'
   className='peer block w-full rounded-md border border-gray-200 py-2 pl-10 text-sm outline-2 placeholder:text-gray-500'
/>
```

**Comment by JairGH** [comment]
Nice!

**Comment by delbaoliveira** [comment]
Thank you @cjboco 🙏🏼  The missing step was added on this PR: https://github.com/vercel/next-learn/pull/410/commits/6eb374ea24a02a5756747204cd7a5b2163c4c494
