### ISSUE TITLE
Typos in Chapter 16 - adding metadata subsection

### ISSUE THREAD

**Issue by mandeep-s1ngh** [vercel/next-learn#460]
Without sounding so fussy. It should be "Next.js has a range **`of`** special files that are specifically **`used`** for metadata purposes: "

![image](https://github.com/vercel/next-learn/assets/92678152/16330562-db66-4670-b6fb-7690fc3d9afb)

**Comment by delbaoliveira** [comment]
Agree @mandeep-s1ngh, the grammar here needs improvement. Updated, should be landing soon. Thank you!
