### ISSUE TITLE
Chapter 15 - In authentication section need to highlight adding SQL in auth.ts

### ISSUE THREAD

**Issue by flickerbox-tom** [vercel/next-learn#461]
In the authentication section when the getUser function is added along with the SQL code, just need to add a reminder to add the SQL reference on line 4.

"After validating the credentials, create a new getUser function that queries the user from the database."

`import { sql } from '@vercel/postgres';`

**Comment by Connor-Skudlarek** [comment]
Indeed. It will error without the import, and the blue highlight doesn't indicate the addition. Good catch!

**Comment by delbaoliveira** [comment]
Very good catch! Thank you @flickerbox-tom 😄
