### ISSUE TITLE
Chapter 8 - Inconsistent Log

### ISSUE THREAD

**Issue by mukham12** [vercel/next-learn#463]
Found a teensy-weensy hiccup and need your help ironing it out 😄 (thanks for bearing with the typo spree lately).

In Chapter 8, while discussing simulating a [slow data fetch](https://nextjs.org/learn/dashboard-app/static-and-dynamic-rendering#simulating-a-slow-data-fetch),  the code block logs a message `Data fetch complete after 3 seconds.`, while the subsequent output block has the word complete`d` (with an extra letter 'd'). 

![tempsnip](https://github.com/vercel/next-learn/assets/55890311/378e3d4c-8b39-42ef-adac-cd4992d776f1)

**Comment by delbaoliveira** [comment]
Thank you 💅🏼 💛
