### ISSUE TITLE
[Dashboard] Chapter 16. Website code example discontinuity (—minor issue—)

### ISSUE THREAD

**Issue by Connor-Skudlarek** [vercel/next-learn#464]
This is a minor issue. Does not affect actual coding execution if only the blue highlighted portions are copied.

On the website for chapter 16, file `/app/layout.tsx` in the "Page title and descriptions" section.

<img width="531" alt="image" src="https://github.com/vercel/next-learn/assets/89144546/0b1a7e72-5b73-436f-b047-f30648a422b1">

This should be showing "`export default function RootLayout`" like it does in chapter 3.

<img width="533" alt="image" src="https://github.com/vercel/next-learn/assets/89144546/580f5931-b609-4e61-8d95-c99a0345ca15">

It shouldn't have the Page() function in the layout.tsx file, and it can't be doing an `export default function` on two different functions.

**Comment by delbaoliveira** [comment]
Thank you @Connor-Skudlarek 🙏🏼 Updated, should be landing soon.
