### ISSUE TITLE
Alt tag missing upon request to deploy to vercel

### ISSUE THREAD

**Issue by kirso** [vercel/next-learn#465]
In chapter 6 in order to add the database, we are asked to deploy to Vercel.

When pushing `pnpm build` though the error occurs asking to add "Alt" tags to <Image> component where its missing in the invoice section.

I understand that we might be fixing it in the future, however the build fails if not fixed otherwise.

**Comment by delbaoliveira** [comment]
Thank you for letting us know @kirso. We need the `alt` to be empty for Chapter 14 on improving accessibility.

However, I think I can update the chapter slightly to show how removing the `alt` tag will give a warning when running `next lint`, rather than the other way round where we ask them to fix the alt tag.

**Comment by aniel928** [comment]
I see the alt tag was updated on the first instance of `Image`, but the alt tag is still missing on line 88.

**Comment by nemchik** [comment]
Ref my P.S. note in https://github.com/vercel/next-learn/issues/469 copying here for visibility:

> per the instructions in chapter 6 when deploying from GitHub to Vercel I receive errors about the missing alt attributes that are later added in chapter 14. I figured it would be easy to add on my own but I looked ahead in the material to see it was covered in a later chapter and waited patiently, but there was no indication in chapter 6 that this was expected. This topic could warrant a separate issue, and the outcome could either be to cover the alt attribute requirement sooner so that the Vercel deploy can be successful, or somehow otherwise keep that code commented until it's time to cover accessibility in chapter 14, or at least add some notes in chapter 6 about the deploy failing until you reach chapter 14 to correct the alt attributes (although that is quite a few chapters to cover between 6 and 14).

https://github.com/vercel/next-learn/pull/468 included blank alt attributes, which would also have solved the deploy error problem and left room to cover the importance of proper alt attributes in chapter 14, but the PR was closed.
