### ISSUE TITLE
Chapter 10 - Reference Link Needs an Update

### ISSUE THREAD

**Issue by mukham12** [vercel/next-learn#470]
In Chapter 10, within the segment discussing [partial prerendering](https://nextjs.org/learn/dashboard-app/partial-prerendering#how-does-partial-prerendering-work), there are reference links to two React documentation pages. The link for Concurrent APIs directs to the [updated React documentation](http://www.react.dev/). However, the link for Suspense currently points to the old [React page](https://17.reactjs.org/docs/concurrent-mode-suspense.html). Kindly update the Suspense link to the [new documentation page](https://react.dev/reference/react/Suspense).

![image](https://github.com/vercel/next-learn/assets/55890311/47eacb0f-9858-4751-92c5-cf6449c19dc2)

**Comment by delbaoliveira** [comment]
Once again, thank you @mukham12 🚀 🎉
