### ISSUE TITLE
Could not locate the repository for starter-example.

### ISSUE THREAD

**Issue by helloEarth** [vercel/next-learn#474]
When i run:
`npx create-next-app@latest nextjs-dashboard --use-npm --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example/"`

It shows: 
**Could not locate the repository for "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example". Please check that the repository exists and try again.**

But if i just run:
`npx create-next-app@latest nextjs-dashboard`
Everything is fine.

Node version: v17.2.0 (Same with v18.18.2)
OS: MacOSX, M1 chip

I am using work network. But i can clone `https://github.com/vercel/next-learn.git` this project down. Dont know if this matters.

**Comment by StephDietz** [comment]
@helloEarth thanks for the feedback! I was unable to reproduce this. Running the command in my terminal clones the repo as expected. Is this issue still happening for you?

**Comment by helloEarth** [comment]
> @helloEarth thanks for the feedback! I was unable to reproduce this. Running the command in my terminal clones the repo as expected. Is this issue still happening for you?

Yes, this issue is still happening.

**Comment by helloEarth** [comment]
![screenshot-20231128-173416](https://github.com/vercel/next-learn/assets/2564047/b016c729-2319-44e8-b839-e11fad465561)

**Comment by nikola-golijanin** [comment]
Im also getting same issue
![Capture](https://github.com/vercel/next-learn/assets/64159013/c5252528-f329-495a-8c78-87817b7f7820)

**Comment by firtree-23** [comment]
Hi altogther, unfortunately I experience the same problem.
Win 10
Node 20.10.0,
npm 10.2.4
Any sugestions? Thanks in advance

**Comment by Valdhor** [comment]
Same issue here using MacOS Sonoma 14.2.1 on M2 Mac. 
Node 20.10.0
npm 10.2.5

My workaround...
npx create-next-app@latest nextjs-dashboard --use-npm
Would you like to use TypeScript? … Yes
Would you like to use ESLint? … Yes
Would you like to use Tailwind CSS? … Yes
Would you like to use `src/` directory? … No
Would you like to use App Router? (recommended) … Yes
Would you like to customize the default import alias (@/*)? … No

Download the zip file from the "Code" button at https://github.com/vercel/next-learn
Unzip the file
Move the contents of next-learn-main/dashboard/starter-example/ to nextjs-dashboard/ (replace all when asked)
cd nextjs-dashboard
npm i
npm run dev

**Comment by leerob** [comment]
I am not able to reproduce this. Please open a new issue if you are still having trouble here. Thank you!
