### ISSUE TITLE
Chapter 8 - Incorrect image in curriculum

### ISSUE THREAD

**Issue by jameskajon** [vercel/next-learn#475]
The first image in chapter 8 appears to be the incorrect image. The image alt says "Diagram showing how users hit the CDN instead of the server when requesting a page" but this not what the image shows. The image shown is a repeat from chapter 4 with alt of "Diagram showing how adding a folder called dashboard creates a new route '/dashboard'."

**Comment by StephDietz** [comment]
@jameskajon thank you for opening this issue! It has been fixed :)
