### ISSUE TITLE
Chapter 15:  auth.config.ts issue

### ISSUE THREAD

**Issue by laviedegeorge** [vercel/next-learn#477]
During authentication Login seems to be successful but the app refuses to redirect to the dashboard page. After some investigation, I found out that the `auth` param in the  `authorized` call back in `auth.config.ts` is null. But `auth.js` works fine as the user data is gotten and returned as accepted.

**Comment by Xelaflash** [comment]
I had the same issue.
Linked with issue [252](https://github.com/vercel/next-learn/issues/252)
Fix: add `NEXTAUTH_URL=http://localhost:3000` to `.env` file or update package (did not try the update but this is the solution of the issue)

**Comment by laviedegeorge** [comment]
@Xelaflash Thank you very much. I fixed the issue 1 hour ago. I had to go through the finished version and noticed the change in Next version. I upgraded Next.js on my project and it worked.

**Comment by laviedegeorge** [comment]
Issue can be fixed by upgrade Next.js to latest version
