### ISSUE TITLE
Chapter 9: file name typo

### ISSUE THREAD

**Issue by suzuki** [vercel/next-learn#485]
### About

I think this file name was wrong:

<img width="294" alt="screenshot" src="https://github.com/vercel/next-learn/assets/10488/39a647f1-b3f5-4eab-a52e-1798548a3385">

- Wrong: `/app/dashboard/page.tsx`
- Correct: `/app/dashboard/(overview)/page.tsx`

### URL

- https://nextjs.org/learn/dashboard-app/streaming#grouping-components

**Comment by StephDietz** [comment]
@suzuki thank you for the feedback! We have a PR in progress fixing this typo
