### ISSUE TITLE
Missing "alt" on "./app/ui/invoices/table.tsx:88:24" causes TypeError while deploying on Vercel

### ISSUE THREAD

**Issue by dangol-anish** [vercel/next-learn#488]
In Chapter 6, as I worked on deploying the repository to Vercel to set up the database, I encountered an error during the deployment process.

![Screenshot 2023-11-26 at 11 24 04](https://github.com/vercel/next-learn/assets/121813673/c3ea17d5-440f-439e-ab3a-d00aeb93f075)

This issue can be solved by adding an "alt" attribute to the < Image > component.

**Comment by nemchik** [comment]
#472 does not fix the issue. There were two of the same issue in the same file and only one was fixed. https://github.com/vercel/next-learn/pull/473 and https://github.com/vercel/next-learn/pull/482 both attempt to fix the issue, which is also mentioned in #465 and #469 and #480
