### ISSUE TITLE
npm install failling on create next app and has something to do with bcrypt

### ISSUE THREAD

**Issue by ti-deart** [vercel/next-learn#489]
So, I tried to do the first command on the guide that creates the project and although the directory was created it gives this error when it tries to do `npm install`

_npm install_
_npm ERR! code 7_
_npm ERR! path /home/xaxa/code/nextjs-dashboard/node_modules/bcrypt_
_npm ERR! command failed_
_npm ERR! command sh -c node-pre-gyp install --fallback-to-build_

my node version: v18.18.0
my npm version: 9.8.1

**Comment by delbaoliveira** [comment]
Hey @ti-deart, this error means `npm` is encountering problems while trying to install `bcrypt`. It may be a compatibility issue with `bcrypt` and your environment. You can try uninstalling `bcrypt` and using `bcryptjs` instead. 

For bugs or issues, please also see the `bcrypt` repo: https://github.com/kelektiv/node.bcrypt.js
