### ISSUE TITLE
Possible typos in chapter 7, 9

### ISSUE THREAD

**Issue by agan-k** [vercel/next-learn#492]
Chapter 7
[Choosing how to fetch data](https://nextjs.org/learn/dashboard-app/fetching-data#choosing-how-to-fetch-data)
[API layer](https://nextjs.org/learn/dashboard-app/fetching-data#api-layer)
APIs are an intermediary layer between your application code and database. There are a few cases where you might use an API:

1. If you're using 3rd party services that provide an API.

2. If you're fetching data <ins>from the client</ins>, you want to have an API layer that runs on the server to avoid exposing your database secrets to the client.

### Shouldn't second point read: <ins>ON</ins> the client?

Chapter 9
[Streaming a whole page with loading.tsx](https://nextjs.org/learn/dashboard-app/streaming#streaming-a-whole-page-with-loadingtsx)
//..
A few things are happening here:

loading.tsx is a special Next.js file built on top of Suspense, it allows you to create fallback UI to show as a replacement while page content loads.
Since ` <Sidebar> ` is static, so it's shown immediately. The user can interact with ` <Sidebar> ` while the dynamic content is loading.

### Shouldn't it red `<SideNav>` ?

**Comment by leerob** [comment]
Thank you! Will fix.
