### ISSUE TITLE
After adding noStore in chapter 8, I get LOTS of issues connecting to the db locally (seems ok with the hosted version)

### ISSUE THREAD

**Issue by PaulHaze** [vercel/next-learn#493]
Everything so far works without issue until adding noStore to the various data calling functions in data.ts. Once I do this I repeatedly get errors locally 

in the terminal
<img width="714" alt="Screen Shot 2023-11-29 at 10 59 39 am" src="https://github.com/vercel/next-learn/assets/20569604/79932014-2fe5-4765-b4b7-cbb2d4e690b1">

on the website:
<img width="300" alt="Screen Shot 2023-11-29 at 11 02 41 am" src="https://github.com/vercel/next-learn/assets/20569604/08839065-a4fa-4f72-aef0-241d5d551761">

The errors change with each reload, most often with fetchInvoices but sometimes with the other functions too. If you KEEP reloading the page over and over after about 5 or 6 (sometimes more) it will finally work. But then as soon as you add anything new to the app (like the loading page, or the skeletons component) it will then fail again and you have to keep reloading again. 

I have noticed this only seems to affect it locally. The site that is hosted via vercel seems to be ok. I am not sure if this is just an issue just with my machine or if this is a common issue with developing locally and using noStore. Either way, it makes working through the tutorial after this point VERY frustrating. 

If someone could let me know what I am doing wrong and how to prevent these errors I would appreciate it.....

**Comment by mrananderson** [comment]
I got the same errors. Kindly let me know if you were able to figure out what caused it.

**Comment by leerob** [comment]
Do you see this issue with the final example as well? Or only on your working branch?

**Comment by mrananderson** [comment]
Working branch. Once I reinstalled node modules and restarted the server I did not get any more errors.

**Comment by leerob** [comment]
Removing `noStore()` here: https://github.com/vercel/next-learn/pull/764
