### ISSUE TITLE
getting a failed build after chapter 7 

### ISSUE THREAD

**Issue by WarrenAdams8** [vercel/next-learn#494]
I am getting a failed Vercel build after chapter 7,It is working locally.
 
<img width="912" alt="failed build" src="https://github.com/vercel/next-learn/assets/38167058/6b4cd141-910b-4a80-97d0-cd89e6704e4a">

I  copied the .env.local from Vercel correctly, so I am unsure why it isn't working.

**Comment by jpkdomgen** [comment]
Hi,

Please copy .env.local data to .env file at root of the project.

that should solve the issue. 

![image](https://github.com/vercel/next-learn/assets/114588419/1dee44ab-1d8e-43f9-8a25-8924752a2f11)

**Comment by leerob** [comment]
^ Yes, please ensure the environment variables are correct! Thank you.
