### ISSUE TITLE
Chapter 6 - Typo in  (setting-up-your-database)

### ISSUE THREAD

**Issue by aaryannipane** [vercel/next-learn#497]
There is a typo in the [Troubleshooting section of Chapter 6](https://nextjs.org/learn/dashboard-app/setting-up-your-database#seed-your-database)

observe the last point of it 👇 

- If you continue to experience issues while seeding your **_`Verce`_** Postgres database...

should be 

- If you continue to experience issues while seeding your **_`Vercel`_** Postgres database...

_**`verce`**_ ➡️  **`vercel`**

**Comment by leerob** [comment]
Thank you!
