### ISSUE TITLE
Chapter 11 - Pagination doesn't give me different data

### ISSUE THREAD

**Issue by Fardeen-Awais** [vercel/next-learn#500]
I learn pagination from chapter 11. Pagination works but the data is still static doesn't dynamically change when switch page. 

Page 01: 
![image](https://github.com/vercel/next-learn/assets/101203786/f86b5fa0-2735-4e12-86f6-ca98819d9130)

Page 02:
![image](https://github.com/vercel/next-learn/assets/101203786/f0e23c2e-c279-4180-ae90-9a679c8a14b1)

Both data is same. Second as a beginner in this chapter i find that there is lack of instruction regarding this function in pagination.tsx: 
![image](https://github.com/vercel/next-learn/assets/101203786/431f380a-8e05-41dd-bf91-e7f83405b303)

So, Please check these things and help beginners. 

Thank you vercel for your support. ♥
Have a nice Day!

**Comment by deepakbrahmania** [comment]
I was able to correct it myself.  It was a quick fix on the `createPageURL` only.

```js
const createPageURL = (pageNumber: string | number) => {
    const param = new URLSearchParams();
    
    // get the rest of the params from the url
    const allParams = Array.from(searchParams.entries());
    
    // modify the page param only, keeping the rest as it is.
    allParams.forEach(([key, value]) => {
      if(key === 'page')
        param.set('page', pageNumber.toString());
      else
        param.set(key, value);
    })
    // newly created path with existing filters and modified page param.
    return `${pathname}?${param.toString()}`
  }
```

**Comment by liwenz** [comment]
I have finishchapter 11, but I have not found the page number. What's wrong? Which part I lost?

**Comment by liwenz** [comment]
I did. 
I only follow the tutorial. 
check my github: https://github.com/liwenz/nextjs-dashboard2/tree/chapter11
