### ISSUE TITLE
ReferenceError: Request is not defined.

### ISSUE THREAD

**Issue by leopardjay** [vercel/next-learn#501]
Loot at the picture that I attached.

**Comment by yaotutu** [comment]
I have the same problem. When I initialize this project using npx create-next-app@latest nextjs-dashboard --use-npm --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example", then I run npm run dev.

**Comment by DroidZed** [comment]
same thing here

**Comment by annamrp** [comment]
What version of Node are you using? In my case the error was solved by changing to v18 (I was using v16)
Hope that it helps!

**Comment by DroidZed** [comment]
Yes the error comes from the fact that we need to run the app with Node v18+. Any version below won't work lol

**Comment by leerob** [comment]
Correct, please use Node.js 18+ 😄
