### ISSUE TITLE
Wrong lines highlighted on /streaming section

### ISSUE THREAD

**Issue by Bokdol11859** [vercel/next-learn#506]
https://nextjs.org/learn/dashboard-app/streaming#practice-streaming-latestinvoices

Instead of these three lines (39 ~ 41) being highlighted, 

<img width="820" alt="Screenshot 2023-12-05 at 9 31 20 PM" src="https://github.com/vercel/next-learn/assets/80627536/36f3c6b5-9760-4c29-8909-01f3d49f6ecc">

It should rather be (40 ~ 42)

<img width="838" alt="Screenshot 2023-12-05 at 9 32 06 PM" src="https://github.com/vercel/next-learn/assets/80627536/eb9cb0bb-2ca6-4864-b3c9-dcd8cae84faa">

**Comment by leerob** [comment]
Thank you!
