### ISSUE TITLE
Inconsistency between repo and 'learn' docs in Chapter 4

### ISSUE THREAD

**Issue by adilapapaya** [vercel/next-learn#511]
In [the docs](https://nextjs.org/learn/dashboard-app/creating-layouts-and-pages), `dashboard` is located under `/app/dashboard` and the link to open the dashboard page is set to http://localhost:3000/dashboard. 

In the repo, `dashboard` Is located at `/app/ui/dashboard/` so one actually needs to navigate to http://localhost:3000/ui/dashboard to view the dashboard page.

Along the same vein, the docs assume `customer` and `invoice` pages are nested under `app/dashboard` but they are actually under `app/ui/` in the code (at the same level as `dashboard` which is also under `app/ui`)

**Comment by finalManu** [comment]
If you continue reading in the same chapter you'll see that it guides the reader to create such directories and pages. The diagrams at the start of the chapter are an overview.

**Comment by adilapapaya** [comment]
Can you point out where you're seeing this? I see that even in the later chapters, the docs are inconsistent with where the code is actually located in the repo. For example, here, the text says `/app/dashboard/invoices/page.tsx` but the code snippet itself is importing from `/app/**ui**/dashboard/invoices/`

<img width="980" alt="image" src="https://github.com/vercel/next-learn/assets/4053020/69642030-9a5f-4828-ac6e-a33bfb6399d2">

**Comment by mark-P0** [comment]
https://nextjs.org/learn/dashboard-app/creating-layouts-and-pages#creating-the-dashboard-page

![image](https://github.com/vercel/next-learn/assets/63066834/dcf88584-2143-4627-b413-c5d71e313753)

The files under `/app/ui/` are components that are imported in the pages created throughout the course. I was also a bit confused at first.

**Comment by adilapapaya** [comment]
aaah, thank you @mark-P0 ! Closing this issue :)
