### ISSUE TITLE
Unnecessary semicolon in Chapter 2 CSS code

### ISSUE THREAD

**Issue by bookercodes** [vercel/next-learn#512]
<img width="1431" alt="Screenshot 2023-12-13 at 14 08 36" src="https://github.com/vercel/next-learn/assets/11927968/ed8ee353-cc5c-433e-aef9-5634bb747083">

In chapter 2, under CSS modules, the code snippet has a superfluous `;`

**Comment by leerob** [comment]
Thank you! Fixing this.
