### ISSUE TITLE
chapter 13, test wrong be wrong

### ISSUE THREAD

**Issue by liwenz** [vercel/next-learn#515]
I follow the command to code , when I test, 
For example, visit http://localhost:3000/dashboard/invoices/2e94d1ed-d220-449f-9f11-f0bbceed9645/edit.
fetchInvoiceById 
console.log(invoice); // Invoice is an empty array []
it has not catched the non- id
Then it go to 

app\ui\invoices\edit-form.tsx (21:63) @ id

  19 | customers: CustomerField[];
  20 | }) {
> 21 | const updateInvoiceWithId = updateInvoice.bind(null, invoice.id);
     |                                                             ^
  22 | return (
  23 |   <form action={updateInvoiceWithId}>
  24 |     <div className="rounded-md bg-gray-50 p-4 md:p-6">

I wonder it has not catched the wrong

code at https://github.com/liwenz/nextjs-dashboard   chapter  13 finish sth wrong

**Comment by liwenz** [comment]
I change it as follow:
console.log(invoice[0]); // Invoice is an empty array []
then 404 catched!

**Comment by liwenz** [comment]
throw new Error('Failed to Delete Invoice');
works fine at first, but later:

app\lib\actions.ts (75:8) @ deleteInvoice

  73 | export async function deleteInvoice(id: string) {
  74 | 
> 75 | throw new Error('Failed to Delete Invoice');
     |      ^
  76 |
  77 | try{
  78 |   await sql`DELETE FROM invoices WHERE id = ${id}`;

is the grammer wrong?

**Comment by leerob** [comment]
Hey there, I'm sorry but it is not clear what the issue is here. Are you still seeing this? Could you provide more details? The test appears to be correct in the chapter.
