### ISSUE TITLE
replace "`alt` tag" with "`alt` text" or "`alt` attribute"

### ISSUE THREAD

**Issue by stefanprobst** [vercel/next-learn#517]
the section on "Improving Accessibility" talks about an "`alt` tag" (see https://nextjs.org/learn/dashboard-app/improving-accessibility#using-the-eslint-accessibility-plugin-in-nextjs).

`alt` is not an html tag but an html attribute, so i think it would be better to say "`alt` text" or "`alt` attribute".

**Comment by leerob** [comment]
Thank you!

**Comment by stefanprobst** [comment]
hi @leerob, you've missed two more instances of "`alt` tag" on https://nextjs.org/learn/dashboard-app/improving-accessibility:

- "However, what would happen if you had an image without an alt tag? Let's find out!"
- "Go to /app/ui/invoices/table.tsx and remove the alt tag from the image. You can use your editor's search feature to quickly find the image tag:"
