### ISSUE TITLE
Chapter 6: Cannot seed database

### ISSUE THREAD

**Issue by 7-days-a-goal** [vercel/next-learn#518]
I can't seed database. Can anyone help me solve this problem?     /(ㄒoㄒ)/~~

![1703225851740](https://github.com/vercel/next-learn/assets/102860151/e19c5295-0835-4adf-8e0f-3fa13e633bc7)
PS D:\projects\next\nextjs-dashboard> npm run seed

> seed
> node -r dotenv/config ./scripts/seed.js

node:events:493
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on WebSocket instance at:
    at emitErrorAndClose (D:\projects\next\nextjs-dashboard\node_modules\ws\lib\websocket.js:1016:13)
    at ClientRequest.<anonymous> (D:\projects\next\nextjs-dashboard\node_modules\ws\lib\websocket.js:864:5)
    at ClientRequest.emit (node:events:515:28)
    at TLSSocket.socketErrorListener (node:_http_client:495:9)
    at TLSSocket.emit (node:events:515:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

Node.js v21.0.0

**Comment by wanglin1329** [comment]
Have you resolved it? I am encountering the same issue as you, and I'm getting the same error on two different computers.

**Comment by 7-days-a-goal** [comment]
> Have you resolved it? I am encountering the same issue as you, and I'm getting the same error on two different computers.

Not yet

**Comment by myat-hsu-mon** [comment]
I have the same issue when seeding. How to solve it?

**Comment by leerob** [comment]
Could you try Node.js 20 LTS instead of 21?

**Comment by YYGod0120** [comment]
> Could you try Node.js 20 LTS instead of 21?你能试试 Node.js 20 LTS 而不是 21 吗？
 
Even if it is changed to version 20, it still won’t work

**Comment by prakhar9015** [comment]
I am also facing the same issue... ☹️

**Comment by joshuayapwj98** [comment]
Hi! For those experiencing issues with populating the table, in particular, **error -4077**, a solution for me was to temporarily downgrade your node version to LTS14. 

`nvm install 14`
`nvm use 14`

It worked for me. Hope it helps!

**Comment by YYGod0120** [comment]
> Hi! For those experiencing issues with populating the table, in particular, **error -4077**, a solution for me was to temporarily downgrade your node version to LTS14.
> 
> `nvm install 14` `nvm use 14`
> 
> It worked for me. Hope it helps!

It works,but why can't use npm 20 or 21

**Comment by don-esteban** [comment]
I remember darkly that TLS defaults/support in Node versions greater 14 has changed. This is an issue of your environments. I'm not savvy with networking, but suspects are OSes, VPNs and Firewalls. If you have time and if you are patient, debug/monitor networking.

**Comment by vignxs** [comment]
try running vercel dev

**Comment by vignxs** [comment]
https://github.com/orgs/vercel/discussions/2350#discussioncomment-5850746

**Comment by leerob** [comment]
I am not able to reproduce this. Please open a new issue if you are still having trouble here. Thank you!

We are also making the seeding easier in this PR by allowing you to hit a URL in the browser: https://github.com/vercel/next-learn/pull/764
