### ISSUE TITLE
Question: Is it best practice to create a directory in `app` that is not related to Routing?

### ISSUE THREAD

**Issue by ryota-murakami** [vercel/next-learn#521]
In App Router, any folder never activate as a routing unless you put `page.tsx`.  
Unlike the pages router, it is true that you can freely create folders unrelated to routing.  

Although There is no technical advantage to creating a folder in `app` that is not related to routing, and on the other hand, there is a disadvantage of adding more folders, which makes it difficult to understand which part is the router.

I think that most people create the `ui` and `lib` of Learn Next cource outside of `app` because [shadcn/ui](https://bestofjs.org/projects/shadcnui), 
a very popular UI library in Next.js community, also creates `components` and `lib` directories outside of `app` when it is installed in Next.js (this is completely my guess, though). I guess most of you are creating `ui` and `lib` outside of `app` (this is completely my guess).

Personally, I think it is best practice to place in `app` only the folder that will be the routing path, files with [special names](https://nextjs.org/docs/app/building-your-application/routing#file-conventions) that affect the behavior of the App Router, and co-locations of one off files used on specific `page.tsx` that start with an underscore `_foo`.  
I believe that this is the best practice.

Appreciate your feedback!

**Comment by PaulHaze** [comment]
I was wondering this exact thing... Hvaing UI and lib elements in the App folder just felt a bit wrong to me, and I'd like to hear the thinking behind it and any advantages of it....

**Comment by ryota-murakami** [comment]
@PaulHaze Thanks for the comments!
I haven't heard a lot of other people's opinions yet, but I think Vercel may have a policy of not defining a specific bestpractice for Directry Structure and leaving it up to the user.

That's fine for solo developers, but for team developers, the directry tends to get cluttered, and that's currently the case in the Next.js project I'm working on. 😅

**Comment by leerob** [comment]
We have docs on this here!

https://nextjs.org/docs/app/building-your-application/routing/colocation

**Comment by ryota-murakami** [comment]
@leerob Thanks Lee!
