### ISSUE TITLE
Error in first deployment to vercel

### ISSUE THREAD

**Issue by mahmudkarimov** [vercel/next-learn#522]
Hi folks, thanks for the turorial, I find it very useful. However I'm having error in first deployment. Re-did second time with updating packages and getting same error again in vercel: 

 

> <html>
<body>

Failed to compile.
12:05:15.719 |  
12:05:15.719 | ./app/ui/acme-logo.tsx:2:26
12:05:15.719 | Type error: Cannot find module '@/app/ui/fonts' or its corresponding type declarations.
12:05:15.719 |  
12:05:15.719 | 1 \| import { GlobeAltIcon } from '@heroicons/react/24/outline';
12:05:15.719 | > 2 \| import { lusitana } from '@/app/ui/fonts';
12:05:15.719 | \|                          ^
12:05:15.719 | 3 \|
12:05:15.719 | 4 \| export default function AcmeLogo() {
12:05:15.719 | 5 \|   return (
12:05:15.791 | Error: Command "npm run build" exited with 1
12:05:16.483

<br class="Apple-interchange-newline">
</body>
</html>

Any help is greatly appreciated!

**Comment by leerob** [comment]
https://github.com/vercel/next-learn/issues/354#issuecomment-1808418171
