### ISSUE TITLE
Chapter 12: Typos in the Learning Course

### ISSUE THREAD

**Issue by 2wheeh** [vercel/next-learn#523]
1. A mistake in the hyperlink URL for `Object.fromEntries()` which currently redirects to the MDN page for `Object.entries()`. It is same in the next.js docs which is on fixing in https://github.com/vercel/next.js/pull/59935
    
2. Typos in this sentence :
    > You will see a temporary TS error for the ~~invoices~~ invoice prop in your terminal because ~~invoices~~ invoice could be potentially undefined. 

    The prop of `EditInvoiceForm` is `invoice`. 
    https://github.com/vercel/next-learn/blob/e75f71499fd2bc2dbabf60992f423e07d33c15fd/dashboard/final-example/app/ui/invoices/edit-form.tsx#L16

Thank you for the amazing Learning Course !

**Comment by aruprakshit** [comment]
I also came here to report this and found it is already reported. :)

**Comment by leerob** [comment]
Thank you!

**Comment by aruprakshit** [comment]
> Thank you!

Could you give the commit link here also?

**Comment by 2wheeh** [comment]
> > Thank you!
> 
> 
> 
> Could you give the commit link here also?

Apparently, It's not open sourced :)
