### ISSUE TITLE
Chapter 15: Suggested name for secret key is not automatically inferred by next-auth

### ISSUE THREAD

**Issue by j-bernardi** [vercel/next-learn#525]
The [current tutorial](https://nextjs.org/learn/dashboard-app/adding-authentication#setting-up-nextauthjs) suggests adding this variable to your .env file: AUTH_SECRET

However [next-auth](https://next-auth.js.org/configuration/options#secret) suggests that only NEXTAUTH_SECRET will be automatically inferred.

This led to me being a little confused about why my login wasn't working.

I'm deployed locally with 'vercel dev', at the moment.

Edit: this is a nice to have, but the site fails in a pretty ugly way when this occurs. It took me a while to figure out what was up!

In client console, the error is `Uncaught SyntaxError: Unexpected token '<'`, and the page is a badly formatted version of the sidebar (e.g. the icons take up the whole page).

The server at least spat out:
```
 ⚠ Next.js can't recognize the exported `config` field in route "/middleware":
Unsupported node type "MemberExpression" at "config.secret".
The default config will be used instead.
Read More - https://nextjs.org/docs/messages/invalid-page-config
```

Maybe some error handling around authentication would be a bonus, but probably not necessary to close this issue.

**Comment by anxiubin** [comment]
hey the link you attached is old version. you should look at [this document for the newest next-auth](https://authjs.dev/reference/nextjs#environment-variable-inference)
