### ISSUE TITLE
Unnecessary semicolon on Chapter 2

### ISSUE THREAD

**Issue by lailsonbm** [vercel/next-learn#526]
The second code example in the _CSS Modules_ section of the _Chapter 2 - CSS Styling_ contains semi-colon that should not be there (see the screenshot below):

<img width="1892" alt="Screenshot 2023-12-27 at 11 13 13" src="https://github.com/vercel/next-learn/assets/114001/d1603b90-c5e0-4d57-abaf-ecc9ab5b9fc7">

**Comment by leerob** [comment]
Thank you! Fixing
