### ISSUE TITLE
Chapter 12: Wrong line highlighted (Updating an Invoice)

### ISSUE THREAD

**Issue by Lxdovic** [vercel/next-learn#528]
https://nextjs.org/learn/dashboard-app/mutating-data#updating-an-invoice

Instead of the 9th line
![Screenshot from 2023-12-28 14-33-26](https://github.com/vercel/next-learn/assets/80395681/cd4fd236-ab82-4f2a-bf75-c73d75e193ad)

line 11 should rather be highlighted
![Screenshot from 2023-12-28 14-33-01](https://github.com/vercel/next-learn/assets/80395681/2fecfc11-ae85-409c-a1d5-e0520ae761d4)

**Comment by leerob** [comment]
Thank you!
