### ISSUE TITLE
re-running seed script inserts duplicate invoices

### ISSUE THREAD

**Issue by murfett-au** [vercel/next-learn#538]
Each time `npm run seed` is executed, an extra 15 rows are inserted into the invoices table.

This is because:

1. no member of the `invoices` array exported from the placeholder include invoices[n].id; and
2. The `id` field is not included in the sql insert statement in the seed.ts script.

I have created https://github.com/vercel/next-learn/pull/537 to address these issues.

**Comment by leerob** [comment]
https://github.com/vercel/next-learn/pull/537#issuecomment-2185348626
