### ISSUE TITLE
Typo on https://nextjs.org/learn/dashboard-app/streaming

### ISSUE THREAD

**Issue by xkra** [vercel/next-learn#548]
![image](https://github.com/vercel/next-learn/assets/22492738/3d4fc8bb-0eed-4bec-bed7-6fac0646bea7)

The marked sentence is grammatically incorrect. I am no native speaker, but I suppose the sentence could be:

_Since <Sidebar> is static, _ it's shown immediately._

**Comment by delbaoliveira** [comment]
Thank you @xkra 🙏🏼 Will update
