### ISSUE TITLE
Chapter 10, Partial Prerendering - Grammatical mistake.

### ISSUE THREAD

**Issue by Arslaan0124** [vercel/next-learn#550]
I came across a minor grammatical error in the documentation in chapter 10 in the following heading.
https://nextjs.org/learn/dashboard-app/partial-prerendering#what-is-partial-prerendering.

The specific instance is in the sentence: "A static route shell is served, ensuring a initial load fast."
The correct version should be: "A static route shell is served, ensuring a fast initial load."

**Comment by leerob** [comment]
Thanks, will fix!
