### ISSUE TITLE
i got this issue on chapter 11 Adding Search and Pagination, can somebody tell me what's wrong????

### ISSUE THREAD

**Issue by andifauzi07** [vercel/next-learn#555]
this is the screenshot from my terminal

<img width="771" alt="Error chapter 11" src="https://github.com/vercel/next-learn/assets/120794559/0f89031a-88c0-4fa9-957f-f43177add2a3">

i just add noStore() function into the data.ts file, and then every time i move the chapter i got this error all the time. i never change anything on that file, can somebody help me????

**Comment by LeonardoSya** [comment]
Me too. Have you solved this problem ?

**Comment by andifauzi07** [comment]
not yet

**Comment by leerob** [comment]
This is your error, so it's something with your code for querying.

Could you reference the final application code here to see the delta?

![CleanShot 2024-01-20 at 21 00 49@2x](https://github.com/vercel/next-learn/assets/9113740/c8432259-9637-447f-971b-07e4be93b104)
