### ISSUE TITLE
initial error tutorial page 2

### ISSUE THREAD

**Issue by opencityint** [vercel/next-learn#556]
Newb here - I know (knew?) React. Started the beginner dashboard tutorial. Immediate error from page 2

```
nextjs-dashboard/app/ui/global.css Unknown word

> 1 | import '@/app/ui/global.css';
    | ^
  2 |  
  3 | export default function RootLayout({
```
IDGI - import as an unknown word
Thanks in advance for any info. Apologies if this is far too newb to ask here.

**Comment by leerob** [comment]
Hey there, it's not obvious what this error is coming from based on what you've provided. Could you open a new issue with more context or code, or we can reopen this one?
