### ISSUE TITLE
Database Error  Failed to fetch invoices  in Ch 11

### ISSUE THREAD

**Issue by LeonardoSya** [vercel/next-learn#557]
I encountered some problems when adding the <Search> component in Chapter 11. There's an error occurring when rendering the invoice page, and below is the error message. I followed the tutorial exactly as it is. Could there be an issue with this part of the tutorial?
Thanks.
![微信图片_20240115121436](https://github.com/vercel/next-learn/assets/120240967/04b49251-6aa5-445f-a743-1a7e564ec5b5)
![微信截图_20240115121540](https://github.com/vercel/next-learn/assets/120240967/b78f7dc9-1f88-4cdc-9b39-fc0bcd8a4399)

**Comment by liwenz** [comment]
which step which you did?

**Comment by liwenz** [comment]
I did,
check the result at
https://nextjs-dashboard2-plum.vercel.app/dashboard/invoices?page=2&query=l
and github 👍 
https://github.com/liwenz/nextjs-dashboard2/tree/chapter11

**Comment by LeonardoSya** [comment]
> I did, I only follow the tutorial. check the result at https://nextjs-dashboard2-plum.vercel.app/dashboard/invoices?page=2&query=l and github 👍 https://github.com/liwenz/nextjs-dashboard2/tree/chapter11

I fixed it already, something went wrong with my lib/data.ts. Thank you so much👍
