### ISSUE TITLE
Chapter 13: Unused import (updateInvoice)

### ISSUE THREAD

**Issue by 70928manson** [vercel/next-learn#563]
https://nextjs.org/learn/dashboard-app/error-handling#handling-404-errors-with-the-notfound-function

The updateInvoice function imported here is unused.  

![Screenshot from 2024-01-18 11-12-34](https://github.com/vercel/next-learn/assets/74696798/a17603b3-3837-45ec-8940-b72f899ffc4a)

People may feel confused when they see the unused import because they might think they have overlooked something.
I think it would be better to remove it.

**Comment by leerob** [comment]
Yes, but also `updateInvoice` is also mentioned in this chapter, so you can connect them 👍
