### ISSUE TITLE
Couldn't create new  project from learn page

### ISSUE THREAD

**Issue by khairnsaa** [vercel/next-learn#575]
i'm learning next js from [this page](https://nextjs.org/learn/dashboard-app/getting-started) and im getting an error while downloading the next starter project, it says "could not locate the repo", but when i check the link to the repo it's fine

![image](https://github.com/vercel/next-learn/assets/53510222/832e2ab4-1cd7-4f55-8d0c-34f7e81a3f61)

**Comment by lbudakov** [comment]
@khairnsaa Check this [comment](https://github.com/vercel/next-learn/issues/346#issuecomment-1911940317)
