### ISSUE TITLE
Some file names are different

### ISSUE THREAD

**Issue by kaji-hiro** [vercel/next-learn#581]
I noticed minor typos in the following file names:

1. https://nextjs.org/learn/dashboard-app/fetching-data#parallel-data-fetching

| now | Ideal |
| ---- | ---- |
| /app/lib/data.js | /app/lib/data.ts |
2. https://nextjs.org/learn/dashboard-app/improving-accessibility#:~:text=FormSchema%20as%20follows%3A-,/app/lib/action.ts,-const%20FormSchema%20%3D

| now | Ideal |
| ---- | ---- |
| /app/lib/action.ts | /app/lib/actions.ts |

Can I make fix PR?

**Comment by Ahmadjajja** [comment]
Hello maintainers, 
Would you please this issue to me??

**Comment by leerob** [comment]
Thank you! Fixing.
