### ISSUE TITLE
Chapter 15 not able to resolve '@/auth'

### ISSUE THREAD

**Issue by songproducer** [vercel/next-learn#598]
I installed with:

>npm install next-auth@beta

but on localhost when I try to load any page I get:

```
Module not found: Can't resolve '@/auth'
  4 | import { revalidatePath } from 'next/cache';
  5 | import { redirect } from 'next/navigation';
> 6 | import { signIn } from '@/auth';
  7 | import { AuthError } from 'next-auth';
  8 |
```

**Comment by delbaoliveira** [comment]
Thank you for reporting this @songproducer, I was able to reproduce it. We'll look into it!

**Comment by dccrissman** [comment]
I think paths need to be updated in tsconfig.json. I had to add these for paths to work from the tutorial:
```
"paths": {
      "@/app/*": ["app/*"],
      "@/*": ["/*"],
    }
```

**Comment by delbaoliveira** [comment]
Hey there! I'm closing this issue as we are removing NextAuth from the course. We have found that it can be overwhelming for beginners, and the content doesn't reflect our current auth recommendations. 

For those who would like to learn more about auth, I've written a guide that goes through the principles of auth and what Next.js features to use, including guides from popular auth libraries: https://nextjs.org/docs/app/building-your-application/authentication
