### ISSUE TITLE
Chapter 6, data has been set, but not shown in browse.

### ISSUE THREAD

**Issue by bsqgm** [vercel/next-learn#599]
This is the picture, I dont know why.
![image](https://github.com/vercel/next-learn/assets/37140581/5f3320d5-a7a7-4570-a5b9-e6f477bb13af)
![image](https://github.com/vercel/next-learn/assets/37140581/43b4848d-8039-4342-8db3-21bb9798e896)

**Comment by MyNameIsGuz** [comment]
Have you ever tried clicking on 'Choose a table'?

**Comment by leerob** [comment]
Hey there, I am not able to reproduce this. Please open a new issue if you are still having trouble here. Thank you!
