### ISSUE TITLE
Could not locate the repository

### ISSUE THREAD

**Issue by randyaa** [vercel/next-learn#60]
I keep running into a "Could not locate the repository" error when following the instructions at https://nextjs.org/learn/basics/create-nextjs-app/setup

```
npx: installed 1 in 2.349s
Could not locate the repository for "https://github.com/vercel/next-learn/tree/master/basics/learn-starter". Please check that the repository exists and try again.
```

Instructions say to check https://github.com/vercel/next-learn/blob/master/basics/errors/install.md but there's not much detail there and the commands are a bit different. I followed the text based instructions there (not the specific command) and removed everything past the project name which was then "Successful" but when starting the app it quickly failed for other reasons:

```
Installing dependencies:
- react
- react-dom
- next

+ react@17.0.2
+ react-dom@17.0.2
+ next@12.0.7
added 243 packages from 223 contributors and audited 255 packages in 44.584s
found 0 vulnerabilities


Installing devDependencies:
- eslint
- eslint-config-next


> core-js-pure@3.20.2 postinstall C:\code\nextjs-blog\node_modules\core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

+ eslint@8.6.0
+ eslint-config-next@12.0.7
added 170 packages from 100 contributors and audited 425 packages in 34.247s
found 0 vulnerabilities


Initialized a git repository.

Success! Created nextjs-blog at C:\code\nextjs-blog
```

```
 started server on 0.0.0.0:3000, url: http://localhost:3000
(node:19500) UnhandledPromiseRejectionWarning: ReferenceError: TextEncoder is not defined
    at C:\code\nextjs-blog\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:67:19
    at Object.<anonymous> (C:\code\nextjs-blog\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:900:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\code\nextjs-blog\node_modules\next\dist\compiled\react-server-dom-webpack\writer.browser.server.js:6:20)
(node:19500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Not supported
    at Object.loadConfig [as default] (C:\code\nextjs-blog\node_modules\next\dist\server\config.js:399:74)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nextjs-blog@ dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nextjs-blog@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

```

**Comment by lixplor** [comment]
I've met same issues. Here's my solution:
1. Check latest document for the template url. By now the create app command is:
```
npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
```
2. Install latest node.js version. When I was using node v10.12.x, I met same problem on starting up the project which showed me TextEncoder is not defined Error. Then I installed node.js v16.14.0 and `npm run dev`, it worked well.

**Comment by Dphilomath** [comment]
the app init command
`npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"`
still results in the same error as before 
_Could not locate the repository for "https://github.com/vercel/next-learn/tree/master/basics/learn-starter". Please check that the repository exists and try again._
Starting a project without example template using `npx create-next-app next-blog` works fine but of course that doesn't make use of the template.

**Comment by Dphilomath** [comment]
> I keep running into a "Could not locate the repository" error when following the instructions at https://nextjs.org/learn/basics/create-nextjs-app/setup
> 
> ```
> npx: installed 1 in 2.349s
> Could not locate the repository for "https://github.com/vercel/next-learn/tree/master/basics/learn-starter". Please check that the repository exists and try again.
> ```
> 
> Instructions say to check https://github.com/vercel/next-learn/blob/master/basics/errors/install.md but there's not much detail there and the commands are a bit different. I followed the text based instructions there (not the specific command) and removed everything past the project name which was then "Successful" but when starting the app it quickly failed for other reasons:
> 
> ```
> Installing dependencies:
> - react
> - react-dom
> - next
> 
> + react@17.0.2
> + react-dom@17.0.2
> + next@12.0.7
> added 243 packages from 223 contributors and audited 255 packages in 44.584s
> found 0 vulnerabilities
> 
> 
> Installing devDependencies:
> - eslint
> - eslint-config-next
> 
> 
> > core-js-pure@3.20.2 postinstall C:\code\nextjs-blog\node_modules\core-js-pure
> > node -e "try{require('./postinstall')}catch(e){}"
> 
> + eslint@8.6.0
> + eslint-config-next@12.0.7
> added 170 packages from 100 contributors and audited 425 packages in 34.247s
> found 0 vulnerabilities
> 
> 
> Initialized a git repository.
> 
> Success! Created nextjs-blog at C:\code\nextjs-blog
> ```
> 
> ```
>  started server on 0.0.0.0:3000, url: http://localhost:3000
> (node:19500) UnhandledPromiseRejectionWarning: ReferenceError: TextEncoder is not defined
>     at C:\code\nextjs-blog\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:67:19
>     at Object.<anonymous> (C:\code\nextjs-blog\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:900:5)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (C:\code\nextjs-blog\node_modules\next\dist\compiled\react-server-dom-webpack\writer.browser.server.js:6:20)
> (node:19500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:19500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
> Error: Not supported
>     at Object.loadConfig [as default] (C:\code\nextjs-blog\node_modules\next\dist\server\config.js:399:74)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! nextjs-blog@ dev: `next dev`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the nextjs-blog@ dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> ```

This was caused by some problem in proxy configuration as my institute uses a proxy server. I could use npm, git and apt by manually configuring proxies but this 

>`npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"` was failing.

`npx create-next-app nextjs-blog` works fine, most probably using the proxy for npm but the former fails. 
Temporary Workaround: I'm using a VPN with proxy which routes all traffic through the proxy server and although the speed is a setback, it gets the work done.

**Comment by bailinglan** [comment]
I succeeded by turning off the VPN. Switching the network environment may be one of the solutions.

**Comment by ycshill** [comment]
> I've met same issues. Here's my solution:
> 
> 1. Check latest document for the template url. By now the create app command is:
> 
> ```
> npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
> ```
> 
> 2. Install latest node.js version. When I was using node v10.12.x, I met same problem on starting up the project which showed me TextEncoder is not defined Error. Then I installed node.js v16.14.0 and `npm run dev`, it worked well.

我就不行呢  npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
Could not locate the repository for "https://github.com/vercel/next-learn/tree/master/basics/learn-starter". Please check that the repository exists and try again.

**Comment by ycshill** [comment]
I have the same problem

**Comment by dora-ljh** [comment]
> > I've met same issues. Here's my solution:
> > 
> > 1. Check latest document for the template url. By now the create app command is:
> > 
> > ```
> > npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. Install latest node.js version. When I was using node v10.12.x, I met same problem on starting up the project which showed me TextEncoder is not defined Error. Then I installed node.js v16.14.0 and `npm run dev`, it worked well.
> 
> 我就不行呢 npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter" Could not locate the repository for "https://github.com/vercel/next-learn/tree/master/basics/learn-starter". Please check that the repository exists and try again.

Trial run `npx create-next-app@latest nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"`

**Comment by Namnika** [comment]
> Install the latest node.js version. When I was using node v10.12.x, I met the same problem on starting up the project which showed me TextEncoder is not defined Error. Then I installed node.js v16.14.0 and npm run dev, it worked well.

As it should be installed node.js v16.4.0. Well, I'm having also the same.

> I have the same problem

Hi @ycshill, are you still facing that problem? 
In my case, I didn't meet with an issue as expected url works well!

**Comment by Bibooo25730** [comment]
Unknown command: "create-next-app@latest"

To see a list of supported npm commands, run:
  npm help

**Comment by GyeongHoKim** [comment]
The master branch no longer exists, so try the main branch instead.

**Comment by simonlagneaux** [comment]
> The master branch no longer exists, so try the main branch instead.

That did the trick, thanks!

**Comment by manovotny** [comment]
We made the following changes to address a few items highlighted in this issue.

* We've updated all messaging regarding expected node versions. We also added some lite "enforcement" here by adding `engines` to all the `package.json` files.
* We've updated all command references of `master` → `main`.
* We've added a note about proxys / VPNs to the [error page](https://github.com/vercel/next-learn/blob/main/basics/errors/install.md).

With those in place, I am going to close this issue. Please open a new issue if you are still experiencing problems.

**Comment by icarofr** [comment]
Apparently this issue is back again. Which is not exactly a big deal since we can just use the executable and follow the prompts, but it's not really a good thing when the official documentation points to commands that don't work.

```
user@laptop ~/t/sound-esp-2024 (dev) [1]> npx create-next-app@latest nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/main/basics/learn-starter"
Need to install the following packages:
create-next-app@13.5.3
Ok to proceed? (y) y
Could not locate the repository for "https://github.com/vercel/next-learn/tree/main/basics/learn-starter". Please check that the repository exists and try again.
```

**Comment by manovotny** [comment]
@icarofr I tried the command in your comment this morning and it appears to work correctly. One thing to keep in mind is that downstream issues or hiccups with NPM, which can affect command execution as well. It could be local network issues too, [as mentioned above](https://github.com/vercel/next-learn/issues/60#issuecomment-1710132610).

![CleanShot 2023-09-28 at 10 58 01@2x](https://github.com/vercel/next-learn/assets/446260/a51f40b7-3d54-4817-bfc6-00ccc9a33ca7)

**Comment by Connor-Skudlarek** [comment]
I also am having the same issue.

Node ver. 18.12.1
NPM ver. 9.6.1
Windows 10
create-next-app@13.5.4

Terminal:

"$ npx create-next-app@latest nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/main/basics/learn-starter"
Could not locate the repository for "https://github.com/vercel/next-learn/tree/main/basics/learn-starter". Please check that the repository exists and try again."

I have confirmed this on my work network as well as a mobile hotspot on my personal phone. Will try to confirm this as well on my personal computer at home, but it seems it might not just be a network issue.

**Comment by l-morales** [comment]
In case others find this thread in the future...ran into the reported issue as well. Issue persisted while running node v16.15.0 but was finally able to create the next app using the example template with node v18.19.0.

**Comment by franpandol** [comment]
Updated node to 18.19.0 and it worked.

**Comment by razakadegoke** [comment]
Updated node to latest with 
`nvm install node`
and it worked.

**Comment by yalinyy** [comment]
The master branch no longer exists, so try the main branch instead.
it worked.

**Comment by yalinyy** [comment]
您好~我是亚林，已收到您的邮件，会尽快回复~

**Comment by char-cole** [comment]
using Node 21.7.1, I'm trying to follow the instructions in https://faustjs.org/tutorial/get-started-with-faust and getting this same error.

I also tried cloning the faustjs repo https://github.com/wpengine/faustjs/tree/main and using a local example,
`npx create-next-app faust-test-1 --example  faustjs/examples/next/faustwp-getting-started/`
but this resulted in the following error:
`Could not locate an example named "faustjs/examples/next/faustwp-getting-started/"`

**Comment by lucas1295santos** [comment]
Same error here both with npm 21 and 18. I know that the repo exists because I can access this link through the browser just fine.
```
 ~/Desktop/react-study  npx create-next-app@latest nextjs-dashboard --use-npm --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example"
Could not locate the repository for "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example". Please check that the repository exists and try again.
```

**Comment by LeKarimDerradji** [comment]
> Updated node to latest with `nvm install node` and it worked.

This solution worked for me too

**Comment by yalinyy** [comment]
您好~我是亚林，已收到您的邮件，会尽快回复~

**Comment by lnjdsg** [comment]
As a case tutorial on the official website, the problem has not been solved for 2 years. Can you use Dim sum

**Comment by lnjdsg** [comment]
As a case tutorial on the official website, the problem has not been solved for 2 years. Can you use Dim sum

**Comment by nibinbaby** [comment]
upgrading the node version to v18.20.1 worked. Thanks for all the inputs.

**Comment by DvoeglazovIlya** [comment]
Same error: 
```
npx create-next-app@latest nextjs-dashboard --use-npm --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example"
Could not locate the repository for "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example". Please check that the repository exists and try again.
```

https://github.com/vercel/next-learn/blob/main/basics/errors/install.md

**Comment by abhaykumarprajpati** [comment]
> I keep running into a "Could not locate the repository" error when following the instructions at https://nextjs.org/learn/basics/create-nextjs-app/setup
> 
> ```
> npx: installed 1 in 2.349s
> Could not locate the repository for "https://github.com/vercel/next-learn/tree/master/basics/learn-starter". Please check that the repository exists and try again.
> ```
> 
> Instructions say to check https://github.com/vercel/next-learn/blob/master/basics/errors/install.md but there's not much detail there and the commands are a bit different. I followed the text based instructions there (not the specific command) and removed everything past the project name which was then "Successful" but when starting the app it quickly failed for other reasons:
> 
> ```
> Installing dependencies:
> - react
> - react-dom
> - next
> 
> + react@17.0.2
> + react-dom@17.0.2
> + next@12.0.7
> added 243 packages from 223 contributors and audited 255 packages in 44.584s
> found 0 vulnerabilities
> 
> 
> Installing devDependencies:
> - eslint
> - eslint-config-next
> 
> 
> > core-js-pure@3.20.2 postinstall C:\code\nextjs-blog\node_modules\core-js-pure
> > node -e "try{require('./postinstall')}catch(e){}"
> 
> + eslint@8.6.0
> + eslint-config-next@12.0.7
> added 170 packages from 100 contributors and audited 425 packages in 34.247s
> found 0 vulnerabilities
> 
> 
> Initialized a git repository.
> 
> Success! Created nextjs-blog at C:\code\nextjs-blog
> ```
> 
> ```
>  started server on 0.0.0.0:3000, url: http://localhost:3000
> (node:19500) UnhandledPromiseRejectionWarning: ReferenceError: TextEncoder is not defined
>     at C:\code\nextjs-blog\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:67:19
>     at Object.<anonymous> (C:\code\nextjs-blog\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-writer.browser.development.server.js:900:5)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Module.require (internal/modules/cjs/loader.js:637:17)
>     at require (internal/modules/cjs/helpers.js:22:18)
>     at Object.<anonymous> (C:\code\nextjs-blog\node_modules\next\dist\compiled\react-server-dom-webpack\writer.browser.server.js:6:20)
> (node:19500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:19500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
> Error: Not supported
>     at Object.loadConfig [as default] (C:\code\nextjs-blog\node_modules\next\dist\server\config.js:399:74)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! nextjs-blog@ dev: `next dev`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the nextjs-blog@ dev script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> ```

i fix it with just use latest version of nodejs

**Comment by abhaykumarprajpati** [comment]
i have also the same issue but i fix it with just by use latest version of nodejs

**Comment by Adg1** [comment]
In India, you face the same issue if you use JIO network

**Comment by Johnnycapreano** [comment]
hi i am using node js latest version 21.7.3 i  am still facing the same issue when i run  npx create-next-app@latest nextjs-dashboard --use-npm --example "htt
ps://github.com/vercel/next-learn/tree/main/dashboard/starter-example"
i am getting  Could not locate the repository for "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example". Please check that the repository exists and try again.

**Comment by BazzSivan1** [comment]
same

**Comment by NikitaaSharma** [comment]
@BazzSivan1 Try updating your node first
`nvm install node`

and then run
`npx create-next-app@latest nextjs-dashboard --use-npm --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example"`

**Comment by yalinyy** [comment]
您好~我是亚林，已收到您的邮件，会尽快回复~

**Comment by wlfmnstr** [comment]
So it really irritated me that the accepted solution to this was "If you're on some sort of VPN/Proxy, try not being like that" - not an option for me and probably a lot of other people that work at actual companies of scale lol. 

I'm well aware that this is _related_ to my network configuration on my work VPN, but I also know with certainty that I am able to interact with all of the visible urls this npx command _appeared_ to be making requests to.

At the very least, I know the error message that the create-next-app utility was printing out was wrong since it stated: "Could not locate the repository for "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example". Please check that the repository exists and try again." but I can reach that url just fine on my network.

So I dug into the actual create-next-app code that runs when you `npx create-next-app` which you can find [here](https://github.com/vercel/next.js/tree/canary/packages/create-next-app). This brought me to the [`isUrlOK()`](https://github.com/vercel/next.js/blob/a1c5ca6a645024ea0e349a401bcae13b9136f584/packages/create-next-app/helpers/examples.ts#L13) call, as this seemed to be where the falsy value came which leads to the error message that brought us all to this github issue...

Lo and behold, the url it's fetching from to confirm a valid example project url was "https://api.github.com/repos/vercel/next-learn/contents/dashboard/starter-example/package.json?ref=main"... I can already tell you what is going to happen if I paste this into my browser and try it (and so could probably anyone else that works at big enterprises)...

403 - RATE LIMITED 🤦‍♂️
```
{
  "message": "API rate limit exceeded for <my.ip>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"
}
```

After figuring out how to build the monstrosity of javascript build tools and abstractions that is the next.js monorepo, and then figuring out how to get `npx` to use my create-react-app package instead of whatever's hosted on the public (or in my case private) npm registry, I was able to at least log out what the hell `create-react-app` was trying to do to confirm this was the issue. This also let me add my bearer token as a header on the fetch call that's validating this repo's existence and once built, my local version of the create-next-app tool works as expected on network!

The create-next-app utility needs a few things:
1. The error messages are incorrect and should be at minimum modified to include the response text when failing. 
2. Probably needs the ability to pass args to create-next-app that do things like set headers for requests to github api.

**Tl;dr** - Its problems with the `create-next-app` utility, and if you can't change networks to make this work, you'll need to not use create-next-app or customize that tool as I roughly detailed above.

**Comment by yalinyy** [comment]
您好~我是亚林，已收到您的邮件，会尽快回复~

**Comment by mfclarke-cnx** [comment]
Changing to a different network worked for me. Strange because on the network that didn't work I could browse to https://github.com/vercel/next-learn/tree/main/dashboard/starter-example just fine. It was just npx that didn't like it as an example.

The network that didn't work is just regular old home wifi. No firewalls etc.

**Comment by yalinyy** [comment]
您好~我是亚林，已收到您的邮件，会尽快回复~

**Comment by BoTime** [comment]
I had the same error. The following solution worked for me on my Macbook:
1. Install node: `nvm install node`. It installed node v22.9.0. 
1. Install pnpm: `npm install -g pnpm`.

Previously I had node 18 installed. Not doing step 2 above gave me "unable to resolve dependency tree" error.

**Comment by yalinyy** [comment]
您好~我是亚林，已收到您的邮件，会尽快回复~

**Comment by chenyang48671155** [comment]
> npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/main/basics/learn-starter"

Thanks

**Comment by yalinyy** [comment]
您好~我是亚林，已收到您的邮件，会尽快回复~
