### ISSUE TITLE
Chapter 11: Small typo `searchParams` should be `useSearchParams`

### ISSUE THREAD

**Issue by don-esteban** [vercel/next-learn#601]
At the beginning of Chapter 11 you write:

> ### In this chapter...
> 
> Here are the topics we’ll cover
> Learn how to use the Next.js APIs: **`searchParams`**, `usePathname`, and `useRouter`.
> Implement search and pagination using URL search params.

It should be `useSearchParams`.

**Comment by leerob** [comment]
Thank you! Fixing.
