### ISSUE TITLE
cannot find the files under the posts directory

### ISSUE THREAD

**Issue by Veryinheart** [vercel/next-learn#61]
When I follow the steps and complete getStaticProps part: 

I got this error (I changed my real username to "username" in the path below):

Error: ENOENT: no such file or directory, scandir '/Users/username/Desktop/nextjs-blog/posts'

the path is correct and there are two markdown files under the top-level posts directory, but it still got the error

**Comment by nicolevandersluis-cumlaude** [comment]
Hi! I had the same error, what helped me was to add 'pages/' before posts. So it will be 'pages/posts'.

**Comment by Jesse2098** [comment]
im having the same issue and i tried changing the "posts" to "pages/posts" and it is still giving me the error that says--->

Error: ENOENT: no such file or directory,
stuck on what to do next

**Comment by nikitashvetsov21** [comment]
I have the same problem, WTF????

**Comment by nikitashvetsov21** [comment]
![Скриншот 23-12-2022 16 21 39](https://user-images.githubusercontent.com/62443471/209343387-1afc085f-3e82-49e7-97fe-00890529e1e9.png)

**Comment by nikitashvetsov21** [comment]
![Скриншот 23-12-2022 16 28 04](https://user-images.githubusercontent.com/62443471/209343961-7d17bd9e-afe2-4793-9987-f05e8817bd8a.png)

**Comment by nikitashvetsov21** [comment]
![Скриншот 23-12-2022 16 30 08](https://user-images.githubusercontent.com/62443471/209344066-66bc4832-f8f2-4f8a-bead-774f115f0d6c.png)

**Comment by nikitashvetsov21** [comment]
I didn't pass the props correctly 

I returned props without {} in the function


It looked like this: 

export async function getStaticProps({ params }) {
  const postData = await getPostData(params.postWithApiDynamic);

  return {
    props: postData: postData,
}


And we need it like this!

  return {
    props: {
      postData: postData,
    },
  };
}



Thanks for the cool technology, my bad

**Comment by manovotny** [comment]
This is a little difficult to troubleshoot with y'all using just screenshots. Are any of you willing to commit what changes you have to a GitHub repository so we can clone the code and help troubleshoot using the same thing you are?
