### ISSUE TITLE
[app] Invalid URL link at https://nextjs.org/learn/dashboard-app/creating-layouts-and-pages

### ISSUE THREAD

**Issue by devjiwonchoi** [vercel/next-learn#610]
On the sentence:

One benefit of using layouts in Next.js is that on navigation, only the page components update while the layout won't re-render.
This is called [partial rendering](https://nextjs.org/docs/app/building-your-application/routing/linking-and-navigating#3-partial-rendering):

The link should be `#4-partial-rendering`, not `#3-`.

**Comment by leerob** [comment]
Fixing! Thank you.
