### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by MungaiVic** [vercel/next-learn#613]
I had trouble seeding the database then after changing to node version 20, it worked. 
Now I can't fetch data. 

I use nvm.
What could be the issue?

**Comment by Koder2704** [comment]
The to run for populating the database from seed.js isn't working...It throws out nodejs errors.

**Comment by vignxs** [comment]
try running vercel dev instead of npm run dev

that did the magic for me
https://github.com/orgs/vercel/discussions/2350#discussioncomment-5850746

**Comment by leerob** [comment]
Hey there, I am not able to reproduce this. Please open a new issue if you are still having trouble here. Thank you!
