### ISSUE TITLE
Chapter 15 CallbackRouteError, TypeError: "ikm"" must be an instance of Uint8Array or a string

### ISSUE THREAD

**Issue by meifu** [vercel/next-learn#618]
I followed Chapter 15 tutorial and completed the implementation. But after clicking the Sign In button, a error occurred.

<img width="944" alt="截圖 2024-03-08 下午1 44 50" src="https://github.com/vercel/next-learn/assets/1650518/b6b1c061-ac02-4592-8ce7-fc004d0793d0">
<img width="966" alt="截圖 2024-03-08 下午1 45 17" src="https://github.com/vercel/next-learn/assets/1650518/ca6ff3b8-a203-4daf-8dd2-40c48d39aaa2">

---
I had checked that my code is correct and `AUTH_SECRET` value in `.env` is not empty.
Does any one know what this error means? And how can I fix it?
Thank you.

**Comment by ongbt** [comment]
Same issue for me.
