### ISSUE TITLE
Chapter 6 - compile error in vercel deployment

### ISSUE THREAD

**Issue by robinzclark777** [vercel/next-learn#622]
1) How do I fix the following error: Type error: Type 'string' is not assignable to type 'UrlObject | RouteImple<string> in app/ui/dashboard/nav-lins.tsx on line 33.

<img width="592" alt="image" src="https://github.com/vercel/next-learn/assets/34450077/43b479d5-05f5-48bf-8d89-697d50d951e7">

2) When I push new changes to my github project, how do I get those new changes into Vercel?  Do I have to create a new project in Vercel?  

Thank you.

**Comment by leerob** [comment]
Hey there, please check the completed example so you can compare against your current working state 🙏
