### ISSUE TITLE
after Chapter 6, got error when running  dev

### ISSUE THREAD

**Issue by Qinisfighting** [vercel/next-learn#632]
I have reached Chapter 6, app has been deployed without problem and seed script is running without problem. but when try to run app locally again, I got error, the app can not be built locally anymore, the error looks like this:

PS C:\Users\User\OneDrive\Dokumente\GitHub\financial-dashboard\nextjs-dashboard> npm run dev

> dev
> next dev

   ▲ Next.js 14.0.2
   - Local:        http://localhost:3000
   - Environments: .env

[Error: EINVAL: invalid argument, readlink 'C:\Users\User\OneDrive\Dokumente\GitHub\financial-dashboard\nextjs-dashboard\.next\static\media\05a31a2ca4975f99-s.woff2'] {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'readlink',
  path: 'C:\\Users\\User\\OneDrive\\Dokumente\\GitHub\\financial-dashboard\\nextjs-dashboard\\.next\\static\\media\\05a31a2ca4975f99-s.woff2'
}

where is the problem?

**Comment by Qinisfighting** [comment]
fixed

**Comment by vignxs** [comment]
Try running vercel dev see if that helps

**Comment by Qinisfighting** [comment]
> Try running vercel dev see if that helps

it did help;-D, thank you!
