### ISSUE TITLE
Chapter 15: Credentials Error

### ISSUE THREAD

**Issue by sabaoongfx** [vercel/next-learn#651]
I have written the code for the auth but I am still getting invalid credentials error.
![image](https://github.com/vercel/next-learn/assets/165472223/ff7e3616-bbc3-4b9d-8203-7c7ecd7df006)

**Comment by wade-liwei** [comment]
Do you want to use  github login ?

**Comment by sabaoongfx** [comment]
I entered the password and email from tutorial and it is not accepting

**Comment by wade-liwei** [comment]
You can try the final example;
https://github.com/vercel/next-learn/tree/main/dashboard/final-example

**Comment by delbaoliveira** [comment]
Thank you @wade-liwei 🙏🏼 

@sabaoongfx just as an FYI, we're removing NextAuth from the learn course as we have found that it can be overwhelming for beginners. If you'd like to learn more about auth, I've written a guide that goes through the principles of auth and what Next.js features to use, including guides from popular auth libraries: https://nextjs.org/docs/app/building-your-application/authentication

You should be able to skip the auth chapter as it's independent from the rest of the course.

**Comment by liuxin2361** [comment]
I think that the secret key generated by openssl during the exercise is different from the password stored in the database, so the password entered on the page is inconsistent with the password in the database, and cannot log in.
