### ISSUE TITLE
Could you please add GithubProvider in the next-learn?

### ISSUE THREAD

**Issue by wade-liwei** [vercel/next-learn#653]
I am a frontend beginner, and I need the login with GithubProvider.
but in the example links(https://github.com/nextauthjs/next-auth-example), add  auth method does not likes in the next-learn project.

**Comment by delbaoliveira** [comment]
Hey @wade-liwei, thank you for the feedback. 

Not sure if you have seen this already, but the new Auth.js docs has a page for the Github Provider: https://authjs.dev/getting-started/providers/github

Just as an FYI, we're removing NextAuth from the learn course as we have found that it can be overwhelming for beginners. If you'd like to learn more about auth, I've written a guide that goes through the principles of auth and what Next.js features to use, including guides from popular auth libraries: https://nextjs.org/docs/app/building-your-application/authentication
