### ISSUE TITLE
chapter 15: missing 'use server' directive in example

### ISSUE THREAD

**Issue by wrongbyte** [vercel/next-learn#656]
## Problem
In the [Updating login form](https://github.com/nextauthjs/next-auth/issues/9192) step, the action needs to have the `'use server'` directive in the beginning of the file. 
This is contained in the [source code](https://github.com/vercel/next-learn/blob/main/dashboard/final-example/app/lib/actions.ts#L1), however the tutorial page does not contain this line. It has led to people getting problems when following the tutorial, as [this issue](https://github.com/nextauthjs/next-auth/issues/9192) exemplifies. 

As the curriculum is currently not open sourced, we cannot edit the examples contained in the tutorial, so I am opening this issue.

**Comment by leerob** [comment]
Hey there, I cannot reproduce this. Could you be more specific where the issue is? There is a `"use server"` directive inlined in the function.
