### ISSUE TITLE
Chapter 15 - env-url-basepath-redundant

### ISSUE THREAD

**Issue by gilz93** [vercel/next-learn#657]
Followed the course code up to and including chapter 15.
Seeing the following warning in terminal:
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant

Any idea how to fix this?

(I'm running on a windows machine)

**Comment by delbaoliveira** [comment]
Hey @gilz93, sorry to hear that you ran into this error. Would you be able to share your code? 

Just as an FYI, we're removing NextAuth from the learn course as we have found that it can be overwhelming for beginners. If you'd like to learn more about auth, I've written a guide that goes through the principles of auth (without using an auth library), and includes Next.js guides from popular auth libraries. 

https://nextjs.org/docs/app/building-your-application/authentication

**Comment by gilz93** [comment]
Thanks @delbaoliveira, I've shared the code with you.
For what it's worth, I think it's great that you have a chapter about AUTH in the course, but perhaps it needs to be rewritten, split into two chapters - with more basic, step-by-step thorough explanations - fit for beginners - just as was done with the rest of the course. Overall, a great course.

**Comment by dexhowl** [comment]
@gilz93 - I just ran into the same problem today. 

I completely removed this line from my .env file.  
`AUTH_URL=http://localhost:3000/api/auth `

The warning is gone and everything still works after restarting the server. 

According to Auth.js - [Environment Variables](https://authjs.dev/getting-started/deployment#auth_url)
>**AUTH_URL**
>This environment variable is mostly unnecessary with v5 as the host is inferred from the request headers....

@delbaoliveira - I would agree that AUTH in general can be overwhelming but I would posit that there aren't many web applications out there that don't require it's use at this point and introducing it to potentially new Next users at the outset of their journey through this course is awesome. I'm confident there's a way to break it down a bit more. 

Maybe include the AUTH implementation in the template so the user doesn't have to add it but walk-through what's happening in the code in steps after the login button is clicked. The users that care will appreciate it and those that don't can skip it without changing the end product.

**Comment by gilz93** [comment]
@dexhowl - thanks! that fixed it. (for some reason commenting out the line wasn't enough the first-time round, or maybe it was the fact that I now exited and rerun the app and browser that made it work this time).

**Comment by delbaoliveira** [comment]
Hey @gilz93, glad it's working now 🎉 

>  I think it's great that you have a chapter about AUTH in the course, but perhaps it needs to be rewritten, split into two chapters 

 
And yes, I think there's opportunity for it in the future. I think the trick is balancing an OSS project that everyone can use vs. your own implementation without sacrificing getting too complex. 

I'll keep thinking about it 🙏🏼
