### ISSUE TITLE
tree/master/dynamic-routes-starter this url is null

### ISSUE THREAD

**Issue by weiyi88** [vercel/next-learn#668]
```
npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/dynamic-routes-starter"

```

with this code , it will show the error 
`
 Could not locate the repository for "https://github.com/vercel/next-learn-starter/tree/master/dynamic-routes-starter". Please check that the repository exists and try again.
`

please fix the bug of doc 
 [by this url ](https://www.nextjs.cn/learn/basics/dynamic-routes/setup)

**Comment by leerob** [comment]
Hey there, we don't control that forked version of the site. But here is the right URL: https://github.com/vercel/next-learn/tree/main/basics/dynamic-routes-starter
