### ISSUE TITLE
Docs: Minor syntax error in the streaming doc

### ISSUE THREAD

**Issue by aykutkardas** [vercel/next-learn#673]
### What is the update you wish to see?

I noticed minor thing in the document.

Expected:
```js
const revenue = await fetchRevenue() // delete this line
```
<img width="1014" alt="image" src="https://github.com/vercel/next.js/assets/7966133/794d77ea-a27f-45a4-9c0f-b57177d84795">

### Is there any context that might help us understand?

no

### Does the docs page already exist? Please link to it.

https://nextjs.org/learn/dashboard-app/streaming#streaming-a-component

**Comment by GaneshSrambikal** [comment]
Hello,
What you want to point out is that in line 8:
`const revenue = await fetchRevenue // delete this line`

**Which should be**

`const revenue = await fetchRevenue() // delete this line`

In my opinion, although we are removing the `const revenue = await fetchRevenue()` from _/app/dashboard/(overview)/page.tsx_

and fetching it in _/app/ui/dashboard/revenue-chart.tsx_ , 

Agreeing that this is a minor syntax error but understandable as we are removing it from the code.

**Comment by leerob** [comment]
Fixed! Thank you.
