### ISSUE TITLE
Chapter 6: Create Postgre SQL database error

### ISSUE THREAD

**Issue by ldemu** [vercel/next-learn#675]
When i tried to create database Postegre SQL on Chapter 6, i have this error:
"Failed to acknowledge terms of service for storage"
![capture1](https://github.com/vercel/next-learn/assets/93992253/4e4e383f-3335-4288-962a-7b666bb85a50)

**Comment by leerob** [comment]
I cannot reproduce this, please let me know if you are still seeing it!
