### ISSUE TITLE
'RevenueChart' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by foysalremon** [vercel/next-learn#685]
Using the example. After fetching `revenue` and uncommenting `<RevenueChart revenue={revenue}/>` on `dashboard/page.tsx` getting error:

'RevenueChart' cannot be used as a JSX component.
  Its return type 'Promise<Element>' is not a valid JSX element.
    Type 'Promise<Element>' is missing the following properties from type 'ReactElement<any, any>': type, props, key

**Comment by leerob** [comment]
Please ensure you have all of your dependencies installed – then try restarting your TS server inside of your editor if you are still seeing this.
