### ISSUE TITLE
docs: error example url

### ISSUE THREAD

**Issue by LinkSofuny** [vercel/next-learn#69]
need to update here

https://www.nextjs.cn/learn/basics/create-nextjs-app/setup

![image](https://user-images.githubusercontent.com/69881455/157849428-8abf27ea-7dff-4d1c-b4ee-f9267cd789c3.png)
```
npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"
```
**to**
```
npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"
```
what can I do ??

**Comment by karainsun** [comment]
https://github.com/vercel/next-learn/tree/master/basics/learn-starter

**Comment by leerob** [comment]
This has been fixed, thank you!
