### ISSUE TITLE
Chapter 13:Why is the exception thrown outside the try block in the deleteInvoice function caught by the catch block?

### ISSUE THREAD

**Issue by dododcdc** [vercel/next-learn#721]
I believe that catch is meant to capture errors within the try block. However, when I tried to throw an exception inside the try block, it did not lead to the error page as I expected. I'm a bit puzzled by this. I'm not a professional front-end developer, and I hope someone who comes across this can help clarify my confusion.

**Comment by dododcdc** [comment]
file: nextjs-dashboard/app/lib/actions.ts  ,function: deleteInvoice

**Comment by GaneshSrambikal** [comment]
> I believe that catch is meant to capture errors within the try block. However, when I tried to throw an exception inside the try block, it did not lead to the error page as I expected. I'm a bit puzzled by this. I'm not a professional front-end developer, and I hope someone who comes across this can help clarify my confusion.

Hello,
Your code should look like this after you have followed the instructions to add `throw new Error('Failed to Delete Invoice)` in the delete function in the `action.tsx` file.

![next_learn_chp_14_deletefn_01](https://github.com/vercel/next-learn/assets/33309469/79212156-37f9-4103-b260-4936aca25356)

### But

That line of code `throw new Error('Failed to Delete Invoice')`  only shows you how the exceptions are handled and executed. Also, your `try-catch` block becomes an unreachable code block if you keep the code throughout the chapter/tutorial.
 
So it is better to comment out the line `throw new Error('Failed to Delete Invoice')`  as shown below.

![next_learn_chp_14_deletefn_02](https://github.com/vercel/next-learn/assets/33309469/ee2905a8-147e-40cb-8a03-ac02ce52e097)

You can find more details on try-catch [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch)

 Thank you.

**Comment by dododcdc** [comment]
> try-catch

ok, Thank you .
