### ISSUE TITLE
issue with npm run seed

### ISSUE THREAD

**Issue by Boby900** [vercel/next-learn#725]
Unable to use the cmd `npm run seed` stating that ` Cannot find module 'C:\Users\win 10\Desktop\yogurt\scripts\seed.js'`
I am following along with this article [Setting Up Your Database](https://nextjs.org/learn/dashboard-app/setting-up-your-database)
Also I don't have any `scripts` folder in my project after running the cmd `npm i @vercel/postgres`

[my repo](https://github.com/Boby900/yogurt)

**_Any help would be highly appreciated_**
![Screenshot (476)](https://github.com/vercel/next-learn/assets/111265239/92acd780-6953-488d-85a4-b5252317a436)

**Comment by dododcdc** [comment]
https://github.com/vercel/next-learn/tree/main/dashboard/starter-example/scripts ，and you can read chapter 6：https://nextjs.org/learn/dashboard-app/setting-up-your-database

**Comment by Boby900** [comment]
> https://github.com/vercel/next-learn/tree/main/dashboard/starter-example/scripts ，and you can read chapter 6：https://nextjs.org/learn/dashboard-app/setting-up-your-database

okay, so I should manually add the folder `scripts` and `seed.js `file as given in the starter-example?
Thanks for helping me

**Comment by dododcdc** [comment]
> > https://github.com/vercel/next-learn/tree/main/dashboard/starter-example/scripts ，and you can read chapter 6：https://nextjs.org/learn/dashboard-app/setting-up-your-database
> 
> okay, so I should manually add the folder `scripts` and `seed.js `file as given in the starter-example? Thanks for helping me

yes，I did it this way.

**Comment by Boby900** [comment]
> > > https://github.com/vercel/next-learn/tree/main/dashboard/starter-example/scripts ，and you can read chapter 6：https://nextjs.org/learn/dashboard-app/setting-up-your-database
> > 
> > 
> > okay, so I should manually add the folder `scripts` and `seed.js `file as given in the starter-example? Thanks for helping me
> 
> yes，I did it this way.

okay, I will add that manually then
