### ISSUE TITLE
Chapter 14: Fixing grammar in Client Side Validation example

### ISSUE THREAD

**Issue by GaneshSrambikal** [vercel/next-learn#730]
In the Form validation section, after the client-side validation example code which demonstrates to add *required*

![next_learn_chp_14](https://github.com/vercel/next-learn/assets/33309469/feeb44ed-2a99-40d4-b43b-c550c57d7609)

this single sentence needs a grammar fix:
**Submit the form again, and you should now see the browser a warning if you try to submit a form with empty values.**

### proposed lines:

1. _Submit the form again, and you should now see that the browser throws a warning if you try to submit a form with empty values._
2. _Submit the form again, and you should now see the browser gives a warning if you try to submit a form with empty values._
3. (more specific) _Submit the form again, and you should now see a warning adjacent to the amount field if you try to submit a form with empty values._

**Comment by leerob** [comment]
Thanks, will push a fix!
