### ISSUE TITLE
Chapter 13: No instructions to remove/comment throw new Error example

### ISSUE THREAD

**Issue by GaneshSrambikal** [vercel/next-learn#731]
In the try-catch example, it is instructed to throw an error earlier. `throw new Error('Failed to Delete Invoice');`

![next_learn_chp_13_throw_err](https://github.com/vercel/next-learn/assets/33309469/045b2258-0979-4a01-8624-b7d628699b9c)

After that, there is no clear instruction to remove or comment out the line of code. Which may confuse some learners. As someone has mentioned here #721 

Purposed solution:
instructions to remove or comment out the `throw new Error('Failed to Delete Invoice');` line of code before moving on to the next section.

Thank You.

**Comment by leerob** [comment]
Thank you, I will add this now.

**Comment by AdrianJMartin** [comment]
The instruction to remove the throw(....) is bit too soon as it required in the next section()
