### ISSUE TITLE
Chapter 11: Error: Route /dashboard/invoices/ with `dynamic = "error"` couldn't be rendered statically because it used `searchParams.query`.

### ISSUE THREAD

**Issue by ryanfincham** [vercel/next-learn#739]
This error is thrown after Step #2: https://nextjs.org/learn/dashboard-app/adding-search-and-pagination#2-update-the-url-with-the-search-params. 
I have been trying to debug this for 2 days now. Any insight is appreciated.

app\ui\search.tsx
```
'use client';

import { MagnifyingGlassIcon } from '@heroicons/react/24/outline';
import { usePathname, useRouter, useSearchParams } from 'next/navigation';

export default function Search({ placeholder }: { placeholder: string }) {
const searchParams = useSearchParams();
const { replace } = useRouter();
const pathname = usePathname();

function handleSearch(term: string) {


const params = new URLSearchParams(searchParams);

params.set('page', '1');

if (term) {
  params.set('query', term);
} else {
  params.delete('query');
}
replace(`${pathname}?${params.toString()}`);
};

  return (
    <div className="relative flex flex-1 flex-shrink-0">
      <label htmlFor="search" className="sr-only">
        Search
      </label>
      <input
        className="peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500"
        placeholder= {placeholder}
        onChange={(e) => {
          handleSearch(e.target.value);
        }}
        defaultValue={searchParams.get('query')?.toString()}
      />
      <MagnifyingGlassIcon className="absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900" />
    </div>
  );
}

```
app\dashboard\invoices\page.tsx
```
import Pagination from 'app/ui/invoices/pagination';
import Search from 'app/ui/search';
import Table from 'app/ui/invoices/table';
import { CreateInvoice } from 'app/ui/invoices/buttons';
import { lusitana } from 'app/ui/fonts';
import { InvoicesTableSkeleton } from 'app/ui/skeletons';
import { Suspense } from 'react';

export default async function Page({
  searchParams,
}: {
  searchParams?: { query?: string; page?: string };
}) {
  console.log(searchParams);
  const query = searchParams?.query || '';
  const currentPage = Number(searchParams?.page) || 1;

  return (
    <div className="w-full">
      <div className="flex w-full items-center justify-between">
        <h1 className={`${lusitana.className} text-2xl`}>Invoices</h1>
      </div>
      <div className="mt-4 flex items-center justify-between gap-2 md:mt-8">
        <Search placeholder="Search invoices..." />
        <CreateInvoice />
      </div>
      <Suspense key={query + currentPage} fallback={<InvoicesTableSkeleton />}>
        <Table query={query} currentPage={currentPage} />
      </Suspense>
      <div className="mt-5 flex w-full justify-center">
        {/* <Pagination totalPages={totalPages} /> */}
      </div>
    </div>
  );
}
```
Terminal Error:
✓ Compiled in 3s (1125 modules)
 GET /dashboard/invoices/ 200 in 1832ms
 GET /dashboard/invoices/?query=adfasfsdfd 200 in 1614ms
{}
{}
 ⨯ Error: Route /dashboard/invoices/ with `dynamic = "error"` couldn't be rendered statically because it used `searchParams.query`. See more info here: https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic#dynamic-rendering
    at Page (./app/dashboard/invoices/page.tsx:23:31)
    at stringify (<anonymous>)
digest: "556017065"
 ⨯ Error: Route /dashboard/invoices/ with `dynamic = "error"` couldn't be rendered statically because it used `searchParams.query`. See more info here: https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic#dynamic-rendering
    at Page (./app/dashboard/invoices/page.tsx:23:31)
    at stringify (<anonymous>)
digest: "556017065"
 ⨯ Error: Route /dashboard/invoices/ with `dynamic = "error"` couldn't be rendered statically because it used `searchParams.query`. See more info here: https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic#dynamic-rendering
    at Page (./app/dashboard/invoices/page.tsx:23:31)
    at stringify (<anonymous>)
digest: "556017065"
 ⨯ Error: Route /dashboard/invoices/ with `dynamic = "error"` couldn't be rendered statically because it used `searchParams.query`. See more info here: https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic#dynamic-rendering
    at Page (./app/dashboard/invoices/page.tsx:23:31)
    at stringify (<anonymous>)
digest: "556017065"
{}
 ⨯ Error: Route /dashboard/invoices/ with `dynamic = "error"` couldn't be rendered statically because it used `searchParams.query`. See more info here: https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic#dynamic-rendering
    at Page (./app/dashboard/invoices/page.tsx:23:31)
    at stringify (<anonymous>)
digest: "556017065"
 ⨯ Error: Route /dashboard/invoices/ with `dynamic = "error"` couldn't be rendered statically because it used `searchParams.query`. See more info here: https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic#dynamic-rendering
    at Page (./app/dashboard/invoices/page.tsx:23:31)
    at stringify (<anonymous>)
digest: "556017065"
{}
 ⨯ Error: Route /dashboard/invoices/ with `dynamic = "error"` couldn't be rendered statically because it used `searchParams.query`. See more info here: https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic#dynamic-rendering
    at Page (./app/dashboard/invoices/page.tsx:23:31)
    at stringify (<anonymous>)
digest: "556017065"
 ⨯ Error: Route /dashboard/invoices/ with `dynamic = "error"` couldn't be rendered statically because it used `searchParams.query`. See more info here: https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic#dynamic-rendering
    at Page (./app/dashboard/invoices/page.tsx:23:31)
    at stringify (<anonymous>)
digest: "556017065"
 GET /dashboard/invoices/ 500 in 680ms
 GET /dashboard/invoices/?query=adfasfsdfd 500 in 249ms

http://[localhost:3000/dashboard/invoices/?query=adfasfsdfd](http://localhost:3000/dashboard/invoices/?query=adfasfsdfd) Error:
Unhandled Runtime Error
Error: Route /dashboard/invoices/ with `dynamic = "error"` couldn't be rendered statically because it used `searchParams.query`. See more info here: https://nextjs.org/docs/app/building-your-application/rendering/static-and-dynamic#dynamic-rendering

Source
Next.js
trackDynamicDataAccessed
node_modules\next\dist\server\app-render\dynamic-rendering.js (115:1)
store
../src/client/components/search-params.ts
```
app\dashboard\invoices\page.tsx (15:17) @ searchParams

  13 | }) {
  14 |   console.log(searchParams);
> 15 |   const query = searchParams?.query || '';
     |                 ^
  16 |   const currentPage = Number(searchParams?.page) || 1;
  17 |
  18 |   return (
```

**Comment by sourabhjain6665** [comment]
import Pagination from '@/app/ui/invoices/pagination';
import Search from '@/app/ui/search';
import Table from '@/app/ui/invoices/table';
import { CreateInvoice } from '@/app/ui/invoices/buttons';
import { lusitana } from '@/app/ui/fonts';import { InvoicesTableSkeleton } from '@/app/ui/skeletons';
import { Suspense } from 'react';

export default async function Page({
  searchParams,
}: {
  searchParams?: { query?: string; page?: string };
}) {
  console.log(searchParams);
  const query = searchParams?.query || '';
  const currentPage = Number(searchParams?.page) || 1;

  return (
    <div className="w-full">
      <div className="flex w-full items-center justify-between">
        <h1 className={`${lusitana.className} text-2xl`}>Invoices</h1>
      </div>
      <div className="mt-4 flex items-center justify-between gap-2 md:mt-8">
        <Search placeholder="Search invoices..." />
        <CreateInvoice />
      </div>
      <Suspense key={query + currentPage} fallback={<InvoicesTableSkeleton />}>
        <Table query={query} currentPage={currentPage} />
      </Suspense>
      <div className="mt-5 flex w-full justify-center">
        {/* <Pagination totalPages={totalPages} /> */}
      </div>
    </div>
  );
}

Try this - It should work for you

**Comment by ryanfincham** [comment]
Thank you for the comment. Your code is correct. However, I ultimately had to delete an extra path that I had added in my tsconfig.json file. I had added it to do some experimentation for multiple app folders. After going through each file and fixing the import paths, my invoice page is now working as expected.
