### ISSUE TITLE
Chapter 1: install failed

### ISSUE THREAD

**Issue by vvnab** [vercel/next-learn#747]
```sh
npx create-next-app@latest nextjs-dashboard --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example"
```

# npm resolution error report

While resolving: undefined@undefined
Found: react@19.0.0-rc-6230622a1a-20240610
node_modules/react
  react@"19.0.0-rc-6230622a1a-20240610" from the root project

Could not resolve dependency:
peer react@">= 16" from @heroicons/react@2.1.3
node_modules/@heroicons/react
  @heroicons/react@"^2.0.18" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

**Comment by chengfengfengwang** [comment]
learn nextjs from error...

**Comment by chengfengfengwang** [comment]
git clone https://github.com/vercel/next-learn/tree/main
cd dashboard/starter-example
pnpm i
pnpm run dev

**Comment by soobing** [comment]
The issue can be resolved by upgrading the Node.js version to 18.17.0 or higher.

I had the same error. Since the project was downloaded, I tried installing the npm packages with yarn, but I encountered the following error.
```bash
➜  nextjs-dashboard yarn
yarn install v1.22.19
info No lockfile found.
[1/5] 🔍  Validating package.json...
error @: The engine "node" is incompatible with this module. Expected version ">=18.17.0". Got "18.16.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
This made me realize there was an issue with the Node.js version. After changing the Node.js version to 20 and reinstalling, the error no longer occurred.

Additionally, the .nvmrc file in this project should be updated to specify the exact version of Node.js required.

**Comment by arjunhamdalah** [comment]
Gave up using npm just use bun instead
```
bun install v1.1.13 (bd6a6051)
warn: incorrect peer dependency "react@19.0.0-rc-6230622a1a-20240610"

warn: incorrect peer dependency "react-dom@19.0.0-rc-6230622a1a-20240610"

warn: incorrect peer dependency "react@19.0.0-rc-6230622a1a-20240610"

+ @types/bcrypt@5.0.2
+ @types/react@18.2.21 (v18.3.3 available)
+ @types/react-dom@18.2.14 (v18.3.0 available)
+ @vercel/style-guide@5.2.0 (v6.0.0 available)
+ dotenv@16.4.5
+ eslint@8.57.0 (v9.4.0 available)
+ eslint-config-next@15.0.0-rc.0
+ eslint-config-prettier@9.0.0 (v9.1.0 available)
+ prettier@3.3.2
+ prettier-plugin-tailwindcss@0.5.4 (v0.6.3 available)
+ @heroicons/react@2.1.3
+ @tailwindcss/forms@0.5.7
+ @types/node@20.5.7 (v20.14.2 available)
+ @vercel/postgres@0.5.1 (v0.8.0 available)
+ autoprefixer@10.4.15 (v10.4.19 available)
+ bcrypt@5.1.1
+ clsx@2.1.1
+ next@15.0.0-rc.0
+ postcss@8.4.31 (v8.4.38 available)
+ react@19.0.0-rc-6230622a1a-20240610
+ react-dom@19.0.0-rc-6230622a1a-20240610
+ tailwindcss@3.3.3 (v3.4.4 available)
+ typescript@5.2.2 (v5.4.5 available)
+ zod@3.23.8

537 packages installed [42.82s]
```

**Comment by F-Joubert** [comment]
This was just my personal preference, but if you don't want access to the final-example while learning:

1. Create/navigate the directory you want to clone into.
2. Clone the repo but don't checkout.
```bash
git clone --filter=blob:none --no-checkout https://github.com/vercel/next-learn
```
3. Navigate to the cloned but empty repo
```bash
cd next-learn/
```
4.  Create a sparse checkout. 
```bash
git sparse-checkout set --cone
```
5. Select the main branch.
```bash
git checkout main
```
6. Clone just the starter-example directory.
```bash
git sparse-checkout set dashboard/starter-example
```
7. Rejoin quecosita's instructions above and update your /dashboard/starter-example/.nvmrc to your current version of node, followed by running `pnpm i`  & `pnpm dev`

**Comment by AB-xdev** [comment]
Maybe it would be a great idea - for the future - to not commit release candidate versions to the default branch that is used in production... or at least check if it still works then...

My workaround:
[Download](https://github.com/vercel/next-learn/archive/b7a4366f682163a6643416c9cdf2d9c43d0fc542.zip) or checkout commit https://github.com/vercel/next-learn/commit/b7a4366f682163a6643416c9cdf2d9c43d0fc542 which is the commit before it broke.

**Comment by togume** [comment]
@AB-xdev 100%. It's bad for NextJS to have potential users become frustrated and have a poor experience because of "broken production."  The team at NextJS is very strong, and releasing something half baked shouldn't happen. I send people here often, and just this week I was going through the tutorial myself, to be blocked at square 0.

cc. @rauchg @delbaoliveira

**Comment by Mugenhub-io** [comment]
Worked for me
 - Install pnpm from https://pnpm.io/installation
 - git clone https://github.com/vercel/next-learn
 - cd to starter-example folder
 - pnpm i
 - pnpm dev
 
![3](https://github.com/vercel/next-learn/assets/172862524/901199e2-85bf-4bc4-a565-5bd7bc9b67c8)

cc: [QUECOSITA](https://github.com/QUECOSITA)

**Comment by togume** [comment]
> Worked for me
> 
> * Install pnpm from https://pnpm.io/installation
> * git clone https://github.com/vercel/next-learn
> * cd to starter-example folder
> * pnpm i
> * pnpm dev
> 
> ![3](https://private-user-images.githubusercontent.com/172862524/339937940-901199e2-85bf-4bc4-a565-5bd7bc9b67c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NTEzMzUsIm5iZiI6MTcxODQ1MTAzNSwicGF0aCI6Ii8xNzI4NjI1MjQvMzM5OTM3OTQwLTkwMTE5OWUyLTg1YmYtNGJjNC1hNTY1LTViZDdiYzliNjdjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQxMTMwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODI5OTc0ZmE2NGYxZWFjZmEyM2VmMWVkNzQ2ZjZiZWMyYjgxYmI5OTU4MmEwMjIxODk3MGY5NWY5ZGQxNDdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kdPZ8QFZG-9sC_ilPaSlcXzNIrODm48UrX34sJdYzaI)
> 
> cc: [QUECOSITA](https://github.com/QUECOSITA)

Yes, it's now fixed.

**Comment by blindjedi** [comment]
Getting this error as well. This problem looks to be created from the recent code merged 
https://github.com/vercel/next-learn/pull/743/files

@delbaoliveira @leerob

**Comment by togume** [comment]
@blindjedi I had to learn Corepack & pnpm to get things running; `corepack enable pnpm`, etc. It should be made clear that `pnpm` is a hard requirement for this to work, which likely throws a lot of us used to other package managers.

**Comment by leerob** [comment]
You don't _need_ corepack, but we believe `pnpm` is a better default so we've updated guidance to start here.

**Comment by AswinBehera** [comment]
> Worked for me
> 
> * Install pnpm from https://pnpm.io/installation
> * git clone https://github.com/vercel/next-learn
> * cd to starter-example folder
> * pnpm i
> * pnpm dev

The above worked for me, but I am getting a big arrow (heroicon arrow), that I think may have been supposed to be besides log in. 
<img width="1728" alt="Screenshot 2024-06-16 at 11 12 17 PM" src="https://github.com/vercel/next-learn/assets/20343007/3217fb25-3246-4f0d-b2f6-7e3cbf3652c2">

**Comment by dolgachio** [comment]
I am not sure is it a right way of handling it, but after getting this error during installation, I went to the `nextjs-dashboard` folder, in  the `package.json` file I changed back dependencies updated in this commit `https://github.com/vercel/next-learn/pull/743/files` to:
```
    "next": "^14.0.2",  
    "react": "18.2.0",
    "react-dom": "18.2.0",
```
And everything worked as expected after that. It is not an ideal solution, but it unblocked me.

PS 
- I didn't install PNPM, I am using regular NPM.
- To fix the broken UI I imported global styles as it is described here https://nextjs.org/learn/dashboard-app/css-styling

**Comment by leotaozeng** [comment]
```bash
pnpm install
pnpm dev
```

pnpm fixed the installation failed issue, but I received warnings issues with peer dependencies found:

![Screenshot 2024-06-17 at 10 40 34 AM](https://github.com/vercel/next-learn/assets/12603244/e9d863ea-c76a-4b74-8d41-c8a76fe3ec71)

**Comment by benceruleanlu** [comment]
> Getting this error as well. This problem looks to be created from the recent code merged https://github.com/vercel/next-learn/pull/743/files

The problem seems to be a react version mismatch.

The `@heroicons/react` package expects a react version greater than or equal to version 16, but the latest commit (58f9a68c6a2a0050976e52969b0dcf427281610a) [specified an install](https://github.com/vercel/next-learn/commit/58f9a68c6a2a0050976e52969b0dcf427281610a#diff-adfc876bcde926729e875197ca02e1c8576f40f0712e6cf8d5312cfef5533332R20) of react version `19.0.0-rc-6230622a1a-20240610`.

According to the [semantic versioning documentation](https://github.com/npm/node-semver?tab=readme-ov-file#prerelease-tags), the prerelease candidate tag `-rc` makes it so that the installed version of react would not satisfy `@heroicons/react`'s react version requirement of `>=16`, despite it technically being a more recent version.

```
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: undefined@undefined
npm error Found: react@19.0.0-rc-6230622a1a-20240610
npm error node_modules/react
npm error   react@"19.0.0-rc-6230622a1a-20240610" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@">= 16" from @heroicons/react@2.1.3
npm error node_modules/@heroicons/react
npm error   @heroicons/react@"^2.0.18" from the root project
```

**Comment by IgorAugust0** [comment]
> Worked for me
> 
> * Install pnpm from https://pnpm.io/installation
> * git clone https://github.com/vercel/next-learn
> * cd to starter-example folder
> * pnpm i
> * pnpm dev
> 

> cc: [QUECOSITA](https://github.com/QUECOSITA)

Alternatively, you can just replace `npx` from the original command with `pnpm dlx`, instead of cloning the repo:

`pnpm dlx create-next-app@latest nextjs-dashboard --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example"`

Worked just fine for me, with no warnings whatsoever:

![image](https://github.com/vercel/next-learn/assets/79866605/08125d63-0f6d-4074-8f80-431ec9a93b5b)

**Comment by manojbhandi** [comment]
--legacy-peer-deps worked for me
![image](https://github.com/vercel/next-learn/assets/97438009/42a25dc8-869c-491f-ad5a-2407885fc474)

**Comment by sanwinmaung** [comment]
> From last commit 11 jun 2024 [Delba de Oliveira](https://github.com/delbaoliveira) changed package.json:
> 
> ```
> "next": "^14.0.2"               to     "next": "15.0.0-rc.0"
> "react": "18.2.0"                to      "react": "19.0.0-rc-6230622a1a-20240610",
> "react-dom": "18.2.0"       to       "react-dom": "19.0.0-rc-6230622a1a-20240610"
> ```
> 
> besides, she changed from npx package manager to pnpm package manager.
> 
> ### **So the solution that worked for me was:**
> 1. Install pnpm from https://pnpm.io/installation
>    (If you are in Windows, after intalling remember to log out and log in again so windows path var gets pnpm to work).
> 2. Clone from Github
> 
> git clone https://github.com/vercel/next-learn
> 
> 3. Update your node version, mine is v22.3.0
> 4. In /next-learn/dashboard/starter-example/  edit the file .nvmrc and replace the number to your actual node version.
> 5. Finally, in power shell or command shell install it with:
> 
> pnpm i
> 
> pnpm dev
> 
> ![Sin título](https://private-user-images.githubusercontent.com/165182744/339125550-340e5057-1fbe-4db3-9a67-ed49f6ed2bbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODM2MzEsIm5iZiI6MTcxODc4MzMzMSwicGF0aCI6Ii8xNjUxODI3NDQvMzM5MTI1NTUwLTM0MGU1MDU3LTFmYmUtNGRiMy05YTY3LWVkNDlmNmVkMmJiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwNzQ4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OGMzY2RiYjkyYzUyYWFiMmE2ODY3OWI0YTMxY2E4NDM4MGZlNmNkMDhhNDI5OWE3YzMxYjAxNjAzNmY0NDU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.aoxeH5s2U1st83x0Yk9AdKlBMI5UstUfzWTZMIsH9Mc)
> 
> Remember to install it in In /next-learn/dashboard/starter-example/
> 
> **There you go! Happy learnning :D**

Thank you! I'm ok using pnpm 💯

**Comment by gercamjr** [comment]
Does using pnpm resolve the issue with importing useActionState hook from react@rc ? 

I can run the project as normal after cloning it, but in Chapter 14 of the Learn Next tutorial, it implements this hook which happens to be only available in React Canary and Experimental versions. I get the same error reported in this ticket when trying to update React, React-Dom and Next to the bleeding edge versions just to have access to this hook. Anybody have a workaround?

**Comment by mrerdem** [comment]
I'm writing to provide an alternative solution and to hopefully remind the devs for an urgent solution. Take my suggestion below with a kilo of salt as I opened next.js website to learn it but here I am trying to fix things before learning starts.

`git clone https://github.com/vercel/next-learn.git
cd next-learn
git reset --hard b7a4366
cd dashboard/starter-example
npm i
npm run dev`

**Comment by leerob** [comment]
https://github.com/vercel/next-learn/issues/754#issuecomment-2185323453
