### ISSUE TITLE
Dependency conflict when setting up the Next.js application from example (Dashboard)

### ISSUE THREAD

**Issue by yigitokar** [vercel/next-learn#754]
npx create-next-app@latest nextjs-dashboard --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example"
Creating a new Next.js app in /Users/yigitokar/nextjs-dashboard.

Downloading files from repo https://github.com/vercel/next-learn/tree/main/dashboard/starter-example. This might take a moment.

Installing packages. This might take a couple of minutes.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@19.0.0-rc-6230622a1a-20240610
npm ERR! node_modules/react
npm ERR!   react@"19.0.0-rc-6230622a1a-20240610" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 16" from @heroicons/react@2.1.4
npm ERR! node_modules/@heroicons/react
npm ERR!   @heroicons/react@"^2.0.18" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/yigitokar/.npm/_logs/2024-06-19T11_10_36_191Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/yigitokar/.npm/_logs/2024-06-19T11_10_36_191Z-debug-0.log

Aborting installation.
  npm install has failed.

**Comment by triggerAustin** [comment]
Install pnpm and use it in place of npm, as in `npm install -g pnpm` then `pnpm i` to install dependencies and `pnpm run dev`

**Comment by yigitokar** [comment]
Thanks, it worked for me too! I feel like I should not close the issue though given that this is a tutorial.

**Comment by KrzysztofPoz** [comment]
Use npx with flag --use-pnpm

`npx create-next-app@latest nextjs-dashboard --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example" --use-pnpm`

**Comment by lunae** [comment]
Using `pnpm` worked for me too! In my case, I had to install `pnpm` first so that the `--use-pnpm` option would work.

**Comment by Malavsp** [comment]
For running we can still use 
```
bash
npm run dev
```

**Comment by stevenlevey** [comment]
> Thanks, it worked for me too! I feel like I should not close the issue though given that this is a tutorial.

Agreed, this is in the tutorial docs so it should be resolved OR commentary added.

For reference I appended the --use-pnpm. Thank you to @KrzysztofPoz

**Comment by tonyfarney** [comment]
Does anyone know the reason for it to work when using `pnpm` but not when using `npm`?

**Comment by benkaboo** [comment]
didn't work for me :-(

**Comment by HarikrishnanBalagopal** [comment]
Please fix this. I was following the tutorial and had to Google search the error to find this PR and the solution https://github.com/vercel/next-learn/issues/754#issuecomment-2178929399

Also the position of the `--use-pnpm` flag is important, `npx --use-pnpm` didn't work.

**Comment by princeanire** [comment]
I also encountered this error using Visual Studio, Dev Container with Node.js  + TypeScript,

I was able to set up the Next.js app using `npx create-next-app@latest nextjs-dashboard --use-pnpm --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example" `

**Comment by eunikester22** [comment]
> Install pnpm and use it in place of npm, as in `npm install -g pnpm` then `pnpm i` to install dependencies and `pnpm run dev` worked for me.

This is work for me.. Thanks a bunch :)

**Comment by leerob** [comment]
Hey everyone, sorry about this. The versions are a little complicated right now because we have updated this tutorial to use the Next.js 15 RC and React 19 RC. These versions should be moving from RC to stable soon.

In the meantime, I've [updated the tutorial](https://nextjs.org/learn/dashboard-app/getting-started) to instead recommending using pnpm. It's both faster and doesn't have this issue.

```bash
npm install -g pnpm
npx create-next-app@latest nextjs-dashboard --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example" --use-pnpm
```

Hope this helps and sorry for the inconvenience here!

**Comment by AimadYahyaoui** [comment]
when I do pnpm dev I have an error 

Could not find the module "/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/client/components/app-router.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at stringify (<anonymous>

**Comment by kelvinmacharia254** [comment]
> Hey everyone, sorry about this. The versions are a little complicated right now because we have updated this tutorial to use the Next.js 15 RC and React 19 RC. These versions should be moving from RC to stable soon.
> 
> In the meantime, I've [updated the tutorial](https://nextjs.org/learn/dashboard-app/getting-started) to instead recommending using pnpm. It's both faster and doesn't have this issue.
> 
> ```shell
> npm install -g pnpm
> npx create-next-app@latest nextjs-dashboard --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example" --use-pnpm
> ```
> 
> Hope this helps and sorry for the inconvenience here!

This still having an issue
```
c1 : fatal error C1083: Cannot open source file: '..\..\..\..\node-addon-api@5.1.0\node_modules\node-addon-api\nothing.c': No such file or directory
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:209:23)
gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Windows_NT 10.0.26100
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" build
gyp ERR! cwd D:\OneDrive\programming\learning\react\other_projects_and_resources\nextjs\nextjs_vercel_tutorial\nextjs-dashboard\node_modules\.pnpm\bcrypt@5.1.1\node_modules\bcrypt
gyp ERR! node -v v21.4.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok

node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build'
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\OneDrive\programming\learning\react\other_projects_and_resources\nextjs\nextjs_vercel_tutorial\nextjs-dashboard\node_modules\.pnpm\bcrypt@5.1.1\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
node-pre-gyp ERR! System Windows_NT 10.0.26100
node-pre-gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "D:\\OneDrive\\programming\\learning\\react\\other_projects_and_resources\\nextjs\\nextjs_vercel_tutorial\\nextjs-dashboard\\node_modules\\.pnpm\\bcrypt@5.1.1\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp.js" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\OneDrive\programming\learning\react\other_projects_and_resources\nextjs\nextjs_vercel_tutorial\nextjs-dashboard\node_modules\.pnpm\bcrypt@5.1.1\node_modules\bcrypt
node-pre-gyp ERR! node -v v21.4.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok

Failed to execute 'C:\Program Files (x86)\nodejs\node.exe C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build' (7.5s)

pnpm install has failed.
```

**Comment by leerob** [comment]
This should be a non-issue now that React 19 stable has been released!

**Comment by kelvinmacharia254** [comment]
Something was up with my node installation. Reinstalled it. All works fine now
