### ISSUE TITLE
Minor file name typo

### ISSUE THREAD

**Issue by alexander-john** [vercel/next-learn#755]
On the following link, https://nextjs.org/learn/dashboard-app/fetching-data#parallel-data-fetching there is a minor typo of the file name "/app/lib/data.js". I believe it should be "/app/lib/data.ts" as indicated in the text above the instructions.

![first](https://github.com/vercel/next-learn/assets/13820251/2490738f-87a2-400b-af51-e662d87abe94)

Close up:
![sec](https://github.com/vercel/next-learn/assets/13820251/24f484b4-a8e8-4755-b303-666897426081)

I think this was also mentioned in issue #581

**Comment by leerob** [comment]
Thank you! Fixing.
