### ISSUE TITLE
Chapter 15: Typo in `Updating the login form` 

### ISSUE THREAD

**Issue by miroim** [vercel/next-learn#756]
**Typo Issue Report**

**Issue Description:**

A minor typo has been discovered on [Chapter 15 - Updating the login form](https://nextjs.org/learn/dashboard-app/adding-authentication#updating-the-login-form), according to the `login-form.tsx` in `starter-example` and `final-example`, `button` should be replace with `Button` component and highlighting is only required on line `67` .
https://github.com/vercel/next-learn/blob/de76b002632d28d6e815983da486ca0a52657121/dashboard/starter-example/app/ui/login-form.tsx#L58-L60
https://github.com/vercel/next-learn/blob/de76b002632d28d6e815983da486ca0a52657121/dashboard/final-example/app/ui/login-form.tsx#L67-L69

**Before:**

![image](https://github.com/vercel/next-learn/assets/22488175/23b9efb5-a3c4-4bea-8b7a-54b5b0cfda5c)

**After:**

![image](https://github.com/vercel/next-learn/assets/22488175/8285cbc3-7ca9-4f09-ab01-a600e14314a6)

Related: https://github.com/vercel/next-learn/pull/748

**Comment by leerob** [comment]
Thank you! Fixing.
