### ISSUE TITLE
dependencies conflict when learning next.js course -> https://nextjs.org/learn

### ISSUE THREAD

**Issue by abdulrehman3725** [vercel/next-learn#757]
Hi Delba, 

I am a newbie in Next.js and wanted to take a session from the nextjs.org/learn course. 
I used their installation command but faced the below errors. I tried to downgrade both react reactdom and next.js version but all in vain.

**COMMAND**

`npx create-next-app@latest nextjs-dashboard --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example"`
 
```
Installing packages. This might take a couple of minutes.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@19.0.0-rc-6230622a1a-20240610
npm ERR! node_modules/react
npm ERR!   react@"19.0.0-rc-6230622a1a-20240610" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 16" from @heroicons/react@2.1.4
npm ERR! node_modules/@heroicons/react
npm ERR!   @heroicons/react@"^2.0.18" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/abdulrehmankhan/.npm/_logs/2024-06-22T21_13_21_418Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/abdulrehmankhan/.npm/_logs/2024-06-22T21_13_21_418Z-debug-0.log

Aborting installation.
  npm install has failed.
```

**Comment by abdulrehman3725** [comment]
I tried to react 18 
next 14
and react 19

no success. I guess there are some issues in the package.json.

i am waiting for your kind response.

**Comment by estefrare** [comment]
Fix it installing dependencies with `pnpm`: 
```
pnpm i
```

**Comment by abdulrehman3725** [comment]
npm i?  
pnpm is new?

**Comment by estefrare** [comment]
It is an alternative package manager for Node.js. It is a drop-in replacement for npm, but faster and more efficient.
Next's course documentation suggests its use. (https://nextjs.org/learn/dashboard-app/getting-started#running-the-development-server)

**Comment by abdulrehman3725** [comment]
You saved my life!

**Comment by abdulrehman3725** [comment]
for others who might be new

Just install pnpm -> npm install -g pnpm

and then use it
