### ISSUE TITLE
Chapter 14: TS error when import 'useActionState' from React. 

### ISSUE THREAD

**Issue by estefrare** [vercel/next-learn#758]
There is a Typescript error when importing 'useActionState' from 'react', used in [server-side-validation](https://nextjs.org/learn/dashboard-app/improving-accessibility#server-side-validation) section.

```
import { useActionState } from 'react';
```
<img width="574" alt="image" src="https://github.com/vercel/next-learn/assets/20587232/3035a577-00f4-4209-ac80-0e4f460ac890">

--- 
It causes a deployment error on Vercel:

<img width="1238" alt="image" src="https://github.com/vercel/next-learn/assets/20587232/00de5e2f-5393-48f7-9f48-72af29a5de72">

---

It is fixed updating `@types/react`  from *18.2.21* to *18.3.3* in `package.json`
```
  ...
  "devDependencies": {
  ...
    "@types/react": "18.3.3",
  ...
```

**Comment by leerob** [comment]
Thank you! This has been fixed.
