### ISSUE TITLE
Chapter 6: Error while customers table seeding

### ISSUE THREAD

**Issue by yuliya-d98** [vercel/next-learn#762]
While running "pnpm seed" in [Chapter 6](https://nextjs.org/learn/dashboard-app/setting-up-your-database#seed-your-database) I've got this error:

![image](https://github.com/vercel/next-learn/assets/83913169/00f20c26-7f15-4940-904b-282a2aa12002)

In [placeholder-data.js](https://github.com/vercel/next-learn/blob/main/dashboard/starter-example/app/lib/placeholder-data.js) file in 89 row we are trying to get customers[7].id, but customers array's length is 7, so last element is customers[6]

Purposed solution:
Replacing customers[7].id with customers[6].id

**Comment by leerob** [comment]
Fixed here https://github.com/vercel/next-learn/pull/764.
