### ISSUE TITLE
Not the same Issue to install project 

### ISSUE THREAD

**Issue by AimadYahyaoui** [vercel/next-learn#763]
when I run pnpm dev 

when I open the link to see, in compile moment

Error: Could not find the module "/Users/aimadyahyaoui/Documents/DEV/ReactJS/NextJS#2/nextjs-dashboard/node_modules/.pnpm/next@15.0.0-canary.28_@babel+core@7.24.6_react-dom@19.0.0-rc-6230622a1a-20240610_react@19.0.0-rc-6230622a1a-20240610/node_modules/next/dist/client/components/app-router.js#" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at stringify (<anonymous>)

**Comment by AimadYahyaoui** [comment]
#759 the same pb

**Comment by joequery** [comment]
I had a similar issue within a vscode devcontainer. It worked on the MacOS machine itself though.

**Comment by AimadYahyaoui** [comment]
> I had a similar issue within a vscode devcontainer. It worked on the MacOS machine itself though.

Ok it could be a problem with my mac... 
it work on Windows so.. 

I have remove all node from my mac and reinstall but still have the issue.

I just have to Reset my mac. Have fun 🙃
