### ISSUE TITLE
Revenue chart not showing

### ISSUE THREAD

**Issue by abdulrehman3725** [vercel/next-learn#767]
From Chapter 7 in Learn Next Course I have followed the same step but I do not see a chart
<img width="1440" alt="image" src="https://github.com/vercel/next-learn/assets/26308666/ac56fef3-6c78-40a9-a2a6-c61373817a2b">

Also, I see a warning in the console. Does that relate to this?

<img width="1440" alt="image" src="https://github.com/vercel/next-learn/assets/26308666/a4549808-0ac2-4be9-b621-50692eecba30">

**Comment by abdulrehman3725** [comment]
Same is for the latest invoices

<img width="1440" alt="image" src="https://github.com/vercel/next-learn/assets/26308666/5be383cd-0450-4a89-9561-5f573709e78a">

**Comment by abdulrehman3725** [comment]
I uncommented the code inside the LatestInvoice and Revenue Chart componentn

**Comment by clarafalisha** [comment]
i got same error, how can you solve it?

**Comment by leerob** [comment]
Seems resolved!
