### ISSUE TITLE
chapter 6 : there is no "seed" folder inside app/ folder

### ISSUE THREAD

**Issue by clarafalisha** [vercel/next-learn#769]
not seeing a seed folder inside app folder after running npm install @vercel/postgres, as well as the database not showing data tables in vercel

**Comment by abdulrehman3725** [comment]
you need to check script folder
There you will see seed.js

**Comment by abdulrehman3725** [comment]
and you need to run following command to see tables in data tables in vercel

`pnpm seed`

**Comment by rachelcolby11** [comment]
@abdulrehman3725 Thanks -- just tried running `pnpm seed` and got the following:

` ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "seed" not found`

Is there any other way to seed the database?

**Comment by abdulrehman3725** [comment]
I have checked the chapter and they have changed the content.

@delbaoliveira  please update on this, the next learn course lesson is showing different and there is not app folder.

**Comment by abdulrehman3725** [comment]
@rachelcolby11  @clarafalisha 

You need to pull following code from this link:  
https://github.com/vercel/next-learn/tree/main/dashboard/starter-example
<img width="1440" alt="image" src="https://github.com/vercel/next-learn/assets/26308666/be3827bb-93e5-45f8-940c-eb0e52ce6db9">


Then follow the next js lesson from this link -> https://nextjs.org/learn/dashboard-app/setting-up-your-database

It will work

**Comment by ShifterNathan** [comment]
I'm also following the chapter 6 of the course. I took a slightly different approach with npm instead of pnpm.
This is what I did to solve the seeder issue:

Go to your `packages.json`, and write the following under  `"scripts": {}`:

`"seed": "node scripts/seed.js"`

Make sure you copied properly the values of all the env variables and renamed the file to just `.env`

Install `npm install dotenv` if it gives you problem add the `--force` at the end

Then, in `app/scripts/seed.js` write this import at the top of the file: `require('dotenv').config();`
  
Now, to populate your vercel database: instead of going to `localhost:3000/seed` execute the command you placed in the executable scripts: `npm run seed` 
  
And that's all, you can continue the lessons. 

Hope this helps.

**Comment by GuiTarSparTan** [comment]
ty @ShifterNathan your solution works perfectly.

**Comment by anshal1** [comment]
@ShifterNathan  In seed.js the placeholder data is getting imported using `require` statement
`const {
  invoices,
  customers,
  revenue,
  users,
} = require("../app/lib/placeholder-data.js");
`
And the placeholder data is getting exported from the `.ts` file using `export` statement so it's not working

**Comment by yigitokar** [comment]
**My understanding:**
The earlier version of the course had a folder called scripts in the root directory which has seed.js file. The content of the seed.js file is very similar to the route.ts file mentioned in the course. However when you follow the course, you obviously encounter with a problem(no seed folder under app directory)

**Solution:**

- create a folder called seed under the app folder.

- create a route.ts file and copy-paste the content from the original github repo: https://github.com/vercel/next-learn/blob/main/dashboard/starter-example/app/seed/route.ts

**Comment by Malavsp** [comment]
@rachelcolby11 
I suggest adding in seed.js
```bash
require('dotenv').config();
```

**Comment by Kofiastro** [comment]
@yigitokar It worked out.Thank you

**Comment by ItsmeEric** [comment]
@abdulrehman3725 I followed your suggestion and it worked. Thank you!

**Comment by abdulrehman3725** [comment]
@ItsmeEric  Welcome!

**Comment by joaquincodigo** [comment]
> I'm also following the chapter 6 of the course. I took a slightly different approach with npm instead of pnpm. This is what I did to solve the seeder issue:
> 
> Go to your `packages.json`, and write the following under `"scripts": {}`:
> 
> `"seed": "node scripts/seed.js"`
> 
> Make sure you copied properly the values of all the env variables and renamed the file to just `.env`
> 
> Install `npm install dotenv` if it gives you problem add the `--force` at the end
> 
> Then, in `app/scripts/seed.js` write this import at the top of the file: `require('dotenv').config();`
> 
> Now, to populate your vercel database: instead of going to `localhost:3000/seed` execute the command you placed in the executable scripts: `npm run seed`
> 
> And that's all, you can continue the lessons.
> 
> Hope this helps.

It solved my problem. Thank you !

**Comment by leerob** [comment]
Sorry about this. Made this more specific to start with this file commented out, then uncomment it and run it, and then you can delete it.

https://github.com/vercel/next-learn/commit/d379162091cac7ea4d0e3054a9fb527c00596264
