### ISSUE TITLE
Chapter 14  Improving Accessibility - useActionState is not available in React

### ISSUE THREAD

**Issue by dtknepper** [vercel/next-learn#775]
Uppon importing useActionState like so:
`import { useActionState } from 'react';`

The following error appears: 
`Module '"react"' has no exported member 'useActionState'.ts(2305)` 

When searching on Google, the official [React Documentation](https://react.dev/reference/react/useActionState) actually says that the `useActionState` is still an experimental feature in their Canary channel.

I assume this means that when using the stable version of React, this Hook is not available yet and can therefore not be used.

If I am completely wrong on this topic, please explain me what I am doing wrong! I'm not doing this course because I am so good at this all already ;)

**Comment by leerob** [comment]
I am not able to reproduce, can you share more about what you're seeing? Can you restart your TypeScript server?

**Comment by braxtonb** [comment]
@dtknepper - Ran into something similar, @leerob 's suggestion to restart the Typescript server solved it on my end

The following steps may be helpful
1. Copy final-example's [package.json](https://github.com/vercel/next-learn/blob/main/dashboard/final-example/package.json)
2. Run `pnpm i` to install latest dependencies
3. Restart Typescript server using `cmd + shift + p` and select `TypeScript: Restart TS Server`

<img width="889" alt="Screenshot 2024-07-06 at 7 58 48 PM" src="https://github.com/vercel/next-learn/assets/13091519/b9b3e6fe-7ff9-438b-9669-4af76205f7f2">

4. After the TypeScript server restarts, ideally `useActionState` is defined

<img width="896" alt="Screenshot 2024-07-06 at 7 59 45 PM" src="https://github.com/vercel/next-learn/assets/13091519/de193c50-e7ca-44c1-b536-93c41d2e3194">

**Comment by dtknepper** [comment]
I have updated all my dependancies, and I still get this error. I was however able to still continue with this project by using `useFormState` from the `react-dom` dependancy. 

@braxtonb I see in you screenshot that you actually use the Canary release of React and not the general release. That's why you do not get this error.

**Comment by bwarman** [comment]
What are we supposed to do to get this working? Without the useActionState hook the entire tutorial grinds to a halt at chapter 14.

**Comment by dtknepper** [comment]
@leerob honestly, I think it's quite weird to depend on a `canary` release for a tutorial that is made for beginners. Especially since there is never a mention of using this version as the NPM command to start the project is using the latest stable release and not the canary version. The command to start this tutorial is: `npx create-next-app@latest nextjs-dashboard --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example" --use-pnpm` On top of that using a `canary` version which is most likely still quite buggy for a beginner tutorial is not the smartest thing in my humble newcomer opinion.

@bwarman the easiest thing to do, is to use `useFormState` instead of the `useActionState` and change the import from `react` to `react-dom`. This will give almost the same behaviour.

**Comment by scottfennell-toptal** [comment]
I just encountered this error myself.  

I'm coming from a jQuery / old-school JS background and the zoo of dependencies, versions, and related errors is making it really hard for me to feel good about trying Next in any real capacity.  

I think it's best to keep the tutorial as stable as possible rather than bleeding edge.

**Comment by leerob** [comment]
@bwarman have you already restarted your TS server or the [steps mentioned above](https://github.com/vercel/next-learn/issues/775#issuecomment-2212055238)?

> the NPM command to start the project is using the latest stable release and not the canary version.

This is the `npx` command, which is a separate project (`create-next-app` is a CLI tool), which pulls the code for the specific example codebase as an argument.

If you would prefer to use `useFormState`, you can reference this [PR](https://github.com/vercel/next-learn/pull/748) and use the codebase at [`deca7c7`](https://github.com/vercel/next-learn/tree/deca7c766f4b33f9af1a9b2f0475f253f9abefc3).

**Comment by Sahil4883** [comment]
hey there i faced the same issue with the useActionState and couldn't find out how do i resolve it 
if there's any resolution regarding the error please let me know I'm looking forward to complete this whole course

**Comment by K332** [comment]
@Sahil4883 
[https://github.com/vercel/next-learn/issues/775#issuecomment-2226848274](url)
You can try useFormState to solve it

**Comment by skinnynoizze** [comment]
> @bwarman have you already restarted your TS server or the [steps mentioned above](https://github.com/vercel/next-learn/issues/775#issuecomment-2212055238)?
> 
> > the NPM command to start the project is using the latest stable release and not the canary version.
> 
> This is the `npx` command, which is a separate project (`create-next-app` is a CLI tool), which pulls the code for the specific example codebase as an argument.
> 
> If you would prefer to use `useFormState`, you can reference this [PR](https://github.com/vercel/next-learn/pull/748) and use the codebase at [`deca7c7`](https://github.com/vercel/next-learn/tree/deca7c766f4b33f9af1a9b2f0475f253f9abefc3).

or you could just make the tutorial work? you realized if you just clone the repo and run npm install it has dependecies errors and cant even build?

**Comment by skinnynoizze** [comment]
> @bwarman have you already restarted your TS server or the [steps mentioned above](https://github.com/vercel/next-learn/issues/775#issuecomment-2212055238)?
> 
> > the NPM command to start the project is using the latest stable release and not the canary version.
> 
> This is the `npx` command, which is a separate project (`create-next-app` is a CLI tool), which pulls the code for the specific example codebase as an argument.
> 
> If you would prefer to use `useFormState`, you can reference this [PR](https://github.com/vercel/next-learn/pull/748) and use the codebase at [`deca7c7`](https://github.com/vercel/next-learn/tree/deca7c766f4b33f9af1a9b2f0475f253f9abefc3).

Do you realized that if someon clones the repo 

> @bwarman have you already restarted your TS server or the [steps mentioned above](https://github.com/vercel/next-learn/issues/775#issuecomment-2212055238)?
> 
> > the NPM command to start the project is using the latest stable release and not the canary version.
> 
> This is the `npx` command, which is a separate project (`create-next-app` is a CLI tool), which pulls the code for the specific example codebase as an argument.
> 
> If you would prefer to use `useFormState`, you can reference this [PR](https://github.com/vercel/next-learn/pull/748) and use the codebase at [`deca7c7`](https://github.com/vercel/next-learn/tree/deca7c766f4b33f9af1a9b2f0475f253f9abefc3).

sounds like excuse to me. npm run install fails on a fresh clone of the repo. thats what it is.

**Comment by skinnynoizze** [comment]
> [This](https://stackoverflow.com/questions/78687164/cant-import-useactionstate-from-react-following-next-js-tutorial-next-js) worked for me: npm i @types/react@18.3.3 npm install --legacy-peer-deps next@rc react@rc react-dom@rc

Thanks man. What a nightmare of tutorial lol.

**Comment by leerob** [comment]
React 19 (and types) are now stable: https://github.com/vercel/next-learn/pull/946
