### ISSUE TITLE
Invoice Entries Repeat in Production

### ISSUE THREAD

**Issue by Vihershunde** [vercel/next-learn#783]
When deploying my application to Vercel, regardless of react and next and react version, I encountered an issue where entries in the Invoice component repeat. However, this bug does not occur only when using Next.js 14 and React 18 locally.

To Reproduce

Upgrade the application to Next.js 15 and React 19.
Deploy the application to Vercel.
Navigate to the dashboard where the Invoice component is rendered.
Observe the repeated entries in the Invoice component.

**Expected behavior**

The Invoice component should display each entry uniquely, as it does in the development environment and with Next.js 14 and React 18.

Screenshots

Bug with Next.js 15 and React 19:
![image](https://github.com/vercel/next-learn/assets/111138052/0c97929b-528b-4baf-8d8b-3da0f7ebf885)

Works Correctly with Next.js 14 and React 18 (only locally):
![image](https://github.com/vercel/next-learn/assets/111138052/fb5570e1-2c31-44fd-a6e3-96e04eb8207d)

Additional context

I have verified that the data source is consistent and does not contain duplicates.

If there are known issues or similar reports, please guide me on potential fixes or workarounds.

Thank you!

**Comment by leerob** [comment]
Hey there, I am not able to reproduce this issue. Could you compare you code with the completed `final-example` folder here?

**Comment by Vihershunde** [comment]
Thanks, for your reply!

The invoices were somehow duped in the database so the app rendered multiple.

Removing duplicates fixed the problem.

Thanks again for the help and sorry for bothering you 😘
