### ISSUE TITLE
learn-starter 404 - page not found

### ISSUE THREAD

**Issue by YangyangU** [vercel/next-learn#785]
When i was try to use "npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"",i got the tips "Please check that the repository exists and try again." And i check the github ,just find  404 - page not found

**Comment by leerob** [comment]
It looks like there is a typo in that URL. Did you copy paste it from somewhere?

**Comment by YangyangU** [comment]
I am copy from "https://www.nextjs.cn/learn/basics/create-nextjs-app/setup"

**Comment by leerob** [comment]
Ah, we do not control that repository. That is from the community.
