### ISSUE TITLE
Missing deps for prettier to work on vscode

### ISSUE THREAD

**Issue by zadokdaniel** [vercel/next-learn#786]
As I tried the tutorial, I noticed prettier isn't working anymore. 

VSCode's prettier output gave the following errors: 

> Error: Cannot load Prettier version from package.json
> Error: Cannot find module '@vercel/style-guide/prettier'

both needed by prettier.config.js
fixed by installing the missing packages as devDeps, and also `prettier-plugin-tailwindcss` which is required in the prettier.config file 

`pnpm -D i @vercel/style-guide prettier prettier-plugin-tailwindcss`

Please confirm my understanding of the problem and the fix and if needed I'll post a PR

**Comment by zrbecker** [comment]
I have this same exact problem. After I install the above packages, my prettier stops reporting an error, but it still doesn't format my code.

If I delete `prettier.config.js` it will successfully format it with the default prettier settings. Is the @vercel/style-guide to just do minimal reformatting of code? Seems to defeat the purpose.

Seems like the tutorial is not properly maintained unfortunately.

**Comment by zadokdaniel** [comment]
Have you tried reloading vscode window?

**Comment by zrbecker** [comment]
Yes, I just moved on to other things. I didn't really need to tutorial, I just figured it'd be entertaining to go through. 

My prettier works fine in the projects I setup.

**Comment by leerob** [comment]
https://github.com/vercel/next-learn/commit/d379162091cac7ea4d0e3054a9fb527c00596264
