### ISSUE TITLE
database not seeding

### ISSUE THREAD

**Issue by Akuu426** [vercel/next-learn#796]
I uncommented the route.ts file and loaded the http://localhost:3000/seed but I'm not getting the 'Database seeded succesfully'. also checking the database data, there is no information on customers or invoices.

**Comment by AldinaSculac** [comment]
Don't forget to comment or delete this part inside `GET()` function:
```
  // return Response.json({
  //   message:
  //     'Uncomment this file and remove this line. You can delete this file when you are finished.',
  // });
```

**Comment by Akuu426** [comment]
Yes. Later figured it out. Also closed the issue afterwards. Thanks. Sent from my iPhoneOn 10 Jul 2024, at 19:48, Aldina Sculac ***@***.***> wrote:﻿
Don't forget to comment or delete this part inside GET() function:
  // return Response.json({
  //   message:
  //     'Uncomment this file and remove this line. You can delete this file when you are finished.',
  // });
