### ISSUE TITLE
NonErrorEmittedError

### ISSUE THREAD

**Issue by debboutr** [vercel/next-learn#81]
I just tries to go through the section on converting this app to Typescript and can't read through this error when trying to run the dev server? I went through all of the files that I changed a couple of times but still don't see what the problem is?

```
error - ./pages/_app.ts
NonErrorEmittedError: (Emitted value instead of an instance of Error) 
  x Expected '>', got '{'
   ,-[/home/rick/tmp/nextjs-blog/pages/_app.ts:5:3]
 5 | return <Component {...pageProps} />
   :                   ^
   `----

Caused by:
    0: failed to process js file
    1: failed to process input file
    2: Syntax Error

```

**Comment by martin-1988** [comment]
Try to rename the file `_app.ts` to `_app.tsx`

https://stackoverflow.com/questions/56871384/what-is-the-difference-between-ts-and-tsx-extensions-both-are-used-as-extensi#:~:text=tsx%20extension%20is%20used%20when,not%20support%20adding%20JSX%20Elements.

**Comment by debboutr** [comment]
that was it.  sorry for the confusion.
