### ISSUE TITLE
Learn Next.js tests with jest

### ISSUE THREAD

**Issue by martin-1988** [vercel/next-learn#82]
I just finished the Next.js basic course. Now I am trying to figure out, how to start with jest for testing. I followed [ his instructions](https://nextjs.org/docs/testing)

With the code from your starter tutorial I got this error.  After some research it seems I have to mock remark because jest doesn't support ESM really good.

All of this is new for me, so I like to ask if mocking remark is the right direction to go? It would be great to have a tutorial how to implement tests after finishing the tutorial.

```
SyntaxError: Cannot use import statement outside a module

      2 | import path from 'path';
      3 | import matter from 'gray-matter';
    > 4 | import { remark } from 'remark';
    
    ```

**Comment by leerob** [comment]
Hey! Check out our docs here on testing: https://nextjs.org/docs/testing
