### ISSUE TITLE
Chapter 2 import style not working

### ISSUE THREAD

**Issue by amyming112** [vercel/next-learn#846]
copying the code and importing global css does nothing to update the style. 

<img width="839" alt="Screenshot 2024-08-25 at 00 48 57" src="https://github.com/user-attachments/assets/5efbeac0-229d-4551-8c72-59d52a1f7f69">
<img width="967" alt="Screenshot 2024-08-25 at 00 48 43" src="https://github.com/user-attachments/assets/3c29423e-b6b9-46e7-9011-ab2346eeb60c">

**Comment by eiffel205566** [comment]
instead of 

`import '@app/ui/global.css'`

try 

`import '../app/ui/global.css'`

**Comment by amyming112** [comment]
Thanks. I tried a few different imports, including the import style from .. (from 2nd part of the tutorial), and I keep getting the below. same for chroms and safari. 

<img width="946" alt="Screenshot 2024-08-25 at 10 48 55" src="https://github.com/user-attachments/assets/2e2fd859-3e70-457b-843b-5e7e93cb6b4c">

**Comment by eiffel205566** [comment]
you shouldn't be running 
`npm i`

the doc is using "pnpm"
https://nextjs.org/learn/dashboard-app/getting-started#running-the-development-server

**Comment by LuamB** [comment]
I had the same issue, probably bc I ran `npm i` accidentally, but then I quit the process `ctl c` and ran `pnpm i`, so I thought it should be fine.
Anyways, deleting node_modules and running `pnpm i` again solved the issue, but there's still a warning in the terminal: 
(node:11645) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by GreytownSnowy** [comment]
I managed to get Chapter 2 working by changing:
import styles from '@/app/ui/home.module.css';
to 
import styles from './ui/home.module.css'

**Comment by leerob** [comment]
Looks like this was resolved
