### ISSUE TITLE
Error with the date-fns module

### ISSUE THREAD

**Issue by juanppdev** [vercel/next-learn#85]
![Screenshot_20220827-221331_Chrome](https://user-images.githubusercontent.com/81490579/187046567-b111ce9b-7ac6-4bea-b411-c55d5b1a42fe.jpg)

**Comment by beau-mind** [comment]
While in the "Dynamic Routes" tutorial, this error arises because `[id].js` is also counted as a post. See https://github.com/vercel/next-learn/pull/66 for a fix.
