### ISSUE TITLE
Chapter 10 PPR and Canary Dependencies

### ISSUE THREAD

**Issue by mdmahendri** [vercel/next-learn#892]
- I think chapter 10 deserves additional instruction to update dependencies to the latest canary available from [nextjs](https://github.com/vercel/next.js). Because leaving it to as it is will produce error and will unable to start the dev server.
- This method is preferred because the canary change version rappidly.
- The error i found if we use the stable version
```bash
D:\nextjs-dashboard>pnpm dev

> @ dev D:\nextjs-dashboard
> next dev --turbo

D:\nextjs-dashboard\node_modules\.pnpm\next@15.0.0_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__react@19.0.0-rc-cd22717c-20241013\node_modules\next\dist\server\config.js:241
            throw new CanaryOnlyError('experimental.ppr');
                  ^

CanaryOnlyError: The experimental feature "experimental.ppr" can only be enabled when using the latest canary version of Next.js.
    at assignDefaults (D:\nextjs-dashboard\node_modules\.pnpm\next@15.0.0_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__react@19.0.0-rc-cd22717c-20241013\node_modules\next\dist\server\config.js:241:19)
    at loadConfig (D:\nextjs-dashboard\node_modules\.pnpm\next@15.0.0_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__react@19.0.0-rc-cd22717c-20241013\node_modules\next\dist\server\config.js:843:32)
    at async Module.nextDev (D:\nextjs-dashboard\node_modules\.pnpm\next@15.0.0_react-dom@19.0.0-rc-cd22717c-20241013_react@19.0.0-rc-cd22717c-20241013__react@19.0.0-rc-cd22717c-20241013\node_modules\next\dist\cli\next-dev.js:189:14)

Node.js v20.18.0
 ELIFECYCLE  Command failed with exit code 1.
```

I need to change `package.json` for `next` to `"canary"` which equivalent as of now to `"15.0.2-canary.6"` then run `pnpm i` to resolve compatible `react` and `react-dom` version

```
...
    "next": "canary"
    ...
    "react": "19.0.0-rc-1631855f-20241023",
    "react-dom": "19.0.0-rc-1631855f-20241023",
...
```

**Comment by moylanm** [comment]
Thanks for the info. I ran `pnpm i next@canary` to solve the dev server startup issue.

**Comment by ashvinpanicker** [comment]
PPR is still experimental and under development

This error is mentioned on [Next.js docs](https://nextjs.org/docs/messages/ppr-preview)

**Comment by bluefire2121** [comment]
In the Next.js docs, following the recommendation `npm install next@canary` causes a dependency issue between React 18 and React 19. Need to use `pnpm install next@canary` instead.

**Comment by leerob** [comment]
We've now recommended to install canary as part of using PPR  - thanks!

**Comment by leochoo** [comment]
@leerob 
It seems like the change is not reflected on [Chapter 10](https://nextjs.org/learn/dashboard-app/partial-prerendering) yet?


I see it here instead. https://nextjs.org/docs/messages/ppr-preview

**Comment by drod3763** [comment]
Came here because I followed the tutorial in Chapter 10 and got the same error. The docs should be updated.

**Comment by aidanpatrickkane** [comment]
Yup, came with same issue as others. pnpm install next@canary fixed it for me

**Comment by geekysaurabh001** [comment]
This doesn't make sense as the canary version installed by pnpm is `15.1.1-canary.23` while the next version in stable form is `15.1.3` which is higher version.

**Comment by Riaz5687** [comment]
I was facing the same issue and was fixed with `pnpm i next@canary`

**Comment by bi1eygr** [comment]
> Came here because I followed the tutorial in Chapter 10 and got the same error. The docs should be updated.

Same!
