### ISSUE TITLE
Chapter 15 - Enabling Redirect in signOut

### ISSUE THREAD

**Issue by TIMN00** [vercel/next-learn#907]
Hi,

In Chapter 15 of the nextJS dashboard documentation, the signOut does not redirect to the login page given the sample code. I have added the following in /sidenav.tsx :

```
<form
                    action={async () => {
                        'use server';
                        await signOut({redirect: false});
                        redirect('/login');
                    }}
                >
```

Perhaps an update to the documentation should be made?

Hope this helps.

**Comment by baiwfg2** [comment]
If you try this example: https://next-learn-dashboard.vercel.sh , it will redirect to login page after signing out.
![image](https://github.com/user-attachments/assets/2695c430-06ef-4484-b173-7b5abcd48544)

But I find the URL is not right. Should be `https://next-learn-dashboard.vercel.sh/login` ?

**Comment by TIMN00** [comment]
I see the following issue was raised which also provides a solution for the redirect: https://github.com/vercel/next-learn/issues/904#issue-2627855899 . 

Noting that [auth documentation](https://authjs.dev/getting-started/installation?framework=Next.js ) requires "Add a Route Handler under /app/api/auth/[...nextauth]/route.ts." which solves this issue. Thanks
