### ISSUE TITLE
Chapter 6 : pnpm issue data not seeding on vercel (does not show "connected" on vercel dashboard)

### ISSUE THREAD

**Issue by main-xero** [vercel/next-learn#916]
I uncomment the app/seed/route file and run the pnpm command and get this error. 

```
PS C:\Users\xero\start\dash> pnpm i @vercel/postgres
 WARN  6 deprecated subdependencies found: are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, inflight@1.0.6, npmlog@5.0.1, rimraf@3.0.2
Already up to date
Progress: resolved 250, reused 224, downloaded 0, added 0, done
 WARN  Issues with peer dependencies found
.
└─┬ next 15.0.0
  ├── ✕ unmet peer react@"^18.2.0 || 19.0.0-rc-65a56d0e-20241020": found 19.0.0-rc-cd22717c-20241013
  └── ✕ unmet peer react-dom@"^18.2.0 || 19.0.0-rc-65a56d0e-20241020": found 19.0.0-rc-cd22717c-20241013

Done in 2.8s
```

Then I go to vercel data tab for the project I just deployed but the tab wont let me click the drop downs.

If it helps, here is my github repo...

https://github.com/cbmastery/next_dash/blob/main/app/seed/route.ts

**Comment by razvanthered** [comment]
You forgot to remove line 105 that is returning an empty object as json instead of calling the methods to seed the data
` return Response.json({});`

**Comment by cbmastery** [comment]
> You forgot to remove line 105 that is returning an empty object as json instead of calling the methods to seed the data ` return Response.json({});`

Ok I did so, then I pushed the commit and it still doesn't work. I re copied the .env.local files from vercel to my project and still no luck on the Data tab in Vercel.

**Comment by cbmastery** [comment]
> You forgot to remove line 105 that is returning an empty object as json instead of calling the methods to seed the data ` return Response.json({});`

The error terminal is throwing me seems to suggest that id doesn't like version 19 of react because it is looking for 18.2 when I run `pnpm i @vercel/postgres`

**Comment by razvanthered** [comment]
Try downgrading your react version in package.json to ^18.2.0 and then use pnpm i to refresh the modules

**Comment by leerob** [comment]
You can also move to the general `postgres` JavaScript package (we will likely update here) which works with any Postgres provider.

Further, we just updated to React 19 stable, which will fix some of those warnings.

https://github.com/vercel/next-learn/pull/946
