### ISSUE TITLE
No data option available  in the sidenav 

### ISSUE THREAD

**Issue by GhofranMohamed** [vercel/next-learn#928]
After seeding the database in chapter 6 I can't explore my data, since there's no data option in the side nav. Did the interface changed ? or did I do something wrong? 
![next-dashboard – Integration – Vercel - Google Chrome 11_19_2024 9_49_05 AM](https://github.com/user-attachments/assets/5fe44a3b-3079-489a-89c5-78717b7d9c35)

**Comment by delbaoliveira** [comment]
Hey @GhofranMohamed! Yes, the interface recently changed. We're updating Chapter 6, and have a PR which will allow you to query the database from a Route Handler: https://github.com/vercel/next-learn/pull/927
