### ISSUE TITLE
"Assets, Metadata, and CSS" does not follow on from previous tutorial

### ISSUE THREAD

**Issue by ChristopherHackett** [vercel/next-learn#94]
I am following the "Create your first app" tutorials in the order suggested 

The [setup says](https://nextjs.org/learn/basics/assets-metadata-css/setup) for Assets, Metadata, and CSS

> If you’re continuing from the previous lesson, you can skip this page. Click the button below to go to the next page.

but when you get to step 6 [it says ](https://nextjs.org/learn/basics/assets-metadata-css/css-styling)

> As you can see, our index page (http://localhost:3000/) already has some styles. If you look at your file structure, you'll see a folder called styles with two CSS files: a global stylesheet (globals.css), and a CSS module (Home.module.css).

However 
* there doesn't appear to be such file in that location
* CSS for `pages/index.js` is internal 

```shell
$ tree . --gitignore
.
├── README.md
├── package-lock.json
├── package.json
├── pages
│   ├── index.js
│   └── posts
│       └── first-post.js
└── public
    ├── favicon.ico
    └── images
        └── profile.jpg

4 directories, 7 files
```

The only notable deviation I have made is when starting my project originally today I used @lgaspari's version (identical to the current repo but with the current dependency issue fixed)
```shell
npx create-next-app nextjs-example --use-npm --example "https://github.com/lgaspari/next-learn/tree/master/basics/learn-starter"
```

**If you use `/assets-metadata-css-starter` instead of following along from `/learn-starter` you have the right files**

```shell
 tree . --gitignore 
.
├── README.md
├── package-lock.json
├── package.json
├── pages
│   ├── index.js
│   └── posts
│       └── first-post.js
├── public
│   ├── favicon.ico
│   └── vercel.svg
└── styles
    ├── Home.module.css
    └── globals.css

4 directories, 9 files
```

**Comment by lgaspari** [comment]
Nice finding @ChristopherHackett! After getting stuck at the beginning I didn't go that far, nonetheless I can now confirm this is an issue. Would be nice to update either the template or the docs to match.

**Comment by leerob** [comment]
The CSS has now been added here, thank you.
