### ISSUE TITLE
Navigate to localhost:3000/seed but not appear any table

### ISSUE THREAD

**Issue by JUANJOSEDOLL** [vercel/next-learn#940]
PLease help!

In my VSC terminal:
PS C:\react\nextjs-dashboard> pnpm run dev

> @ dev C:\react\nextjs-dashboard
> next dev --turbo

  ▲ Next.js 15.0.0 (turbo)
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 3.8s
 ○ Compiling /seed ...
 ✓ Compiled /seed in 4.1s
 GET /seed 200 in 5469ms

navigate to http://localhost:3000/seed

but in vercel neon console is empty.

amy github repo: https://github.com/JUANJOSEDOLL/nextjs-dashboard (.env is populated by the copy of .env code in local, not in repo who is empty

**Comment by JUANJOSEDOLL** [comment]
Thanks in advance

**Comment by JUANJOSEDOLL** [comment]
![Captura de pantalla (71)](https://github.com/user-attachments/assets/41779dc4-87dd-441b-a1ec-5691c8f935ab)

**Comment by chrishubbard62** [comment]
I am having an issue as well but did you try commenting out the return statement with wrapping the comment. 

![nextseed](https://github.com/user-attachments/assets/a0bb8394-b93d-4acc-9830-c617422bc281)

**Comment by Labmem-00** [comment]
@chrishubbard62 nice answer
