### ISSUE TITLE
Chapter 6: No Postgress SQL data base available, tutorial bottleneck

### ISSUE THREAD

**Issue by daninaydenow** [vercel/next-learn#951]
As stated in the chapter 

[Create a Postgres database](https://nextjs.org/learn/dashboard-app/setting-up-your-database#create-a-postgres-database)
" Next, to set up a database, click Continue to Dashboard and select the Storage tab from your project dashboard. Select Create Database. Depending on when your Vercel account was created, you may see the following options: Postgres (Powered by Neon), Neon, or Supabase. Choose your preferred provider and click Continue. "

The problem is that there is no option for PostgresSQL.

Please either update the tutorial to include a DB from the existing options, or provide some backwards compatible way to use Postgres.

**Comment by tobyguelly** [comment]
In the meantime you can use your own local database instead of using Vercel by using Docker.

```
docker run -d --name=postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres:latest
```

Then you have to rewrite the code using another Postgres client instead of the Vercel client. I did so using pq.

```
pnpm install pq
```

```ts
import { Client } from 'pg';

const client = new Client({
    host: "localhost",
    port: 5432,
    user: "postgres",
    password: "postgres",
    database: "postgres",
});

await client.connect();
```

Then just replace all calls to `client.sql` with `client.query` and everything should work without requiring a database from Vercel.

**Comment by RyanMG** [comment]
For anyone else learning on the fly for this change: https://node-postgres.com/features/queries

**Comment by kamalx** [comment]
I selected Neon from the marketplace and was able to proceed with the tutorial (today).

**Comment by daninaydenow** [comment]
At the end I decided to run a local Postgres db, to use the opportunity to learn SQL, and Postrgres specifically, as I'll need more DB knowledge anyways, if I am headed in the path of full-stack web dev. This chapter actually made me take a step back and expand my knowledge. I'm closing the issue, and thanks to everyone who replied ❤️
