### ISSUE TITLE
Chapter 11: error in React developer tools when clicking on page numbers in the pagination

### ISSUE THREAD

**Issue by antofopera** [vercel/next-learn#960]
React Developer Plugin:
```
Uncaught Error: Cannot reorder children for node "0" because no matching node was found in the Store.
Dismiss
The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1175534
    at v.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1140783)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1142390
    at bridgeListener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1552529)
```

Happens when you click on the page numbers in the `Pagination` component. The `React Developer Plugin` emits this error and crashes. There is no error log in the console, so is this just a plugin problem? Probably caused by using something new?

**Comment by leerob** [comment]
Hey there, that sounds like a plugin problem indeed. Could you try in incognito? That will help you verify it's from a plugin.
